package com.nitroapps.emoticons.helpers

import com.nitroapps.emoticons.EmoticonEntity

class HelperClass2 {
    companion object {
        fun generateData(): Array<EmoticonEntity> {
            val result = arrayOf(
                //WORRIED
                EmoticonEntity(5, "( ´△｀)", false),
                EmoticonEntity(5, "(　ﾟдﾟ)", false),
                EmoticonEntity(5, "(⊙…⊙ )", false),
                EmoticonEntity(5, "＼(°o°；）", false),
                EmoticonEntity(5, "~~旦_(･o･;)", false),
                EmoticonEntity(5, "ヽ(*´Д｀*)ﾉ", false),
                EmoticonEntity(5, ":;(∩´﹏`∩);:", false),
                EmoticonEntity(5, "｡:ﾟ*+;(●´･д･`●);+*ﾟ:｡", false),
                EmoticonEntity(5, "( ；´Д｀)", false),
                EmoticonEntity(5, "(-’๏_๏’-)", false),
                EmoticonEntity(5, "(･_-｡ )", false),
                EmoticonEntity(5, "(;´・`)>", false),
                EmoticonEntity(5, "(;´Д`)", false),
                EmoticonEntity(5, "（；￣ェ￣）", false),
                EmoticonEntity(5, "(;° ロ°)", false),
                EmoticonEntity(5, "(；☉_☉)", false),
                EmoticonEntity(5, "（’-’*)", false),
                EmoticonEntity(5, "(((( ;°Д°))))", false),
                EmoticonEntity(5, "((*゜Д゜)ゞ”", false),
                EmoticonEntity(5, "(」゜ロ゜)」", false),
                EmoticonEntity(5, "(＠￣Д￣＠；)", false),
                EmoticonEntity(5, "(´；Д；｀)", false),
                EmoticonEntity(5, "(´Д` )", false),
                EmoticonEntity(5, "（￣□￣；）", false),
                EmoticonEntity(5, "(￣□￣;)!!", false),
                EmoticonEntity(5, "(￣◇￣;)", false),
                EmoticonEntity(5, "(°◇°;)", false),
                EmoticonEntity(5, "（°o°；）", false),
                EmoticonEntity(5, "(~_~;)", false),
                EmoticonEntity(5, "（−＿−；）", false),
                EmoticonEntity(5, "(⊙︿⊙✿)", false),
                EmoticonEntity(5, "(⊙△⊙✿)", false),
                EmoticonEntity(5, "(꒪⌓꒪)", false),
                EmoticonEntity(5, "(ーー;)", false),
                EmoticonEntity(5, "（ｏ。ｏ；）", false),
                EmoticonEntity(5, "(ι´Д｀)ﾉ", false),
                EmoticonEntity(5, "《ﾟДﾟ》", false),
                EmoticonEntity(5, "(￣□￣)", false),
                EmoticonEntity(5, "＼(●o○;)ノ", false),
                EmoticonEntity(5, "∑(;°Д°)", false),
                EmoticonEntity(5, "⊙﹏⊙", false),
                EmoticonEntity(5, "⊙△⊙", false),
                EmoticonEntity(5, "┗┐ヽ(′Д、`*)ﾉ┌┛", false),
                EmoticonEntity(5, "◑.◑", false),
                EmoticonEntity(5, "ヽ（・＿・；)ノ", false),
                EmoticonEntity(5, "ヾ(´･ ･｀｡)ノ”", false),
                EmoticonEntity(5, "ヽ(￣д￣;)ノ", false),
                EmoticonEntity(5, "ヽ（゜ロ゜；）ノ", false),
                EmoticonEntity(5, "ヾ(=ﾟ･ﾟ=)ﾉ", false),
                EmoticonEntity(5, "ヽ(ﾟДﾟ)ﾉ", false),
                EmoticonEntity(5, "Σ（ﾟдﾟlll）", false),
                EmoticonEntity(5, "Σ(ﾟﾛﾟ｣)｣", false),
                EmoticonEntity(5, "ლ(´﹏`ლ)", false),
                EmoticonEntity(5, "ミ●﹏☉ミ", false),
                EmoticonEntity(5, "((유∀유|||))", false),
                EmoticonEntity(5, "(((╹д╹;)))", false),
                EmoticonEntity(5, "(ὀ⌓ὀ⑅)", false),
                EmoticonEntity(5, "（ ͒๑㉾ܫ㉾๑ ͒）", false),
                EmoticonEntity(5, "૮( ´⁰▱๋⁰` )ა", false),
                EmoticonEntity(5, "(•᷊᷄ṏ̮•᷊᷅)", false),
                EmoticonEntity(5, "૮( ‘▱๋’ )ა", false),
                EmoticonEntity(5, "(⌓⍢⌓〣)", false),
                EmoticonEntity(5, "(‖ⁱ꒪♖꒪)", false),
                EmoticonEntity(5, "૮( ᵒ̌ัૢ▱ᵒ̌ัૢ )ა", false),
                EmoticonEntity(5, "(｡´╹A╹｀｡)", false),
                EmoticonEntity(5, "Σ੧(❛□❛✿)", false),
                EmoticonEntity(5, "(◍•﹏•)", false),
                EmoticonEntity(5, "Σ(‘◉⌓◉’)", false),
                EmoticonEntity(5, "(☍﹏⁰)", false),
                EmoticonEntity(5, "(๑ ˊ͈ ᐞ ˋ͈ )ƅ̋", false),
                EmoticonEntity(5, "ଽ꒰⌓̈ ॢ꒱ ̉ ̉", false),
                EmoticonEntity(5, "(❁°͈▵°͈)", false),
                EmoticonEntity(5, "(๑⁺᷄д⁺᷅๑)◞՞", false),
                EmoticonEntity(5, "(╬⁽⁽ ⁰ ⁾⁾ Д ⁽⁽ ⁰ ⁾⁾)", false),
                EmoticonEntity(5, "( ᵒ̴̶̷᷄ д ᵒ̴̶̷᷅ )", false),
                EmoticonEntity(5, "ฅ(๑’Δ’๑)", false),
                EmoticonEntity(5, "(●ฅ́дฅ̀●)", false),
                EmoticonEntity(5, "(╯•﹏•╰)", false),
                EmoticonEntity(5, "(●´⌓`●)", false),
                EmoticonEntity(5, "(๑ˊ▵ॢˋ̥๑)", false),
                EmoticonEntity(5, "ヾ( •́д•̀ ;)ﾉ", false),
                EmoticonEntity(5, "(๑•﹏•)", false),
                EmoticonEntity(5, "(๑ó⌓ò๑)", false),
                EmoticonEntity(5, "(‘﹏*๑)", false),
                EmoticonEntity(5, "(･:ﾟдﾟ:･)", false),
                EmoticonEntity(5, "(ó﹏ò｡)", false),
                EmoticonEntity(5, "( •᷄⌓•᷅ )", false),
                EmoticonEntity(5, "╭(°A°`)╮", false),
                EmoticonEntity(5, "(´ ˙○˙ `)", false),
                EmoticonEntity(5, "┌┤´ﾟДﾟ`├┐", false),
                EmoticonEntity(5, "(๑ŏ _ ŏ๑)", false),
                EmoticonEntity(5, "~( ´•︵•` )~", false),
                EmoticonEntity(5, "(੭ ･᷄﹏･᷅)੭ु⁾", false),
                EmoticonEntity(5, "(･᷄ὢ･᷅)", false),
                EmoticonEntity(5, "๑•́ㅿ•̀๑) ᔆᵒʳʳᵞ", false),
                EmoticonEntity(5, "(๑o̴̶̷̥᷅﹏o̴̶̷̥᷅๑)ᵒᵐᵍᵎᵎᵎ", false),
                EmoticonEntity(5, "(´๑・⌓・｀)", false),
                EmoticonEntity(5, "(-｡-;", false),
                EmoticonEntity(5, "༼⁰o⁰；༽", false),
                EmoticonEntity(5, "(´⊙o⊙`；)", false),
                EmoticonEntity(5, "( ꒪ͧ⌓꒪ͧ ⊂", false),
                EmoticonEntity(5, "ヾ(◎o◎,,；)ﾉ", false),
                EmoticonEntity(5, "ヾ( ๑´д`๑)ﾂ", false),
                EmoticonEntity(5, "ヽ(▣﹏▣＼*≡*／▣﹏▣)ﾉ", false),
                EmoticonEntity(5, "･(•́⍛•̀; ≡ •́⍛•̀;)", false),
                EmoticonEntity(5, "ヾ(*ㅿ*๑)ﾂ", false),
                EmoticonEntity(5, "ヾ(๑ ³ㅿ³)ﾉ", false),
                EmoticonEntity(5, "(๏д๏)", false),
                EmoticonEntity(5, "(；๏д๏)", false),
                EmoticonEntity(5, "(๑ŐдŐ)b", false),
                EmoticonEntity(5, "(๑´•ω • `๑)", false),
                EmoticonEntity(5, "(๑´•д • `๑)", false),
                EmoticonEntity(5, "(´◑д◐｀)", false),
                EmoticonEntity(5, "(◐д◑´,,)", false),
                EmoticonEntity(5, "d(ŐдŐ๑)", false),
                EmoticonEntity(5, "₊·(ϱ॔﹏ᵕ๑॓)‧*", false),
                EmoticonEntity(5, "(๑⃙⃘°̧̧̧ㅿ°̧̧̧๑⃙⃘)", false),
                EmoticonEntity(5, "(ꐦ°᷄д°᷅)", false),
                EmoticonEntity(5, "(╬ ꒪Д꒪)ノ", false),
                EmoticonEntity(5, "(ૢ•᷄⊱•᷅ ╬)", false),
                EmoticonEntity(5, "ฅ=͟͟͞͞((꒪∆꒪;)ฅ", false),
                EmoticonEntity(5, "Σू(((ↂ⃙⃙⃚⌑ↂ⃙⃙⃚;)))ू", false),
                EmoticonEntity(5, "ヾ(((;ꈡ▱ꈡ;)))ﾉ", false),
                EmoticonEntity(5, "(｡ŏ﹏ŏ)", false),
                EmoticonEntity(5, "( ³⌓³)", false),
                EmoticonEntity(5, "( ◦⃝⃚⃙⃘⃙⃚⃙⃚⃙⃘⃑д◦⃝⃚⃙⃘⃙⃐ )∕⌚", false),
                EmoticonEntity(5, "(*´ﾟд)(дﾟ｀*)", false),
                EmoticonEntity(5, "(◞‸◟；)", false),
                EmoticonEntity(5, "(ʘᗩʘ’)", false),
                EmoticonEntity(5, "ᗜੂͦ﹏ᗜੂͦ", false),
                EmoticonEntity(5, "ʿʿ⁽⁽((⁰ⅈ⁰))⁾⁾ʾʾ", false),
                EmoticonEntity(5, "(*´･Д･)", false),
                EmoticonEntity(5, "˛૧(˵¯͒▱¯͒˵)", false),
                EmoticonEntity(5, "₍ॢ﹒︠⍛ू﹒︡ ॢ₎", false),
                EmoticonEntity(5, "“(#ﾟ,_ゝﾟ)”", false),
                EmoticonEntity(5, "“(ﾟc_,ﾟ｀｡)ﾌﾟ", false),
                EmoticonEntity(5, "( ´;ﾟ;ё;ﾟ;)", false),
                EmoticonEntity(5, "˚▱˚", false),
                EmoticonEntity(5, "‷̗ↂ凸ↂ‴̖", false),
                EmoticonEntity(5, "(ﾟAﾟ;)", false),
                EmoticonEntity(5, "(υ´Д｀)", false),
                EmoticonEntity(5, "(´Д｀υ)", false),
                EmoticonEntity(5, "(･д･｀o)", false),
                EmoticonEntity(5, "ヾ(ﾟдﾟ;)", false),
                EmoticonEntity(5, "(:.;ﾟ;Д;ﾟ;.:)", false),
                EmoticonEntity(5, "( ;ﾟдﾟ)", false),
                EmoticonEntity(5, "ヽ(;´Д｀)ﾉ", false),
                EmoticonEntity(5, "( ﾟÅﾟ；)", false),
                EmoticonEntity(5, "Σ(ﾟдﾟ；)", false),
                EmoticonEntity(5, "(ﾉﾟдﾟ(;￣Д￣)", false),
                EmoticonEntity(5, "ヾ(o´０ω０o)ﾉ", false),
                EmoticonEntity(5, "ヾ(o´０Д０o)ﾉ", false),
                EmoticonEntity(5, "<(´・д・｀)ノ", false),
                EmoticonEntity(5, "( ･ั﹏･ั)", false),
                EmoticonEntity(5, "⋆ᶿ̵᷄ ˒̼ ᶿ̵᷅⋆", false),
                EmoticonEntity(5, "(⌯꒪͒ .̼ ꒪͒)", false),
                EmoticonEntity(5, "=͟͟͞͞(꒪ᗜ꒪ ‧̣̥̇)", false),
                EmoticonEntity(5, "(❛ॕ⌓ ̣̣̥❛ॕ•ॢ)", false),
                EmoticonEntity(5, "Σ【*ﾟдﾟ*】", false),
                EmoticonEntity(5, "ଽ ૮( ⁰▱๋⁰ )ა", false),
                EmoticonEntity(5, "(๑°⌓°๑)", false),
                EmoticonEntity(5, "⁎ۜ′̛˷˒′̛⌕", false),
                EmoticonEntity(5, "๑ΘдΘ๑", false),
                EmoticonEntity(5, "(*´･Å･｀)", false),
                EmoticonEntity(5, "(﹗︠﹏︠﹗︡)", false),
                EmoticonEntity(5, "Σ(◦⃝⃚⃙⃘⃙⃚⃙⃚⃙⃘⃑△◦⃝⃚⃙⃘⃙⃐ﾉ)ﾉ", false),
                EmoticonEntity(5, "(☪̤̆_̆ ☪̤̆)", false),
                EmoticonEntity(5, "(✱°⌂°✱)", false),
                EmoticonEntity(5, "(˚☐˚! )/", false),
                EmoticonEntity(5, "(๑ʘ∆ʘ๑)", false),
                EmoticonEntity(5, "[･Å･` ○]", false),
                EmoticonEntity(5, "˛˛૧(˵¯͒▱¯͒˵)", false),
                EmoticonEntity(5, "(ⅈ▱ⅈ)", false),
                EmoticonEntity(5, "٩̋(•᷄◟̵◞̵•᷅‧̣̥̇)’`~✧", false),
                EmoticonEntity(5, "(⌇ຶД⌇ຶ)", false),
                EmoticonEntity(5, "(ૢ•᷄ۿ•᷅╬)", false),
                EmoticonEntity(5, "ల(｀°Δ°)", false),
                EmoticonEntity(5, "ଵ˛̼ଵ", false),
                EmoticonEntity(5, "ꀯ(⑈ꑒ᷅⺫ꑒ᷄)", false),
                EmoticonEntity(5, "(๑Ő д Ő๑)", false),
                EmoticonEntity(5, "(⋆ꁏہꁏ⋆)", false),
                EmoticonEntity(5, "(φ╻φ；)", false),
                EmoticonEntity(5, "(´-﹏-`；)", false),
                EmoticonEntity(5, "[･A･` ○]", false),
                EmoticonEntity(5, "ꐑ(*ꐌ﹋ꐌꐐ*)", false),
                EmoticonEntity(5, "(,,꒪꒫꒪,,)", false),
                EmoticonEntity(5, "ჴ˘ര‸രჴ", false),
                EmoticonEntity(5, "(੭ु⍨)੭ु⁾⁾", false),
                EmoticonEntity(5, "(;ↀ⌓ↀ)", false),
                EmoticonEntity(5, "(٭ॢꏿ᷄ ູ̠ꏿ᷅) ॢ", false),
                EmoticonEntity(5, "(≖╻≖；)", false),
                EmoticonEntity(5, "(*ꑒꆯꑒ*)冫", false),
                EmoticonEntity(5, "(◕⌓◕;)", false),
                EmoticonEntity(5, "(･д･)", false),
                EmoticonEntity(5, "(；ꏿ︿ꏿ)", false),
                EmoticonEntity(5, "•(◐﹏◐)•", false),
                EmoticonEntity(5, "꒰๑´ඹ.̫ ඹ `๑꒱", false),
                EmoticonEntity(5, "꒰(⋅⃝ ௰͡ ⋅⃝)꒱", false),
                EmoticonEntity(5, "⁎ً′̛˷˒ً′̛⌕", false),
                EmoticonEntity(5, "ꀯ(*ꑒꑘꑒ*)", false),
                EmoticonEntity(5, "(⁎·́ˍູˑ·̀)", false),
                EmoticonEntity(5, "ɭ ɿ (•᷄દ•᷅)", false),
                EmoticonEntity(5, "(.`･﹏･´.)", false),
                EmoticonEntity(5, "(ι´ Д｀)ﾉ", false),
                EmoticonEntity(5, "ヽ༼☯﹏☯༽ﾉ", false),
                EmoticonEntity(5, "੧║ ” ◔ Ĺ̯ ◔ ” ║و", false),
                EmoticonEntity(5, "c໒( ◐ ﹏ ◐ )७੭", false),
                EmoticonEntity(5, "⁝ʺ̢͈̗̋ •᷊᷄ṏ̮•᷊᷅ ˵̡̖̎̏⁝", false),
                EmoticonEntity(5, "ԅ[ •́ ﹏├┬┴┬┴", false),
                EmoticonEntity(5, "ゞ( ͡°⍛ ͡°)ゞ", false),
                EmoticonEntity(5, "ヽ༼⊙_⊙༽ﾉ", false),
                EmoticonEntity(5, "☁ 。७﹏७ 。☁", false),
                EmoticonEntity(5, "⊂(⊙д⊙)つ", false),
                EmoticonEntity(5, "(||ﾟДﾟ)", false),
                EmoticonEntity(5, "(ﾟДﾟ||)", false),
                EmoticonEntity(5, "┌╏ •́ – •̀ ╏┐", false),
                EmoticonEntity(5, "⊂((ﾒ´Д｀))⊃", false),
                EmoticonEntity(5, "o͡͡͡╮〳 ~ ☉ ₒ ☉ ~ 〵╭o͡͡͡", false),
                EmoticonEntity(5, "（ ´ﾟ,_」ﾟ）", false),
                EmoticonEntity(5, "ヾ(*’□’*)ｰ", false),
                EmoticonEntity(5, "(¤﹏¤)", false),
                EmoticonEntity(5, "●﹏●", false),
                EmoticonEntity(5, "༼ : ౦ ‸ ౦ : ༽", false),
                EmoticonEntity(5, "( ﾟдﾟ)", false),
                EmoticonEntity(5, "(σ･Д･)σ", false),
                EmoticonEntity(5, "(*σ´Д｀*)", false),
                EmoticonEntity(5, "Σ(っﾟДﾟ；)っ", false),
                EmoticonEntity(5, "ヽ(;ﾟ;Д;ﾟ;; )", false),
                EmoticonEntity(5, "(´д｀ι)", false),
                EmoticonEntity(5, "(´エ｀；)", false),
                EmoticonEntity(5, "(-∀-`; )", false),
                EmoticonEntity(5, "<(llﾟ◇ﾟll)>", false),
                EmoticonEntity(5, "ヾ(･ω･`；))ﾉ", false),
                EmoticonEntity(5, "ヾ((；´･ω･)ﾉ", false),
                EmoticonEntity(5, "ヾ(･ω･`；)ﾉ", false),
                EmoticonEntity(5, "(･∀･；)", false),
                EmoticonEntity(5, "o┤*´Д｀*├o", false),
                EmoticonEntity(5, "(；´ﾟДﾟ)ゞ", false),
                EmoticonEntity(5, "(;ﾟ;Д;ﾟ；;)", false),
                EmoticonEntity(5, "w(´ﾟДﾟ｀)w", false),
                EmoticonEntity(5, "(# ﾟДﾟ)", false),
                EmoticonEntity(5, "ヾ(ﾟдﾟ)ﾉﾞ", false),
                EmoticonEntity(5, "m(*´Д｀)m", false),
                EmoticonEntity(5, "(；´･Д･)", false),
                EmoticonEntity(5, "(*;´□`)ゞ", false),
                EmoticonEntity(5, "ヽ(*´□`)ﾉﾞ", false),
                EmoticonEntity(5, "ヾ(;ﾟ;Д;ﾟ;)ﾉﾞ", false),
                EmoticonEntity(5, "|*´・Д・)r))ﾟ", false),
                EmoticonEntity(5, "/~＼o=(;ﾟﾛﾟ)=o/~＼", false),
                EmoticonEntity(5, "(*ﾉ´□`)ﾉ~", false),
                EmoticonEntity(5, "Σ(ﾟДﾟ;≡｀ﾟдﾟ)", false),
                EmoticonEntity(5, "(σ ´゜д゜)σ", false),
                EmoticonEntity(5, "( ﾟдﾟ )", false),
                EmoticonEntity(5, "ヾ(ﾟёﾟ*)ﾉ", false),
                EmoticonEntity(5, "Σヽ(゜Д゜；)ﾉ", false),
                EmoticonEntity(5, "(((ﾟДﾟ)))", false),
                EmoticonEntity(5, "((*｀ﾟдﾟ)ゞ", false),
                EmoticonEntity(5, "o(°ω°メ)Ｏ))", false),
                EmoticonEntity(5, "σ(°Д°*)", false),
                EmoticonEntity(5, "ヾ(◕д◕❀)ﾂ", false),
                EmoticonEntity(5, "ヾ(❀◕д◕)ﾉ", false),
                EmoticonEntity(5, "╰໒(⸝⸝⸝⚆Ĺ̯⚆⸝⸝⸝)७ノ", false),
                EmoticonEntity(5, "[ ∗ ◕ □ ◕ ∗ ]", false),
                EmoticonEntity(5, "へ[ : ⊚ ﹏ ⊚ : ]ง", false),
                EmoticonEntity(5, "ヽ(‘ºل͟º)ノ", false),
                EmoticonEntity(5, "( ˵ ◐ ︿ ◐ ˵ )", false),
                EmoticonEntity(5, "░ ര Ĺ̯ ര ░", false),
                EmoticonEntity(5, "╏ ⁰ ⌂ ⁰ ╏", false),
                EmoticonEntity(5, "⁞ ✪ ⌂ ✪ ⁞", false),
                EmoticonEntity(5, "へ( ̿̿ o ̿̿ )╮", false),
                EmoticonEntity(5, ".+:｡ヽUﾟДﾟUﾉﾟ.+:｡", false),
                EmoticonEntity(5, "[ : • 益 • : ]", false),
                EmoticonEntity(5, "╏ ˵ ✪ ﹏ ✪ ˵ ╏", false),
                EmoticonEntity(5, "▐ ” ⊗ ﹏ ⊗ ”▐", false),
                EmoticonEntity(5, "ヽ(◕﹏◕)ﾉ", false),
                EmoticonEntity(5, "ヽ[ ಡ ⌂ ಡ ]⊃", false),
                EmoticonEntity(5, "ԅ། , ◔ ﹏ ◔ , །ᓄ", false),
                EmoticonEntity(5, "ʕ･_･ ;ʔ≡ʕ; ･_･ʔ", false),
                EmoticonEntity(5, "~( ~´･_･`)~", false),
                EmoticonEntity(5, "┌┤´д`├┐", false),
                EmoticonEntity(5, "（ 　ﾟ々ﾟ）", false),
                EmoticonEntity(5, "(○´･д･)ﾉ", false),
                EmoticonEntity(5, "(*′口`)ﾉ", false),
                EmoticonEntity(5, "(oﾟ□ﾟ)o", false),
                EmoticonEntity(5, "ミ（゜д゜○）", false),
                EmoticonEntity(5, "ヽ(･д･｀｡)ﾉ", false),
                EmoticonEntity(5, "ヽ(´･д･`)ﾉ", false),
                EmoticonEntity(5, "ヽ(｡´･д･)ﾉ", false),
                EmoticonEntity(5, "o(･´д･｀o)))三(((o´･д｀･)o", false),
                EmoticonEntity(5, "（￣ー￣；）", false),
                EmoticonEntity(5, "(oﾐﾟﾛﾟﾐ)o", false),
                EmoticonEntity(5, "o(ﾐﾟﾛﾟﾐo)", false),
                EmoticonEntity(5, "(ﾟдﾟ)", false),
                EmoticonEntity(5, "ヾ(゜д゜)ノ", false),
                EmoticonEntity(5, "((((爾△爾))))", false),
                EmoticonEntity(5, "（●´･△･｀）", false),
                EmoticonEntity(5, "／(￣ロ￣;)＼", false),
                EmoticonEntity(5, "Σ(´ﾟωﾟ｀ )", false),
                EmoticonEntity(5, "(｡´･д･)o", false),
                EmoticonEntity(5, "o(ﾟДﾟ)っ", false),
                EmoticonEntity(5, "((´∀`;))", false),
                EmoticonEntity(5, "(( ´∀`;))", false),
                EmoticonEntity(5, "。(>_<;=;>_<)。", false),
                EmoticonEntity(5, "（；○□○）", false),
                EmoticonEntity(5, "(╯•ω•╰)", false),
                EmoticonEntity(5, "(๑•́ω•̀)", false),
                EmoticonEntity(5, "/･_･ヾ＼", false),
                EmoticonEntity(5, "ヽ(*´□｀*)ッ", false),
                EmoticonEntity(5, "Σ꒰๑•ॢд •ॢ๑꒱", false),
                EmoticonEntity(5, "Σ(,,oΔo,,*)", false),
                EmoticonEntity(5, "(๑º ﾛ º๑)", false),
                EmoticonEntity(5, "(。´д｀。)", false),
                EmoticonEntity(5, "Σ(`･Д･ﾉ)ﾉ", false),
                EmoticonEntity(5, "(οдО;)", false),
                EmoticonEntity(5, "(๑⊙ﾛ⊙๑)", false),
                EmoticonEntity(5, "(*´○∧○`*）", false),
                EmoticonEntity(5, "[*っ´･Å･]", false),
                EmoticonEntity(5, "◍´Д‵◍", false),
                EmoticonEntity(5, "（┓゜Ａ゜）┓", false),
                EmoticonEntity(5, "∩(￣□￣#)∩", false),
                EmoticonEntity(5, "o｜๑⊙Д⊙๑｜ツ", false),
                EmoticonEntity(5, "ლ(ﾟдﾟლ)", false),
                EmoticonEntity(5, "(*ﾟÅﾟ；*)", false),
                EmoticonEntity(5, "(✽ ﾟдﾟ ✽)", false),
                EmoticonEntity(5, "ヽ(*゜∀゜*)ノ", false),
                EmoticonEntity(5, "ﾍ(ﾟ∀ﾟﾍ)ﾍ(ﾟ∀ﾟﾍ)ﾍ(ﾟ∀ﾟﾍ)", false),
                EmoticonEntity(5, "(´д｀、)", false),
                EmoticonEntity(5, "ε=(ﾟ∀゜´)", false),
                EmoticonEntity(5, "(,,ﾟДﾟ)", false),
                EmoticonEntity(5, "(´σωσ*)", false),
                EmoticonEntity(5, "o(*´д`*)o", false),
                EmoticonEntity(5, "(´･⊥･｀)", false),
                EmoticonEntity(5, "((((｡(´°Α°｀)｡))))", false),
                EmoticonEntity(5, "f(^_^;", false),
                EmoticonEntity(5, "(´･Д･lll)ゞ", false),
                EmoticonEntity(5, "(°m°;)", false),
                EmoticonEntity(5, "(-∧-；)", false),
                EmoticonEntity(5, "ヾ(｡﹏｡)ﾉﾞ", false),
                EmoticonEntity(5, "₍₍ (̨̡ ‾᷄⌂‾᷅)̧̢ ₎₎", false),
                EmoticonEntity(5, "☂o(ﾟДﾟ = ﾟДﾟ)o ☂", false),
                EmoticonEntity(5, "☂o(⑅ﾟДﾟ = ﾟДﾟ)o ☂", false),
                EmoticonEntity(5, "=。:.ﾟ٩(⑅๑꒪﹏꒪๑)۶:.｡+ﾟ", false),
                //THINKING
                EmoticonEntity(6, "(;¬_¬)", false),
                EmoticonEntity(6, "（；¬＿¬)", false),
                EmoticonEntity(6, "(¬_¬)", false),
                EmoticonEntity(6, "(¬‿¬)", false),
                EmoticonEntity(6, "(¬ω¬)", false),
                EmoticonEntity(6, "( ͡° ͜ʖ ͡°)", false),
                EmoticonEntity(6, "( ¬_¬)", false),
                EmoticonEntity(6, "(҂⌣̀_⌣́)", false),
                EmoticonEntity(6, "(∩⌣̀_⌣́)", false),
                EmoticonEntity(6, "(ʃ⌣́,⌣́ƪ)", false),
                EmoticonEntity(6, "<(¬＿¬<)", false),
                EmoticonEntity(6, "m(￢0￢)m", false),
                EmoticonEntity(6, "눈_눈", false),
                EmoticonEntity(6, "( ་ ⍸ ་ )", false),
                EmoticonEntity(6, "⁝(๑⑈௰⑈)◞⁝˚º꒰꒱", false),
                EmoticonEntity(6, "(.﹒︣︿﹒︣.)", false),
                EmoticonEntity(6, "(ꆤ⍸ꆤ)", false),
                EmoticonEntity(6, "(⑅ ‘﹃’ )", false),
                EmoticonEntity(6, "(‾͈̑ ◟  ॢ‾͈̑๑)ഽ̵ᵘഽ̵ᵘ४꒰…꒱", false),
                EmoticonEntity(6, "ॱ॰⋆(˶ॢ‾᷄﹃‾᷅˵ॢ)ӵᵘᵐᵐᵞ♡♡♡", false),
                EmoticonEntity(6, "Σ(-᷅_-᷄๑)", false),
                EmoticonEntity(6, "(－‸ლ)", false),
                EmoticonEntity(6, "(•᷉ुε ू•᷈,)", false),
                EmoticonEntity(6, "๐छ ੂछ๐", false),
                EmoticonEntity(6, "| ू*꒦ິ꒳꒦ີ)｡oO", false),
                EmoticonEntity(6, "( ･᷄ㅂ･᷅ )", false),
                EmoticonEntity(6, "( ᵕ́ૢ‧̮ᵕ̀ૢ)‧̊·*", false),
                EmoticonEntity(6, "(❛ัॢᵕ❛ั ॢ)✩*ೃ.⋆", false),
                EmoticonEntity(6, "(  ु⁎ᴗ_ᴗ⁎)ु.｡oO", false),
                EmoticonEntity(6, "( •́ ⍨ •̀)", false),
                EmoticonEntity(6, "( ´⍪⌂⍪`)", false),
                EmoticonEntity(6, "(˃̴̀ᄇॢ˂̴́ ∗)", false),
                EmoticonEntity(6, "(๑•̆૩•̆)", false),
                EmoticonEntity(6, "(*´ ˘ `*).｡oO ( ♡ )", false),
                EmoticonEntity(6, "(º﹃º )", false),
                EmoticonEntity(6, "(*´﹃｀*)", false),
                EmoticonEntity(6, "(¯―¯٥)", false),
                EmoticonEntity(6, "( ｰ̀εｰ́ )", false),
                EmoticonEntity(6, "(눈_눈)", false),
                EmoticonEntity(6, "( ｡_｡)", false),
                EmoticonEntity(6, "(ಢ⊱ಢ ｡)", false),
                EmoticonEntity(6, "(ಡωಡ)", false),
                EmoticonEntity(6, "(*˘︶˘*).｡.:*♡", false),
                EmoticonEntity(6, "(´-ι_-｀)", false),
                EmoticonEntity(6, "v(´-ι_-｀)v", false),
                EmoticonEntity(6, "（´-`）.｡oO（）", false),
                EmoticonEntity(6, "| ू･᷄ω･᷅)｡oOஇo｡", false),
                EmoticonEntity(6, "(´._.`).｡oஇ()", false),
                EmoticonEntity(6, "(-｡-;", false),
                EmoticonEntity(6, "( מּ,_מּ)", false),
                EmoticonEntity(6, "(。ⓥдⓥ)ノ", false),
                EmoticonEntity(6, "(´-_ゝ-`)", false),
                EmoticonEntity(6, "( ﾟｰﾟ)", false),
                EmoticonEntity(6, "❤︎⁄⁄꒰* ॢꈍ◡ꈍ ॢ꒱.*˚‧", false),
                EmoticonEntity(6, "(❛ॕ௰❛ॕૢ๑)˚º꒰꒱", false),
                EmoticonEntity(6, "(〠_〠)", false),
                EmoticonEntity(6, "♒((⇀‸↼))♒", false),
                EmoticonEntity(6, "(,Ծ_Ծ,)", false),
                EmoticonEntity(6, "(ԾεԾ|||)", false),
                EmoticonEntity(6, "(.•̵̑⌓•̵̑)", false),
                EmoticonEntity(6, "ƪ(•̃͡•̃͡ ƪ", false),
                EmoticonEntity(6, "=͟͟͞͞ ऀืົཽ≀ ͔ ͕̮ ऀืົཽ✧॰৹꒰❢❢꒱", false),
                EmoticonEntity(6, "( ج_ج )", false),
                EmoticonEntity(6, "ღ˘◡˘ற♡.｡oO", false),
                EmoticonEntity(6, "=͟͟͞͞ ऀืົཽ≀ ͔ ͕̮ ऀืົཽ✧॰৹꒰꒱", false),
                EmoticonEntity(6, "(ー_ーゞ", false),
                EmoticonEntity(6, "|´ε ｀ゞ)*.。oO( )", false),
                EmoticonEntity(6, "【•】_【•】", false),
                EmoticonEntity(6, "בּ_בּ", false),
                EmoticonEntity(6, "טּ_טּ", false),
                EmoticonEntity(6, "לּ_לּ", false),
                EmoticonEntity(6, "מּ_מּ", false),
                EmoticonEntity(6, "סּ_סּ", false),
                EmoticonEntity(6, "תּ_תּ", false),
                EmoticonEntity(6, "ಠ , ಥ", false),
                EmoticonEntity(6, "(￢ε￢　)", false),
                EmoticonEntity(6, "(,,-`_●-)", false),
                EmoticonEntity(6, "(‾͈̑ ◟  ॢ‾͈̑๑)ഽ̵ᵘഽ̵ᵘ४꒰ ꒱", false),
                EmoticonEntity(6, "(◦ˇ _̆ ˇ◦)", false),
                EmoticonEntity(6, "⁽་º་⁾", false),
                EmoticonEntity(6, "(　`_ゝ´)", false),
                EmoticonEntity(6, "*¨*•.¸꒰๑ ᷄ω ᷅꒱", false),
                EmoticonEntity(6, "(ര⸏ुര)", false),
                EmoticonEntity(6, "(●･̆⍛･̆●)", false),
                EmoticonEntity(6, "(ு८ு_ .:)", false),
                EmoticonEntity(6, "(;￢＿￢)", false),
                EmoticonEntity(6, "(´～ヾ)", false),
                EmoticonEntity(6, "( ⁝ื ‸ ⁝ื )", false),
                EmoticonEntity(6, "(¬ -̮ ¬)", false),
                EmoticonEntity(6, "(⁽͈˙̑⁾˔̉⁽˙̑⁾͈)˚º꒰꒱", false),
                EmoticonEntity(6, "(⌍་д་⌌)", false),
                EmoticonEntity(6, "ᗜੂ௰ᗜੂ", false),
                EmoticonEntity(6, "(ꉺ⍸ꉺ)", false),
                EmoticonEntity(6, "(´ι_｀ )", false),
                EmoticonEntity(6, "(￢з￢)", false),
                EmoticonEntity(6, "(◞‸ლ)", false),
                EmoticonEntity(6, "(ღ✪ｖ✪)｡o○", false),
                EmoticonEntity(6, "(ᇂ_ᇂ|||)", false),
                EmoticonEntity(6, "( *´罒`* )", false),
                EmoticonEntity(6, "⸂⸂( ृ[▒͠]꒱⸒⸒⌕˚º꒰❣꒱", false),
                EmoticonEntity(6, "◔̯◔", false),
                EmoticonEntity(6, "(´⊂_｀人)", false),
                EmoticonEntity(6, "ε(´･●_･｀)з", false),
                EmoticonEntity(6, "(◔ૂ◔)", false),
                EmoticonEntity(6, "(•Ṵ•)", false),
                EmoticonEntity(6, "(ᇂ_Jᇂ)", false),
                EmoticonEntity(6, "(⁎छ˼̲̮छ)", false),
                EmoticonEntity(6, "( ꂧ᷆ ◞ ˑ̼̬ ◟ ꂧ᷇ )", false),
                EmoticonEntity(6, "|˄·͈༝·͈˄₎.｡oO", false),
                EmoticonEntity(6, "(ृᓎੁ⁎ ृ　)ुᐝ꒰꒱", false),
                EmoticonEntity(6, "┌༼ σ ‸ σ ༽┐", false),
                EmoticonEntity(6, "◤¬ ˒̫̮ ¬◥", false),
                EmoticonEntity(6, "(*´Д｀)=з", false),
                EmoticonEntity(6, "(〃´o｀)=3", false),
                EmoticonEntity(6, "┌[ O ʖ̯ O ]┐", false),
                EmoticonEntity(6, "(ノ◇≦。)", false),
                EmoticonEntity(6, "(/ヘ￣､)", false),
                EmoticonEntity(6, "(⊹◕ʖ̯◕)", false),
                EmoticonEntity(6, "―(´￢O￢)(￢O￢｀)―", false),
                EmoticonEntity(6, "(`L_` )", false),
                EmoticonEntity(6, "⇎_⇎", false),
                EmoticonEntity(6, "║ * ರ Ĺ̯ ರ * ║", false),
                EmoticonEntity(6, "( ´_>`)", false),
                EmoticonEntity(6, "(￢ω￢;A)", false),
                EmoticonEntity(6, "(⍞∻⍞ॢ)₎₎", false),
                EmoticonEntity(6, "┏། ﹒ _ ﹒ །┓", false),
                EmoticonEntity(6, "(；￢＿￢)", false),
                EmoticonEntity(6, "⁞ ˵ •̀ ل͟ •́ ˵ ⁞", false),
                EmoticonEntity(6, "〳 ͡° Ĺ̯ ͡° 〵", false),
                EmoticonEntity(6, "(•ṋ•)", false),
                EmoticonEntity(6, "ꏂ　: ृ⑆)˚º꒰꒱", false),
                EmoticonEntity(6, "˓˓₍ʔˊԶ͡ˋʕ₎˒˒", false),
                EmoticonEntity(6, "○o。／((-＿-メ))＼｡o○", false),
                EmoticonEntity(6, "(*ゝ(ェ)･)ﾉ.｡o○", false),
                EmoticonEntity(6, "（￢з￢）", false),
                EmoticonEntity(6, "(๏็ટૄ ๏็ (๏็ટૄ◟๏็ )", false),
                EmoticonEntity(6, "(｡･~･｡)", false),
                EmoticonEntity(6, "（─。─）", false),
                EmoticonEntity(6, "(*´∀｀).。o○", false),
                EmoticonEntity(6, "(p〒д〒q)", false),
                EmoticonEntity(6, "(✿╹m╹)", false),
                EmoticonEntity(6, "(´･＿･‘)", false),
                EmoticonEntity(6, "(；◔ิд◔ิ)", false),
                EmoticonEntity(6, "（´―оヽ）", false),
                EmoticonEntity(6, "Σ (°ζ‿°　)", false),
                EmoticonEntity(6, "། ﹒︣ ‸ ﹒︣ །", false),
                EmoticonEntity(6, "ɖී؀ීϸ", false),
                EmoticonEntity(6, "( ˇ÷ˇ　 )", false),
                EmoticonEntity(6, "୧╏ ՞ _ ՞ ╏୨", false),
                //WAVING
                EmoticonEntity(7, "“(`(エ)´)ノ", false),
                EmoticonEntity(7, "( ´ ▽ ` )ﾉ", false),
                EmoticonEntity(7, "(,, ･∀･)ﾉ゛", false),
                EmoticonEntity(7, "(;-_-)/", false),
                EmoticonEntity(7, "(｡･ω･)ﾉﾞ", false),
                EmoticonEntity(7, "(。･д･)ﾉﾞ", false),
                EmoticonEntity(7, "(｡´∀｀)ﾉ", false),
                EmoticonEntity(7, "(/・0・)", false),
                EmoticonEntity(7, "(´・ω・)ﾉ", false),
                EmoticonEntity(7, "(￣∠ ￣ )ﾉ", false),
                EmoticonEntity(7, "(=ﾟωﾟ)ノ", false),
                EmoticonEntity(7, "(¬_¬)ﾉ", false),
                EmoticonEntity(7, "(ノ^∇^)", false),
                EmoticonEntity(7, "＼(°o°；）", false),
                EmoticonEntity(7, "ヽ(´･ω･`)､", false),
                EmoticonEntity(7, "( ・_・)ノ", false),
                EmoticonEntity(7, "( ･ω･)ﾉ", false),
                EmoticonEntity(7, "( ´ ▽ ` )ﾉ", false),
                EmoticonEntity(7, "( ^_^)／", false),
                EmoticonEntity(7, "（ ゜ρ゜)ノ", false),
                EmoticonEntity(7, "( ﾟ▽ﾟ)/", false),
                EmoticonEntity(7, "(;-_-)ノ", false),
                EmoticonEntity(7, "(。-ω-)ﾉ", false),
                EmoticonEntity(7, "(。^_・)ノ", false),
                EmoticonEntity(7, "(*^･ｪ･)ﾉ", false),
                EmoticonEntity(7, "(*＾▽＾)／", false),
                EmoticonEntity(7, "(*￣Ｏ￣)ノ", false),
                EmoticonEntity(7, "(*●⁰ꈊ⁰●)ﾉ", false),
                EmoticonEntity(7, "(⁎ ✪͡ ◡͐✪͡ ⁎)ﾉ”", false),
                EmoticonEntity(7, "(^ _ ^)/", false),
                EmoticonEntity(7, "(^ Q ^)/", false),
                EmoticonEntity(7, "(^-^*)/", false),
                EmoticonEntity(7, "(^o^)/", false),
                EmoticonEntity(7, "(￣(oo)￣)ﾉ", false),
                EmoticonEntity(7, "(￣(ｴ)￣)ﾉ", false),
                EmoticonEntity(7, "(￣▽￣)ノ", false),
                EmoticonEntity(7, "(=ﾟωﾟ)ﾉ", false),
                EmoticonEntity(7, "(≧∇≦)/", false),
                EmoticonEntity(7, "(○´3｀)ﾉ", false),
                EmoticonEntity(7, "(o・・o)/", false),
                EmoticonEntity(7, "(o´ω`o)ﾉ", false),
                EmoticonEntity(7, "(ﾉ´∀｀*)ﾉ", false),
                EmoticonEntity(7, "@(o・ェ・)@ノ", false),
                EmoticonEntity(7, "＼( ･_･)", false),
                EmoticonEntity(7, "＼(-_- )", false),
                EmoticonEntity(7, "＼(-o- )", false),
                EmoticonEntity(7, "＼（＾∀＾）メ（＾∀＾）ノ", false),
                EmoticonEntity(7, "＼(＾▽＾*)", false),
                EmoticonEntity(7, "＼(￣O￣)", false),
                EmoticonEntity(7, "~(＾◇^)/", false),
                EmoticonEntity(7, "~ヾ ＾∇＾", false),
                EmoticonEntity(7, "~ヾ(＾∇＾)", false),
                EmoticonEntity(7, "╭(°ﾛ°”)╯", false),
                EmoticonEntity(7, "☆ﾐ(o*･ω･)ﾉ", false),
                EmoticonEntity(7, "ー( ´ ▽ ` )ﾉ", false),
                EmoticonEntity(7, "ヾ( ‘ – ‘*)", false),
                EmoticonEntity(7, "ヾ(-_-;)", false),
                EmoticonEntity(7, "ヽ(･∀･)ﾉ", false),
                EmoticonEntity(7, "ヾ(･ω･`｡)", false),
                EmoticonEntity(7, "ヾ(・ω・ｏ)", false),
                EmoticonEntity(7, "ヾ(｡･ω･｡)", false),
                EmoticonEntity(7, "ヾ(｡´･_●･`｡)☆", false),
                EmoticonEntity(7, "ヾ(＠⌒ー⌒＠)ノ", false),
                EmoticonEntity(7, "ヽ(๏∀๏ )ﾉ", false),
                EmoticonEntity(7, "ヾ(´･ω･｀)", false),
                EmoticonEntity(7, "ヾ(´(ｴ)｀ﾉﾞ", false),
                EmoticonEntity(7, "ヾ(´￢｀)ﾉ", false),
                EmoticonEntity(7, "ヾ(＾-＾)ノ", false),
                EmoticonEntity(7, "ヾ(＾∇＾)", false),
                EmoticonEntity(7, "ヽ(＾▽＾)人(＾▽＾)人(＾▽＾)ﾉ", false),
                EmoticonEntity(7, "ヽ(ﾟ◇ﾟ )ﾉ", false),
                EmoticonEntity(7, "ヾ(◍’౪`◍)ﾉﾞ♡", false),
                EmoticonEntity(7, "ヾ(◜▿‾ 三 ‾▿◝)ﾉ", false),
                EmoticonEntity(7, "ヾ(☆▽☆)", false),
                EmoticonEntity(7, "ヘ(‘◇’、)/", false),
                EmoticonEntity(7, "ヘ(゜Д、゜)ノ", false),
                EmoticonEntity(7, "ヘ(°￢°)ノ", false),
                EmoticonEntity(7, "ヘ(°◇、°)ノ", false),
                EmoticonEntity(7, "ﾍ(ﾟ∀ﾟ*)ﾉ", false),
                EmoticonEntity(7, "且_(ﾟ◇ﾟ；)ノﾞ", false),
                EmoticonEntity(7, "(*ﾟ⚙͠ ∀ ⚙͠)ﾉ", false),
                EmoticonEntity(7, "ヾ(oﾟｘﾟo)ﾉ", false),
                EmoticonEntity(7, "川o･-･)ﾉ", false),
                EmoticonEntity(7, "┻┳|･ω･)ﾉ", false),
                EmoticonEntity(7, "]ｮ◡◕ั⁎)ﾉ✰⁎*", false),
                EmoticonEntity(7, "(。･∀･)ﾉ", false),
                EmoticonEntity(7, "(^▽^)/ ʸᵉᔆᵎ", false),
                EmoticonEntity(7, "(ヾﾉ･ω･`)", false),
                EmoticonEntity(7, "(｀･ω･´)ﾉ", false),
                EmoticonEntity(7, "ヾ(´｡••｡`)ﾉ", false),
                EmoticonEntity(7, "(ﾉ)’ω`(ヾ)", false),
                EmoticonEntity(7, "(◍˃̶ᗜ˂̶◍)ﾉ”", false),
                EmoticonEntity(7, "ヾ( ´｡ •x• ｡` )ﾉ”", false),
                EmoticonEntity(7, "ヾ ^_^", false),
                EmoticonEntity(7, "ヾ(*´∀｀*)ﾉ", false),
                EmoticonEntity(7, "ヾ(๑╹ヮ╹๑)ﾉ”", false),
                EmoticonEntity(7, "ヾ(๑╹ꇴ◠๑)ﾉ”", false),
                EmoticonEntity(7, "ヾ(๑ㆁᗜㆁ๑)ﾉ”", false),
                EmoticonEntity(7, "*+( ๑´•ω•)۶”", false),
                EmoticonEntity(7, "(✿´꒳`)ﾉ°", false),
                EmoticonEntity(7, "ヾ(*❦ω❦)ノ", false),
                EmoticonEntity(7, "( ✪ワ✪)ノʸᵉᵃʰᵎ", false),
                EmoticonEntity(7, "꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥", false),
                EmoticonEntity(7, "(♦亝д 亝)ﾉ", false),
                EmoticonEntity(7, "ヾ(^ิ∀^ิ)", false),
                EmoticonEntity(7, "ヾ(Ő∀Ő๑)ﾉ", false),
                EmoticonEntity(7, "(✧∇✧)╯", false),
                EmoticonEntity(7, "╰(✧∇✧)", false),
                EmoticonEntity(7, "(；ﾞﾟ’ωﾟ’):⁾", false),
                EmoticonEntity(7, "ヾ(⌒(_๑˘ㅂ˘๑)_", false),
                EmoticonEntity(7, "(੭ ᐕ)੭*⁾⁾", false),
                EmoticonEntity(7, "(๑ò◊ó ﾉ)ﾉ", false),
                EmoticonEntity(7, "ヾ(˹ᆺ˺✿)ﾉﾞ", false),
                EmoticonEntity(7, "‘`,､(((ꏿwꏿ;)))", false),
                EmoticonEntity(7, "(●°u°●)​ 」", false),
                EmoticonEntity(7, "|ʘ‿ʘ)╯", false),
                EmoticonEntity(7, "˛(ˊʙˋ)੭˒˒", false),
                EmoticonEntity(7, "ヾ(´∀｀○)ﾉ", false),
                EmoticonEntity(7, "ヾ(◜▿‾ ( ´▿｀ ) ‾▿◝)ﾉ", false),
                EmoticonEntity(7, "⌒(o＾▽＾o)ノﾟ", false),
                EmoticonEntity(7, "ヾ(°∇°*)", false),
                EmoticonEntity(7, "(*´∇｀)ﾉ", false),
                EmoticonEntity(7, "∪*ゝω･)ﾉ”", false),
                EmoticonEntity(7, "ヾ(･ω･*∪", false),
                EmoticonEntity(7, "ヾ(・ᆺ・✿)ﾉﾞ", false),
                EmoticonEntity(7, "(´っω･o)", false),
                EmoticonEntity(7, "ヽ(´▽`)ﾉ", false),
                EmoticonEntity(7, "ヽ(｡･c_，･｡)ﾉﾞ", false),
                EmoticonEntity(7, "⁽(ી₍₍⁽⁽(ી(◟̊◞̊)ʃ)₎₎⁾⁾ʃ)₎₎", false),
                EmoticonEntity(7, "(◜௰◝)╯", false),
                EmoticonEntity(7, "(ृ°͈꒳​°͈＝°͈꒳​°͈)੭ु⁾⁾*", false),
                EmoticonEntity(7, "(๑ ؔؖؕ◉͠ ◡͐ ◉ؕؔؕؖ͠)ノ", false),
                EmoticonEntity(7, "(ஐ╹◡╹)ノ", false),
                EmoticonEntity(7, "❣ヾ( ؔ✪̥ ⌔ ؔ✪̥`﹡)", false),
                EmoticonEntity(7, "o(*’▽’*)/☆ﾟ’", false),
                EmoticonEntity(7, "(｡Ő▽Ő｡)ﾉﾞ", false),
                EmoticonEntity(7, ".:*･✿ ✿.｡.:*･ヾ(Ő‿Ő✿)", false),
                EmoticonEntity(7, "ヾ(*･ω･*)o", false),
                EmoticonEntity(7, "(*´･д･)ﾉ", false),
                EmoticonEntity(7, "ヾ[･ω･`●]", false),
                EmoticonEntity(7, "(⋆ʾ ꆚ ʿ⋆)۶⁾⁾⿻", false),
                EmoticonEntity(7, "◦°˚(´•̛ᴗ•̛`)/˚°◦", false),
                EmoticonEntity(7, "ヾ(῀ ⚙⌄⚙ ῀)ﾉ”", false),
                EmoticonEntity(7, "✧*｡٩(ˊ⺫ ˋ ृ )", false),
                EmoticonEntity(7, "✲ﾟ｡.(✿╹◡╹)ﾉ☆.｡₀:*ﾟ✲ﾟ*:₀｡", false),
                EmoticonEntity(7, "|･ω･`*)ッ", false),
                EmoticonEntity(7, "(。･∀･)ﾉ゛", false),
                EmoticonEntity(7, "(ʻ͈ჲ̫ʻ͈)◞", false),
                EmoticonEntity(7, "(●>ω<)ﾉﾞ", false),
                EmoticonEntity(7, "(ゝω･)ﾉ", false),
                EmoticonEntity(7, "ヾ(=´･∀･｀=)", false),
                EmoticonEntity(7, "♪( ･ｪ･)ﾂ彡", false),
                EmoticonEntity(7, "(✿◕ ‿◕ฺ)ノ))。₀: *゜", false),
                EmoticonEntity(7, "φ(*⌒▽⌒)ﾉ", false),
                EmoticonEntity(7, "(◕ฺー≦)ノ", false),
                EmoticonEntity(7, "ヾ(*Ő౪Ő*)", false),
                EmoticonEntity(7, "ヾ(▼ﾍ▼；)", false),
                EmoticonEntity(7, "|/// |(ω･ )ﾉ| ///|", false),
                EmoticonEntity(7, "|/// |ω･｀*)ﾉ| ///|", false),
                EmoticonEntity(7, "(*ﾟ_っﾟ)ﾉﾞ", false),
                EmoticonEntity(7, "ヾ(*●´∀｀●*）", false),
                EmoticonEntity(7, "◞(⚭⃚⃙͐·̫⚭⃚⃙͐)˩✧", false),
                EmoticonEntity(7, "(ό‿ὸ)ﾉ", false),
                EmoticonEntity(7, "|。･ω･|ﾉ", false),
                EmoticonEntity(7, "└╏ ･ ᗜ ･ ╏┐", false),
                EmoticonEntity(7, "Σ(;´□｀)ﾉ", false),
                EmoticonEntity(7, "ヾ(o｀Å´o)", false),
                EmoticonEntity(7, "ヾ( o･∀)ﾉﾞ", false),
                EmoticonEntity(7, "ヾ(o･∀･o)ﾉﾞ", false),
                EmoticonEntity(7, "ヾ(∀･o )ﾉﾞ", false),
                EmoticonEntity(7, "(* ﾟ∀ﾟ)ﾉｼ", false),
                EmoticonEntity(7, "(●´Д)ﾉ”　ヾ(∀｀●)", false),
                EmoticonEntity(7, "ヾ(ﾟдﾟ)ﾉ゛", false),
                EmoticonEntity(7, "|｡･益･)ﾉ", false),
                EmoticonEntity(7, "ヽ། ﹒ ~ ﹒ །╮", false),
                EmoticonEntity(7, "ヾ(´ω｀＝´ω｀)ノ", false),
                EmoticonEntity(7, "(*・ｪ･*)ﾉ", false),
                EmoticonEntity(7, "ヾ(・∀・*)", false),
                EmoticonEntity(7, "(*・∀・)ノ゛", false),
                EmoticonEntity(7, "ヾ(>ω<○)", false),
                EmoticonEntity(7, "( ´_ゝ｀)ﾉ", false),
                EmoticonEntity(7, "（｡≧◇≦）ﾉ", false),
                EmoticonEntity(7, "(ﾉﾟ∇ﾟ)", false),
                EmoticonEntity(7, "o(*ﾟ∇ﾟ)ﾉ", false),
                EmoticonEntity(7, "(●＞д＜)ノ", false),
                EmoticonEntity(7, "(＾◇＾）ノ", false),
                EmoticonEntity(7, "（*・Ｕ・）ノ☆", false),
                EmoticonEntity(7, "o(*･ｰ･)〇", false),
                EmoticonEntity(7, "ヾ(*>v<)", false),
                EmoticonEntity(7, "(>v<*)ｼ", false),
                EmoticonEntity(7, "[○´・ω・]ﾉ", false),
                EmoticonEntity(7, "ﾍ(￣ー￣)ﾉ", false),
                EmoticonEntity(7, "☆⌒c(´∀｀)ノ", false),
                EmoticonEntity(7, "ﾟ.+:｡(≧∇≦)ﾉﾟ.+:｡", false),
                EmoticonEntity(7, "(｡･o･｡)ﾉ", false),
                EmoticonEntity(7, "(o゜◇゜)ノ", false),
                EmoticonEntity(7, "（｀∀´）ノ", false),
                EmoticonEntity(7, "ヾﾉ≧∀≦)o", false),
                EmoticonEntity(7, "( *՞ਊ՞*)ﾉ", false),
                EmoticonEntity(7, "ｰ<(´∀｀)/", false),
                EmoticonEntity(7, "ヾ｜*￣ー￣｜*￣∇￣｜/”", false),
                EmoticonEntity(7, "ヾ(・◇・)ﾉ", false),
                EmoticonEntity(7, "ヾ(･ω･ )", false),
                EmoticonEntity(7, "(*´∀｀*)ﾉ｡+ﾟ *｡", false),
                EmoticonEntity(7, "ヾ(*´Д｀*)", false),
                EmoticonEntity(7, "ヽ(*´ω｀*))", false),
                EmoticonEntity(7, "((*´ω｀*)ﾉ", false),
                EmoticonEntity(7, "☆ヾ(･ェ･｡｀Ｕ", false),
                EmoticonEntity(7, "：*：°・☆ヾ(δ_δ。)", false),
                EmoticonEntity(7, "(●´∀｀)ノ~", false),
                EmoticonEntity(7, "(*ゝω・)ﾉ", false),
                EmoticonEntity(7, "￥( ´ω`)/", false),
                EmoticonEntity(7, "(ヾ(´・ω・｀)", false),
                EmoticonEntity(7, "(*σωσ）シ", false),
                EmoticonEntity(7, "(∩｡･ｏ･｡)っ.ﾟ☆｡’`", false),
                EmoticonEntity(7, "(*´∇｀)ノ", false),
                EmoticonEntity(7, "ｰ(☆∀☆)/”", false),
                EmoticonEntity(7, "ヾ(*･∀･*）/☆ﾟ。･＋", false),
                EmoticonEntity(7, "(●ゝ∀･)ﾉ", false),
                EmoticonEntity(7, "(〃･ω･)ﾉ~☆･ﾟ+｡*ﾟ･.+", false),
                EmoticonEntity(7, "(ж^□^ж)ﾉ", false),
                EmoticonEntity(7, "(￣ｰ￣)ﾉ", false),
                EmoticonEntity(7, "o｜◕ˇ▽ˇ◕｜ツ", false),
                EmoticonEntity(7, "╰(❛∀❛ )", false),
                EmoticonEntity(7, "╰|･ิД･ิ |", false),
                EmoticonEntity(7, "o｜๑⊙Д⊙๑｜ツ", false),
                EmoticonEntity(7, "o｜#╹ー╹｜ツ", false),
                EmoticonEntity(7, "ヾ(・m・*)ノ゛", false),
                EmoticonEntity(7, "╰( ^o^)╮", false),
                EmoticonEntity(7, "(ஐ০౪০)ﾉ", false),
                EmoticonEntity(7, "໒(◕ヮ◕)〜⊹", false),
                //WRITING
                EmoticonEntity(8, "＿φ( °-°)/", false),
                EmoticonEntity(8, "＿φ(°-°=)", false),
                EmoticonEntity(8, "φ(．．;)", false),
                EmoticonEntity(8, "φ(^∇^ )", false),
                EmoticonEntity(8, "φ(◎◎ヘ)", false),
                EmoticonEntity(8, "ψ(。。)", false),
                EmoticonEntity(8, "___ψ(‥ )", false),
                EmoticonEntity(8, "＿φ(￣ー￣ )", false),
                EmoticonEntity(8, "＿φ(□□ヘ)", false),
                EmoticonEntity(8, "＿〆(。。)", false),
                EmoticonEntity(8, "(‘•̀ ▽ •́ )φ", false),
                EmoticonEntity(8, "φ(・ω・｀ )", false),
                EmoticonEntity(8, "φ(._.)", false),
                EmoticonEntity(8, "φ（．．）", false),
                EmoticonEntity(8, "φ(￣ー￣ )ノ", false),
                EmoticonEntity(8, "φ(°ρ°*)メ", false),
                EmoticonEntity(8, "〆(・∀・＠)", false),
                EmoticonEntity(8, "〆(´Ｕ_｀*)", false),
                EmoticonEntity(8, "φ(^ω^*)ﾉ", false),
                EmoticonEntity(8, "…φ(o´ωﾟo)φ…", false),
                EmoticonEntity(8, "σ(ൈ)φ", false),
                EmoticonEntity(8, "໒(⊙ᴗ⊙)७✎▤", false),
                EmoticonEntity(8, "[≡] 〆(・⺫・‶)", false),
                EmoticonEntity(8, "(๑╹o╹)φ", false),
                EmoticonEntity(8, "†=”Ⴛ̸ ♡(˃͈ દ ˂͈ ༶ )", false),
                EmoticonEntity(8, "ණ⃛(ᵒ͈̑ᴗ̂ᵒ͈̑ )”", false),
                EmoticonEntity(8, "_〆(´Д⊂", false),
                EmoticonEntity(8, "＿〆(●-Дゞ●)", false),
                EmoticonEntity(8, "φ|o-Дゞo|", false),
                EmoticonEntity(8, "௸˓˓✍(ீଞீ๑)", false),
                EmoticonEntity(8, "＿ø(●ʘ╻ʘ●)", false),
                EmoticonEntity(8, "〆(´ω`●)ゞ", false),
                EmoticonEntity(8, "((φ(．．｡)", false),
                EmoticonEntity(8, "βακα…_〆(´･ω･｀*)", false),
                EmoticonEntity(8, "βακα…_φ(ﾟωﾟ )", false),
                EmoticonEntity(8, "✍(΄◞ิ౪◟ิ‵)", false),
                EmoticonEntity(8, "✉✍(ග⍛ග੭", false),
                EmoticonEntity(8, "“φʕ•ᴥ•oʔ", false),
                EmoticonEntity(8, "φ(￣￢￣ヾ)", false),
                EmoticonEntity(8, "φ(●ﾟ益ﾟ)っ", false),
                EmoticonEntity(8, "＿〆ヾ(￣(エ)￣)", false),
                EmoticonEntity(8, "￠(･ω･`)", false),
                EmoticonEntity(8, "_￠(T-T*)", false),
                EmoticonEntity(8, "φ(´ω｀●)", false),
                EmoticonEntity(8, "φ(ﾟ ωﾟ//）♡", false),
                EmoticonEntity(8, "_φ(●ﾟ益ﾟ)っ", false),
                EmoticonEntity(8, "φ(´д｀ｏ)", false),
                EmoticonEntity(8, "_〆(･_･｡)", false),
                EmoticonEntity(8, "_￠(･ω･`)", false),
                EmoticonEntity(8, "_〆((ﾐ￣ｴ￣ﾐ))", false),
                EmoticonEntity(8, "≡≡≡≡φ(＾∇＾*)", false),
                EmoticonEntity(8, "_〆(ﾟ▽ﾟ*)", false),
                EmoticonEntity(8, "❣ฺ✍ฺ（◕ฺｖ◕ฺ）✌ฺ", false),
                EmoticonEntity(8, "φ(･c_,･｡)", false),
                EmoticonEntity(8, "βακα…_〆(ﾟ▽ﾟ*)", false),
                EmoticonEntity(8, "_〆(･･　)♪", false),
                EmoticonEntity(8, "＿〆((=´ｴ `= ) )", false),
                EmoticonEntity(8, "φ(ﾟｪﾟ♡)", false),
                EmoticonEntity(8, "…_〆(ﾟ▽ﾟ*)", false),
                EmoticonEntity(8, "βακα…_〆(・ｪ・*)", false),
                EmoticonEntity(8, "βακα…_〆(´･ｪ･｀*)", false),
                EmoticonEntity(8, "βακα…_φ(´ι _` 　)", false),
                EmoticonEntity(8, "βακα?…_φ(￣ ￣|||)", false),
                EmoticonEntity(8, "βακαУαЯο…_〆(ﾟ▽ﾟ*)", false),
                EmoticonEntity(8, "ВАКА❣ฺ✍ฺ（◕ฺｖ◕ฺ）✌ฺ", false),
                EmoticonEntity(8, "…_〆(・∀・＠)", false),
                EmoticonEntity(8, "…〆（´Ｕ｀*）", false),
                EmoticonEntity(8, "…..φ(・∀・＊)", false),
                EmoticonEntity(8, "_φ［・ω・｀*］", false),
                EmoticonEntity(8, "….〆(･ω･。)", false),
                EmoticonEntity(8, "_〆┤’-‘*├", false),
                EmoticonEntity(8, "＼＿ﾍ(ω｀*)", false),
                EmoticonEntity(8, "φ(-｀Д´-*)", false),
                EmoticonEntity(8, "￠(-∀・○)", false),
                EmoticonEntity(8, "＼_(･ω･｀)", false),
                EmoticonEntity(8, "＼＿ﾍ(ﾟeﾟ#)", false),
                EmoticonEntity(8, "￠(-∀-○)", false),
                EmoticonEntity(8, "_￠(･ω･｀)", false),
                EmoticonEntity(8, "＿〆(´∀｀●)", false),
                EmoticonEntity(8, "＿〆(=´ｴ ｀= )", false),
                EmoticonEntity(8, "_〆(-c_,-。)", false),
                EmoticonEntity(8, "＿〆(-ε･｀)ﾉ^☆", false),
                EmoticonEntity(8, "＼_(ω・｀*)ゞ", false),
                EmoticonEntity(8, "…..φ(〃∇〃 ）", false),
                EmoticonEntity(8, "…..φ(-ω-｡`)", false),
                EmoticonEntity(8, "…..φ(〃∇〃 )))", false),
                EmoticonEntity(8, "…〆(・Å・｀ｏ)ノ", false),
                EmoticonEntity(8, "[＼／]…..φ(・д・。)", false),
                EmoticonEntity(8, "＼＿ﾍ(´ω｀)", false),
                EmoticonEntity(8, "вакатΙη…￠(-∀・○)", false),
                EmoticonEntity(8, "ＳΟЯЯΥ＿φ（･益ｑ｡｀)･ﾟ･ｏ｡", false),
                EmoticonEntity(8, "Ｉ ￡ονё Υου…..φ┃*･ω･*┃", false),
                EmoticonEntity(8, "＼＿ﾍ(◕‿◕✰)", false),
                EmoticonEntity(8, "_〆(ﾟ□ﾟ*)", false),
                EmoticonEntity(8, "〆(･ω･*)", false),
                EmoticonEntity(8, "φ(´ω｀= )", false),
                EmoticonEntity(8, "φ( =´∀｀)ﾉ", false),
                EmoticonEntity(8, "_〆(´Ｕ_｀*)", false),
                EmoticonEntity(8, "ηακετα…_〆(；ωq｀)", false),
                EmoticonEntity(8, "βακα…_〆(・ｪ・*)", false),
                EmoticonEntity(8, "βακα…_〆(´･ｪ･｀*)", false),
                EmoticonEntity(8, "βακα…_φ(´ι _` 　)", false),
                EmoticonEntity(8, "βακα?…_φ(￣ ￣|||)", false),
                EmoticonEntity(8, "..φ(ｰ￣*)", false),
                EmoticonEntity(8, "_φ(*￣0￣)ﾉ", false),
                EmoticonEntity(8, "…φ(ω￣*)", false),
                EmoticonEntity(8, "_φ(*￣ω￣)ﾉ", false),
                EmoticonEntity(8, "〆(°°*)", false),
                EmoticonEntity(8, "【ъака】＼_(・ω・`)", false),
                EmoticonEntity(8, "βακα…_〆(゜▽゜*)", false),
                EmoticonEntity(8, "βακα…_φ(ﾟ∀ﾟ )", false),
                EmoticonEntity(8, "￡ονё Υου…..φ(〃∇〃 ))", false),
                EmoticonEntity(8, "╰(⊡-⊡)و✎⮹", false),
                //WTF?
                EmoticonEntity(9, "(๑ ऀืົཽ₍₍ළ₎₎ ऀืົཽ)✧", false),
                EmoticonEntity(9, "༎ຶ‿༎ຶ", false),
                EmoticonEntity(9, ";´༎ຶਊ ༎ຶ`;", false),
                EmoticonEntity(9, "( ༎ຶŎ༎ຶ )", false),
                EmoticonEntity(9, "( ཀ͝ ∧ ཀ͝ )", false),
                EmoticonEntity(9, "(;´༎ຶД༎ຶ`)", false),
                EmoticonEntity(9, "(;´༎ຶٹ༎ຶ`)", false),
                EmoticonEntity(9, "(;´༎ຶ益༎ຶ`)♡", false),
                EmoticonEntity(9, "(( ༎ຶ‿༎ຶ ))", false),
                EmoticonEntity(9, "⁽⁽(ཀ д ཀ)⁾⁾", false),
                EmoticonEntity(9, "(༎ຶꈊ༎ຶ╬)", false),
                EmoticonEntity(9, "(´༎ຶ༎ຶ)", false),
                EmoticonEntity(9, "(≼⓪≽◟⋌⋚⋛⋋◞≼⓪≽)", false),
                EmoticonEntity(9, "(◞≼۩۞۩≽◟◞౪◟◞≼۩۞۩≽◟)", false),
                EmoticonEntity(9, "(◞≼◎≽◟◞౪◟◞≼◎≽◟)", false),
                EmoticonEntity(9, "(◞≼●≽◟◞౪◟◞≼●≽◟)", false),
                EmoticonEntity(9, "(◞≼☉≽◟◞౪◟◞≼☉≽◟)", false),
                EmoticonEntity(9, "(◞≼థ≽◟◞౪◟◞≼థ≽◟)", false),
                EmoticonEntity(9, "（☝ ՞ਊ ՞）☝", false),
                EmoticonEntity(9, "(☝΄◞ิ۝◟ิ‵)☝", false),
                EmoticonEntity(9, "༼;´༎ຶ ۝ ༎ຶ༽", false),
                EmoticonEntity(9, "*:･✧⃛(ཽ๑ඕัළඕั๑)✧⃛*:･", false),
                EmoticonEntity(9, "⁄⁄ ⁄ ⁄⁄⁄ ⁄⁄( ꈨຶꎁꈨຶ)⁄⁄ ⁄ ⁄⁄⁄ ⁄⁄ ", false),
                EmoticonEntity(9, "☜(:༎ຶ;益;༎ຶ;)☞", false),
                EmoticonEntity(9, "ヾ(;;;;;;;;;;;;´༎ຶ ۝ ༎ຶ)ﾉ", false),
                EmoticonEntity(9, "୧꒰๑͒•͈ꇵ͒•͈๑͒꒱୨ᵎᵎ✧", false),
                EmoticonEntity(9, "v(;´༎ຶД༎ຶ`)v", false),
                EmoticonEntity(9, "(‿ˠ‿)", false),
                EmoticonEntity(9, "(‿ꜟ‿)", false),
                EmoticonEntity(9, "˓˓(‿◟̩ ͜ )˒˒", false),
                EmoticonEntity(9, "╰U╯☜(◉ɷ◉ )", false),
                EmoticonEntity(9, "( ◜◡＾)っ✂╰⋃╯", false),
                EmoticonEntity(9, "ღ╰⋃╯ღ•̥̑ .̮ •̥̑)", false),
                EmoticonEntity(9, "╰⋃╯ლ(´ڡ`ლ)", false),
                EmoticonEntity(9, "(₍ˀ˟͈͈͈᷄ළ˟͈͈͈᷅ˁ₎)", false),
                EmoticonEntity(9, "(༎ຶ⌑༎ຶ)", false),
                EmoticonEntity(9, "(;´༎ຶ益༎ຶ`)♡", false),
                EmoticonEntity(9, "(ּơ̑ළּơ̑)", false),
                EmoticonEntity(9, "(´◔౪◔)✂╰⋃╯", false),
                EmoticonEntity(9, "(•ؔ༎ຶළॆؔ༎ຶ)", false),
                EmoticonEntity(9, "⁽₍੭ ՞̑◞ළ̫̉◟՞̑₎⁾੭", false),
                EmoticonEntity(9, "(༎ຶ ෴ ༎ຶ)", false),
                EmoticonEntity(9, "( ´༎ຶㅂ༎ຶ`)", false),
                EmoticonEntity(9, "(;´༎ຶ༎ຶ`)", false),
                EmoticonEntity(9, "(༎ຶ ༎ຶ 三 ༎ຶ ༎ຶ)", false),
                EmoticonEntity(9, "╰⋃╯(ԾДԾ)७", false),
                EmoticonEntity(9, "⊍⊍ ლ(◉◡◉ლ)", false),
                EmoticonEntity(9, "(◉۝◉)╰U╯", false),
                EmoticonEntity(9, "  ( ⌒⃘ཽ⃜ ◞ළ̆◟ ⌒⃘ཽ⃜ )", false),
                EmoticonEntity(9, "( ◜◡＾)っ╰⋃╯", false),
                EmoticonEntity(9, "  (´༎ຶ۝༎ຶ)", false),
                EmoticonEntity(9, "༼;´༎ຶ ༎ຶ༽", false),
                EmoticonEntity(
                    9,
                    " o͡͡͡͡͡͡͡͡͡͡͡͡͡͡╮༼;´༎ຶ.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨۝ ༎ຶ༽╭o͡͡͡͡͡͡͡͡͡͡͡͡͡͡",
                    false
                ),
                EmoticonEntity(9, "↻( ꑡ᷉ˋ͈۝ˊ͈)ꑡ᷉༄", false),
                EmoticonEntity(9, "་ཀ༼ༀ༽ཫ་῍̩̖̬ ̎ ̎✧", false),
                EmoticonEntity(9, "  ヾ(;;;;;;;;;;;;´༎ຶ ۝ ༎ຶ/)", false),
                EmoticonEntity(9, "(๑ؔ༎̐৫῎ؔ༎̐)⁝", false),
                EmoticonEntity(9, "╭∩╮(︶ε︶*)chu", false),
                EmoticonEntity(9, "(ཫ͝⁔ੂཀ͝)", false),
                EmoticonEntity(9, "(ཫ͝﹏ੂཀ͝)", false),
                EmoticonEntity(9, "㠭(:༑༎ຶ䍏༎ຶ༑:)㠭", false),
                EmoticonEntity(9, "( ๑´•ω•)۶”╰⋃╯ (ㆆᴗㆆ)", false),
                EmoticonEntity(9, "━꒰ ⁎꒦ິཽ ۝꒦ິཽॢ꒱━", false),
                EmoticonEntity(
                    9,
                    ".̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨ↂ⃝⃓⃙⃚⃘۝ↂ⃝⃓⃙⃚⃘.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨",
                    false
                ),
                EmoticonEntity(9, "(༎ຶ ۝ ༎ຶ 三 ༎ຶ ۝ ༎ຶ)", false),
                EmoticonEntity(9, "༼ つ ✿◕‿◕✿༽つ╰⋃╯", false),
                EmoticonEntity(9, "  (~° ͜ʖ͡°)~ ( . ( . )", false),
                EmoticonEntity(9, "(✿ ◕‿◕) ᓄ✂╰⋃╯", false),
                EmoticonEntity(9, "( ＾◡＾)っ (‿|‿)", false),
                EmoticonEntity(9, "( ◜◡＾)っ✂ღ╰⋃╯ღ•̥̑ .̮ •̥̑)", false),
                EmoticonEntity(9, "╰⋃╯ლ(´ڡ`ლ)？", false),
                EmoticonEntity(9, "૮(༎໊ඏ༎໊)ა", false),
                EmoticonEntity(
                    9,
                    ".̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨ↂ⃝⃓⃙⃚⃘۝ↂ⃝⃓⃙⃚⃘.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨",
                    false
                ),
                EmoticonEntity(9, "Ⴤ༼༎ত:౧:ত༎༽Ⴤ", false),
                EmoticonEntity(9, "ſ░▓░▃░▓░ƪ. ◖ƪ❍⊁◞..◟⊀❍|◗", false),
                EmoticonEntity(9, "  ༼ つ ✿◕‿◕✿༽つ (‿ˠ‿)", false),
                EmoticonEntity(9, "(Ɔ˘⌣˘)(˘⌣˘)˘⌣˘ C) ᑦ∪ᔿ ᵒᐢ ᔿᵉᵎᵎ", false),
                EmoticonEntity(
                    9, "( ° ͜ʖ͡°)╭∩╮", false
                ),
                EmoticonEntity(9, "✂╭∩╮(°□° )", false),
                EmoticonEntity(9, "( ͝° ͜ʖ͡°)つ✂╰⋃╯", false),
                EmoticonEntity(9, "(▀̿̿Ĺ̯̿̿▀̿ ̿) ✂╰⋃╯", false),
                EmoticonEntity(9, "ヽ༼✿ʘ̚ل͜ʘ̚༽ﾉ╰⋃╯", false),
                EmoticonEntity(9, "(◔‸◔ )っ✄╰⋃╯", false),
                EmoticonEntity(9, "•ू(༎ຶ۝༎ຶ`•ू) )੭ु⁾⁾", false),
                //WINK
                EmoticonEntity(10, "(･ｪ-)", false),
                EmoticonEntity(10, "(－ｏ⌒)", false),
                EmoticonEntity(10, "(。^_・)ノ", false),
                EmoticonEntity(10, "（＾＿－）", false),
                EmoticonEntity(10, "(^_-)", false),
                EmoticonEntity(10, "（＾_-）", false),
                EmoticonEntity(10, "（＾＿－）≡★", false),
                EmoticonEntity(10, "（＾＿・）", false),
                EmoticonEntity(10, "（＾＿−）", false),
                EmoticonEntity(10, "(^_−)☆", false),
                EmoticonEntity(10, "(⌒.−)＝★", false),
                EmoticonEntity(10, "（○゜ε＾○）", false),
                EmoticonEntity(10, "(o‿∩)", false),
                EmoticonEntity(10, "＼（^０＾）／", false),
                EmoticonEntity(10, "๏[-ิ_•ิ]๏", false),
                EmoticonEntity(10, "~(＾◇^)/", false),
                EmoticonEntity(10, "☆～（ゝ。∂）", false),
                EmoticonEntity(10, "d(-_^)", false),
                EmoticonEntity(10, "✩⃛˞(๑ꆨ৺ꉺ๑)", false),
                EmoticonEntity(10, "(๑ꄱͦॢ◡ु ˂̶͈́๑)", false),
                EmoticonEntity(10, "｡ﾟ+.ღ(ゝ◡ ⚈᷀᷁ღ)", false),
                EmoticonEntity(10, "˄̻ ̊σ(˃̴͈◡ुමੈॆ⋆)˄̻ ̊~♡⃛", false),
                EmoticonEntity(10, "ෆ⃛(ᶿ̴͈᷇◟̵◞̵˂͈᷆ ფ", false),
                EmoticonEntity(10, "⌓⌓⌕(˃̴◡ुؔ՞ઁ)♡⃛", false),
                EmoticonEntity(10, "(˃̶᷄︿๏）", false),
                EmoticonEntity(10, "(∗ᵒ̶̶̷̀ω˂̶́∗)੭₎₎̊₊♡", false),
                EmoticonEntity(10, "(*⸰‿-) (☉_☉) (-‿◦☀)", false),
                EmoticonEntity(10, "♪(ﾟ▽^*)ﾉ⌒☆", false),
                EmoticonEntity(10, "ヾ(*ゝω・*)ﾉ", false),
                EmoticonEntity(10, "ｄ(ゝc_,・●)", false),
                EmoticonEntity(10, "v(*’-^*)ｂ", false),
                EmoticonEntity(10, "v(°∇^*)⌒☆", false),
                EmoticonEntity(10, "σ(ﾟｰ^*)", false),
                EmoticonEntity(10, "۴(๑ꆨ◡ꉺ๑)", false),
                EmoticonEntity(10, "d(*ゝωб*)", false),
                EmoticonEntity(10, "(ﾟ∇^*)", false),
                EmoticonEntity(10, "৲( ᵒ ૩ᵕ )৴♡*৹", false),
                EmoticonEntity(10, "(๑ゝᴗම๑) ৷ਕკ~ෆ", false),
                EmoticonEntity(10, "(｡•̀ᴗ-)✧", false),
                EmoticonEntity(10, "( ᐤ◞◡ु̑◟˂ )⁺ₒ✩", false),
                EmoticonEntity(10, "ヽ(。ゝω･)ﾉ☆;:*", false),
                EmoticonEntity(10, "（◍●◡ु‹◍)☆", false),
                EmoticonEntity(10, "(๑◕ㅂ▰)", false),
                EmoticonEntity(10, "ʸ(➜◡ु⚈᷉)♡⃛", false),
                EmoticonEntity(10, "⁽͑ʺ˚˙̫ʿʺ⁾̉ˀ*", false),
                EmoticonEntity(10, "(ゝω･)ﾉ", false),
                EmoticonEntity(10, "ಠ‿↼", false),
                EmoticonEntity(10, "( ͡~ ͜ʖ ͡°)", false),
                EmoticonEntity(10, "（ゝ。∂）", false),
                EmoticonEntity(10, "☆⌒(*＾-°)v", false),
                EmoticonEntity(10, "(´ゝз・`)ﾉ⌒☆", false),
                EmoticonEntity(10, "v(*’-^*)-☆", false),
                EmoticonEntity(10, "(*^-°)v", false),
                EmoticonEntity(10, "Y（・ω‐）Y", false),
                EmoticonEntity(10, "(^_-)—☆", false),
                EmoticonEntity(10, "(◕ฺー≦)ノ", false),
                EmoticonEntity(10, "(*・∀-)☆", false),
                EmoticonEntity(10, "★~(◠︿◕✿)", false),
                EmoticonEntity(10, "★~(◠﹏◕✿)", false),
                EmoticonEntity(10, "★~(◡﹏◕✿)", false),
                EmoticonEntity(10, "★~(◠ω◕✿)", false),
                EmoticonEntity(10, "★~(◡‿⊙✿)", false),
                EmoticonEntity(10, "★~(◡△⊙✿)", false),
                EmoticonEntity(10, "★~(◠﹏⊙✿)", false),
                EmoticonEntity(10, "★~(◡﹏⊙✿)", false),
                EmoticonEntity(10, "★~(◠‿◕✿)", false),
                EmoticonEntity(10, "★~(◡ω◕✿)", false),
                EmoticonEntity(10, "★~(◠△◕✿)", false),
                EmoticonEntity(10, "★~(◠△⊙✿)", false),
                EmoticonEntity(10, "★~(◠ω⊙✿)", false),
                EmoticonEntity(10, "★~(◡﹏◡✿)", false),
                EmoticonEntity(10, "★~(◡︿⊙✿)", false),
                EmoticonEntity(10, "★~(◠︿⊙✿)", false),
                EmoticonEntity(10, "★~(◡ω◡✿)", false),
                EmoticonEntity(10, "★~(◡ω⊙✿)", false),
                EmoticonEntity(10, "(´ ◕◞౪◟-)-☆", false),
                EmoticonEntity(10, "(´ゝз・)─☆", false),
                EmoticonEntity(10, "(๑ゝڡ◕๑)", false),
                EmoticonEntity(10, "ヽ(。ゝω・)ノ☆", false),
                EmoticonEntity(10, "d(｡ゝд･)", false),
                EmoticonEntity(10, "☆（*ゝω・*）ﾉ", false),
                EmoticonEntity(10, "(v^ー°)", false),
                EmoticonEntity(10, "ヾ(*ゝω・*)ノ", false),
                EmoticonEntity(10, "☆｡ﾟ+.(人-ω◕ฺ)ﾟ+.ﾟ", false),
                EmoticonEntity(10, "o（｀ゝ曲°〃）b⌒☆", false),
                EmoticonEntity(10, "(ﾉ･_-)☆", false),
                EmoticonEntity(10, "☆*．･(*ゝ∀・*)ﾉ", false),
                EmoticonEntity(10, "☆⌒（●ゝω・）", false),
                EmoticonEntity(10, "☆(>ω・)", false),
                EmoticonEntity(10, "(ゝ∀･)", false),
                EmoticonEntity(10, "★⌒(●ゝω・)ｂ", false),
                EmoticonEntity(10, "(*ゝω・)ﾉ", false),
                EmoticonEntity(10, "d(ゝ∀･)", false),
                EmoticonEntity(10, "(●ゝ∀･)ﾉ", false),
                EmoticonEntity(10, "(ゝω´･)b⌒☆", false),
                EmoticonEntity(10, "く(^ｰﾟ)ﾉ", false),
                EmoticonEntity(10, "★>d(,,･ε´-,,)⌒☆", false),
                EmoticonEntity(10, "(。・艸-。)-☆　ｗiйκ", false),
                EmoticonEntity(10, "(･ω<)☆", false),
                EmoticonEntity(10, "(・ω<)", false),
                EmoticonEntity(10, "ｖ(･Д<*)☆", false),
                EmoticonEntity(10, "☆=(ゝω･)", false),
                EmoticonEntity(10, "ヾ(о-ω･)ﾉ⌒★", false),
                EmoticonEntity(10, "(＞ω)＝☆", false),
                EmoticonEntity(10, "(*＾∀ﾟ)ъ", false),
                EmoticonEntity(10, "(*ﾟｰ~)^☆", false),
                EmoticonEntity(10, "（　＾▽-）∠※☆", false),
                EmoticonEntity(10, "(○ゝω・○)ﾉﾟ+.☆", false),
                EmoticonEntity(10, "ヽ(｡ゝ∀･)☆･ﾟ:*☆", false),
                //SALUTING
                EmoticonEntity(11, "(・∧‐)ゞ", false),
                EmoticonEntity(11, "(-ω-ゞ", false),
                EmoticonEntity(11, "(；・ε・)ゝ”", false),
                EmoticonEntity(11, "(；´・∀・)ゝ”", false),
                EmoticonEntity(11, "(；°ρ°)ゝ”", false),
                EmoticonEntity(11, "(；●∀●)ゝ”", false),
                EmoticonEntity(11, "(‘∀`)ゝ”", false),
                EmoticonEntity(11, "(*´ﾟωﾟﾉ", false),
                EmoticonEntity(11, "(〃´・ω・`)ゝ", false),
                EmoticonEntity(11, "(〃⌒▽⌒〃)ゝ", false),
                EmoticonEntity(11, "(｀∀´)ゝ”", false),
                EmoticonEntity(11, "(`Д´)ゞ", false),
                EmoticonEntity(11, "(°∀°)ゝ”", false),
                EmoticonEntity(11, "(＞Д＜)ゝ", false),
                EmoticonEntity(11, "(≧∀≦ゞ", false),
                EmoticonEntity(11, "(≧ω≦)ゞ", false),
                EmoticonEntity(11, "(○$´∀`)ゞ", false),
                EmoticonEntity(11, "(◎｀・ω・´)ゞ", false),
                EmoticonEntity(11, "(★｀･ω･)ゞ", false),
                EmoticonEntity(11, "(★´ω｀★)ゞ", false),
                EmoticonEntity(11, "(★ゝз･)ﾉ~*", false),
                EmoticonEntity(11, "*~ヽ(ゝз･☆)", false),
                EmoticonEntity(11, "(ο´ω｀ο)ゝ", false),
                EmoticonEntity(11, "(`Д´)ゞ", false),
                EmoticonEntity(11, "(｀･ω･´)ゞ", false),
                EmoticonEntity(11, "(′σω`)ﾉ", false),
                EmoticonEntity(11, "(*゜－＾)ゞ", false),
                EmoticonEntity(11, "(*゜ω゜)ゞ", false),
                EmoticonEntity(11, "☆(･ω･*)ゞ", false),
                EmoticonEntity(11, "ヾ|*ﾟωﾟ|ゞ", false),
                EmoticonEntity(11, "(`･ε´-ゞ)", false),
                EmoticonEntity(11, "(`･ω･´)ゞ", false),
                EmoticonEntity(11, "(￣^￣)ゞ", false),
                EmoticonEntity(11, "(^-^)ゝ", false),
                EmoticonEntity(11, "(゜◇゜)ゞ", false),
                EmoticonEntity(11, "(｡･ω･)ゞ", false),
                EmoticonEntity(11, "(‘-‘*ゞ", false),
                EmoticonEntity(11, "∠(｀･ω･´)", false),
                EmoticonEntity(11, "∠(･`_´･ )", false),
                EmoticonEntity(11, "く（＠Д＠）", false),
                EmoticonEntity(11, "( ゜ω゜)ゝ", false),
                EmoticonEntity(11, "( ・∀・ )ゞ", false),
                EmoticonEntity(11, "（｀・ω・）ゞ", false),
                EmoticonEntity(11, "(｀・д・´)ゝ", false),
                EmoticonEntity(11, "(｀д´)ゝ", false),
                EmoticonEntity(11, "(-ω-)ゝ", false),
                EmoticonEntity(11, "（・д・ゝ）", false),
                EmoticonEntity(11, "(‘ー’*)ゞ", false),
                EmoticonEntity(11, "/(‘∀’*", false),
                EmoticonEntity(11, "∠(^ー^)", false),
                EmoticonEntity(11, "(*>▽<*)ゞ", false),
                EmoticonEntity(11, "(｡ゝ∀･)ゞ", false),
                EmoticonEntity(11, "┏( ﾟ益ﾟ)ゞ", false),
                EmoticonEntity(11, "(｀ﾟДﾟ´)ゞ", false),
                EmoticonEntity(11, "( *๑•̀д•́๑)」", false),
                EmoticonEntity(11, "(「꒪౪꒪)」", false),
                EmoticonEntity(11, "(`-д-；)ゞ", false),
                EmoticonEntity(11, "ｏ(〃･◇･〃)ゞ", false),
                EmoticonEntity(11, "(･`◡´･)ゝ", false),
                EmoticonEntity(11, "ヽ|･ω･|ゞ", false),
                EmoticonEntity(11, "∠꒰’౪’꒱✧", false),
                EmoticonEntity(11, "◞(⚭⃚⃙͐·̫⚭⃚⃙͐)˩✧", false),
                EmoticonEntity(11, "┏( ﾟωﾟ)ゝ", false),
                EmoticonEntity(11, "(‾-ƪ‾)", false),
                EmoticonEntity(11, "(〃´3′〃)ゞ", false),
                EmoticonEntity(11, "ｏ(･д´･+)ゞ", false),
                EmoticonEntity(11, "|･｀ヘ´･;|ゞ", false),
                EmoticonEntity(11, "(*^-^*)ゞ", false),
                EmoticonEntity(11, "〆(´ω`●)ゞ", false),
                EmoticonEntity(11, "☆( ´ ਊ ՞ )ゞ", false),
                EmoticonEntity(11, "(〓￣(∵エ∵)￣〓)ゞ", false),
                EmoticonEntity(11, "( -(ｴ)-)ゞ", false),
                EmoticonEntity(11, "(●￣(ｴ)￣●)ゞ", false),
                EmoticonEntity(11, "ヾ(´(ｴ)｀ﾉﾞ", false),
                EmoticonEntity(11, "v(▼ω▼ﾒ)ゞ", false),
                EmoticonEntity(11, "（〃・ロ・〃）ゞ", false),
                EmoticonEntity(11, "(●´ω｀●)ゞ", false),
                EmoticonEntity(11, "(*´･x･`)ゞ", false),
                EmoticonEntity(11, "|；´・ω･｀|ゞ", false),
                EmoticonEntity(11, "( ´_ゝ｀)ゞ", false),
                EmoticonEntity(11, "(*´□`)ゞ", false),
                EmoticonEntity(11, "(*｀･益･´)ゞ", false),
                EmoticonEntity(11, "(｡･益･)ゞ", false),
                EmoticonEntity(11, "( ’v`*)ゞ", false),
                EmoticonEntity(11, "(=´▽｀)ゞ", false),
                EmoticonEntity(11, "(=`ｪ´=；)ゞ", false),
                EmoticonEntity(11, "(*°∀°)ゞ", false),
                EmoticonEntity(11, "(。・ω・)ゞ", false),
                EmoticonEntity(11, "ヽ( ˘ω˘ )ゝ", false),
                EmoticonEntity(11, "∠(´д｀)", false),
                EmoticonEntity(11, "（＊´ω｀）ゞ", false),
                EmoticonEntity(11, "(●>д<●)ゞ", false),
                EmoticonEntity(11, "（・∀・）ゞ", false),
                EmoticonEntity(11, "ヾ(☆´･ω･)ゞ", false),
                EmoticonEntity(11, "ヾ(･ω･｀★)ゞ", false),
                EmoticonEntity(11, "(*｀∪´*)ゞ", false),
                EmoticonEntity(11, "v(*’-^*)ゞ・’ﾟ☆", false),
                EmoticonEntity(11, "(oゝ∀・o)ゞ", false),
                EmoticonEntity(11, "ヾ(≧∇≦)ゞ", false),
                EmoticonEntity(11, "(*´∀｀*)ゞ", false),
                EmoticonEntity(11, "＼|*≧Д≦|>", false),
                EmoticonEntity(11, "ヾ(≧ー≦)ゞ", false),
                EmoticonEntity(11, "∠( ﾟдﾟ)/", false),
                EmoticonEntity(11, "o(*￣○￣)ゝ", false),
                EmoticonEntity(11, "―(≧∀≦)ゞ", false),
                EmoticonEntity(11, "！(@＾▽＾@）ゞ", false),
                EmoticonEntity(11, "(｀･д´･ゞ)-☆", false),
                EmoticonEntity(11, "(*・∀・)ゞ", false),
                EmoticonEntity(11, "（’◇’）ゞ", false),
                EmoticonEntity(11, "(*ﾟｰﾟ)ゞ⌒☆", false),
                EmoticonEntity(11, "(＞Д＜)ゝ”", false),
                EmoticonEntity(11, "（＾∀＾）ゞ", false),
                EmoticonEntity(11, "(･ω´-ゞ)^☆", false),
                EmoticonEntity(11, "（≧▽≦）ゝ", false),
                EmoticonEntity(11, "（´ω｀◎）ゞ", false),
                EmoticonEntity(11, "（*＾～＾*）ゝ", false),
                EmoticonEntity(11, "ｏ(〃・◇・〃)ゞ", false),
                EmoticonEntity(11, "( ﾟДﾟ)ゞ", false),
                EmoticonEntity(11, "ヽ(￣ω￣(￣ω￣〃)ゝ", false),
                EmoticonEntity(11, "☆(*･ｪ･*)＞｡", false),
                EmoticonEntity(11, "＼(^O^ )＞*", false),
                EmoticonEntity(11, "*＜( ^O^)／", false),
                EmoticonEntity(11, "*＜( ≧▽≦)／", false),
                EmoticonEntity(11, "＼(≧▽≦ )＞*", false),
                EmoticonEntity(11, "*＜( ・∀・)ノ", false),
                EmoticonEntity(11, "ヽ(・∀・ )＞*", false),
                EmoticonEntity(11, "v(ﾟ∇^*)＞o⌒☆", false),
                EmoticonEntity(11, "(o｀･ω･)ゞ", false),
                EmoticonEntity(11, "（｀・ゝ・´）ゞ", false),
                EmoticonEntity(11, "（*｀・ω・*）ゞ", false),
                EmoticonEntity(11, "<(￣∇￣)ゞ", false),
                EmoticonEntity(11, "（￣ー￣)ゞ", false),
                EmoticonEntity(11, "(￣▽￣)ゞ", false),
                EmoticonEntity(11, "(*>ω<)ゞ", false),
                EmoticonEntity(11, "（*￣‥￣*）ゝ", false),
                EmoticonEntity(11, "!!(･∇･｀ゞ", false),
                EmoticonEntity(11, "(〃＾∀ﾟ ゞ", false),
                EmoticonEntity(11, "(。・ｘ・)ゞ", false),
                EmoticonEntity(11, "（≧▽≦）ゞ", false),
                EmoticonEntity(11, "(´∀｀ゞ", false),
                EmoticonEntity(11, "（─∀─）ゞ", false),
                EmoticonEntity(11, "(*゜ー゜)ゞ⌒☆", false),
                EmoticonEntity(11, "(U･× ･´)ゞ", false),
                EmoticonEntity(11, "（○｀ω´）ゞ", false),
                EmoticonEntity(11, "(｀∀´*)ゞ", false),
                EmoticonEntity(11, "(‘∀`)ゞ", false),
                EmoticonEntity(11, "(●｀･ω･)ゞ＜ok！", false),
                EmoticonEntity(11, "(｀∇´ゞ", false),
                EmoticonEntity(11, "(＊･_･＊)ゞ", false),
                EmoticonEntity(11, "(*´-｀*)ゞ", false),
                EmoticonEntity(11, "ヾ(*｀∀´*)ゞ", false),
                EmoticonEntity(11, "(‘ – ‘ *)ゞ", false),
                EmoticonEntity(11, "く(^ｰﾟ)ﾉ", false),
                EmoticonEntity(11, "(〇´∪`●ゞ）", false),
                EmoticonEntity(11, "♪(´∪`●)ゝ", false),
                EmoticonEntity(11, "<|๑⊙Д⊙|/", false),
                EmoticonEntity(11, "(｡･Д･)ゞ", false),
                EmoticonEntity(11, "(*｀･ω･)ゞ", false),
                EmoticonEntity(11, "(゜∀´)ゞ=☆", false),
                EmoticonEntity(11, "（★・л・★）ゝ", false),
                EmoticonEntity(11, "ヾ(●｀･△･´●)ゞ", false),
                EmoticonEntity(11, "(∀｀*ゞ)", false),
                EmoticonEntity(11, "ヾ(´ε｀*)ゝ", false),
                EmoticonEntity(11, "(・ω・｀=)ゞ", false),
                EmoticonEntity(11, "o(- -;*)ゞ", false),
                EmoticonEntity(11, "c(＞ω＜)ゞ", false),
                EmoticonEntity(11, "(`･ω･)ゞ", false),
                EmoticonEntity(11, "([]-[]-“ゝ", false),
                EmoticonEntity(11, "(‘ー’*)ゞ", false),
                EmoticonEntity(11, "∠(*ﾟ∇ﾟ*)", false),
                EmoticonEntity(11, "(*･×･*)ゞ", false),
                EmoticonEntity(11, "(･∀･´*)ゞ", false),
                EmoticonEntity(11, "(･´з`･)ゞ", false),
                EmoticonEntity(11, "s(●｀ヘ´●;)ゞ", false),
                EmoticonEntity(11, "(´▽｀；)ゞ", false),
                EmoticonEntity(11, "(。・ω・。)ゞ", false),
                EmoticonEntity(11, "(￣∇￣*)ゞ", false),
                EmoticonEntity(11, "(´･Д･lll)ゞ", false),
                EmoticonEntity(11, "ヽ(⌒‐⌒)ゝ", false),
                EmoticonEntity(11, "(⑅･◇･)ゞ", false),
                EmoticonEntity(11, "(￣ー￣)ゞ", false)
            )
            return result
        }

    }
}