package com.nitroapps.emoticons.helpers

import com.nitroapps.emoticons.EmoticonEntity

class HelperClass3 {
    companion object {
        fun generateData(): Array<EmoticonEntity> {
            val result = arrayOf(
                //SCARED
                EmoticonEntity(12, "(/-(ｴ)-＼)", false),
                EmoticonEntity(12, "( /)u( )", false),
                EmoticonEntity(12, "（*/∇＼*）", false),
                EmoticonEntity(12, "(*/ω＼*)", false),
                EmoticonEntity(12, "（／_＼）", false),
                EmoticonEntity(12, "（／．＼）", false),
                EmoticonEntity(12, "（/｡＼)", false),
                EmoticonEntity(12, "(／。＼)", false),
                EmoticonEntity(12, "(／(ｴ)＼)", false),
                EmoticonEntity(12, "(/ω＼)", false),
                EmoticonEntity(12, "(⊃‿⊂)", false),
                EmoticonEntity(12, "(ノдヽ)", false),
                EmoticonEntity(12, "◑.◑", false),
                EmoticonEntity(12, "ヽ(ﾟДﾟ)ﾉ", false),
                EmoticonEntity(12, "工ｴｴｪｪ(;╹⌓╹)ｪｪｴｴ工", false),
                EmoticonEntity(12, "(((╹д╹;)))", false),
                EmoticonEntity(12, "ε=ε=(っ*´□`)っ", false),
                EmoticonEntity(12, "ε=ε=(怒ﾟДﾟ)ﾉ", false),
                EmoticonEntity(12, "=͟͟͞͞ =͟͟͞͞ ﾍ( ´Д`)ﾉ", false),
                EmoticonEntity(12, "ヽ(￣д￣;)ノ=3=3=3", false),
                EmoticonEntity(12, "(꒪ȏ꒪;)", false),
                EmoticonEntity(12, "(╬⁽⁽ ⁰ ⁾⁾ Д ⁽⁽ ⁰ ⁾⁾)", false),
                EmoticonEntity(12, "٩(´Д` ;)۶:.*", false),
                EmoticonEntity(12, "ヾ( •́д•̀ ;)ﾉ", false),
                EmoticonEntity(12, "〣( ºΔº )〣", false),
                EmoticonEntity(12, "(⊃д⊂)", false),
                EmoticonEntity(12, "ヽ ( ꒪д꒪ )ﾉ", false),
                EmoticonEntity(12, ")Д⊙`)", false),
                EmoticonEntity(12, "ヾ( ๑´д`๑)ﾂ", false),
                EmoticonEntity(12, "(´×д×`三꒪д꒪ ;)", false),
                EmoticonEntity(12, "– =͟͟͞͞ =͟͟͞͞ ﾍ( ´Д`)ﾉ", false),
                EmoticonEntity(12, "ヾ(((;ꈡ▱ꈡ;)))ﾉ", false),
                EmoticonEntity(12, "ε＝ε＝ε＝(((((ﾉ｀･Д･)ﾉ", false),
                EmoticonEntity(12, "(◞º❒º)◞₎₎(◟º❑º)◟⁾⁾➟➠➨", false),
                EmoticonEntity(12, "˓⁽͑ʺˀ́˙̻ˁ̀ʺ⁾̉ʾʾ ᵏᵞᵅ˞ᵎ", false),
                EmoticonEntity(12, "( ⚆ _ ⚆ )", false),
                EmoticonEntity(12, "џ(ºДºџ)", false),
                EmoticonEntity(12, "(˵¯͒ བ¯͒˵)", false),
                EmoticonEntity(12, "(☍д⁰)", false),
                EmoticonEntity(12, "(*/∇＼*)", false),
                EmoticonEntity(12, "ヽ(;ﾟ;∀;ﾟ; )ﾉ", false),
                EmoticonEntity(12, "ヽ( ;ﾟ;ж;ﾟ;)ﾉ", false),
                EmoticonEntity(12, "ε=٩(●❛ö❛)۶", false),
                EmoticonEntity(12, "Σ(ﾟДﾟ；≡；ﾟдﾟ)", false),
                EmoticonEntity(12, "－(゜Д゜;)-ン!", false),
                EmoticonEntity(12, "━(◯Δ◯∥)━ン", false),
                EmoticonEntity(12, "(c=(c=(c=(c=(ﾟﾛﾟ;c=", false),
                EmoticonEntity(12, "(ﾟДﾟ；)ゞ", false),
                EmoticonEntity(12, "⊂(ﾟДﾟ;⊂⌒`つ", false),
                EmoticonEntity(12, "..･ヾ(。￣□￣)ﾂ", false),
                EmoticonEntity(12, "エｴｪｪｪ(●’Д’●)ｪｪｪｴエ", false),
                EmoticonEntity(12, "≡≡≡=(ﾉTдT)ﾉ", false),
                EmoticonEntity(12, "ε=ε=(⊃≧□≦)⊃", false),
                EmoticonEntity(12, "!!Σ(ﾟДﾟ;≡≡≡≡≡ヾ(;ﾟдﾟ)/", false),
                EmoticonEntity(12, "(ﾟДﾟ;)", false),
                EmoticonEntity(12, " (ﾟдﾟ；)", false),
                EmoticonEntity(12, "∠(ﾟДﾟ)/", false),
                EmoticonEntity(12, "‘`( ꒪Д꒪),､", false),
                EmoticonEntity(12, "┃ ु ⠁⃘ ⠁⃘ू┃⁼³₌₃", false),
                EmoticonEntity(12, "(╬☉д⊙)", false),
                EmoticonEntity(12, "༻(〃ຶ⌂〃ຶ)", false),
                EmoticonEntity(12, "y( ꒪◊꒪)y", false),
                EmoticonEntity(12, "ਭ३౽=͟͟͞͞(((ഽʻ⁸ʻ)ഽ", false),
                EmoticonEntity(12, "σ(ｏдｏlll)", false),
                EmoticonEntity(12, "ε=ε=ε=(ﾉ≧∀)ﾉ", false),
                EmoticonEntity(12, "(❛ӧ❛三❛ӧ❛)", false),
                EmoticonEntity(12, "Σ(°Д°；≡；°д°)", false),
                EmoticonEntity(12, "(`･/д＼･)", false),
                EmoticonEntity(12, "(ﾟДﾟ?)", false),
                EmoticonEntity(12, "ε=ε=ε=(ﾉTдT)ﾉ", false),
                EmoticonEntity(12, "(　〇□〇）", false),
                EmoticonEntity(12, "～ε～ε～┌(|||´Д｀)ノ", false),
                EmoticonEntity(12, "゛(ﾉ~o~)ﾉ", false),
                EmoticonEntity(12, "ε=ε=ε=┏(ﾟロﾟ;)┛", false),
                EmoticonEntity(12, "(((φ(◎ロ◎;)φ)))", false),
                EmoticonEntity(12, "ε==ε==(ﾉ゜д゜)ﾂ", false),
                EmoticonEntity(12, "ヽ(≡ω≡;ヽ)", false),
                EmoticonEntity(12, "(ﾉ;≡ω≡)ﾉ", false),
                EmoticonEntity(12, "ヽ(д`ヽ)｡｡", false),
                EmoticonEntity(12, "｡｡(ﾉ´д)ﾉ", false),
                EmoticonEntity(12, "ヽ(´Д｀;≡;´Д｀)丿", false),
                EmoticonEntity(12, "((ヽ(´Д`;ゞ=ヾ;´Д`)ﾉ))", false),
                EmoticonEntity(12, "ヽ(ω；`ヽ))…((ﾉ´；ω)ﾉ", false),
                EmoticonEntity(12, "ヽ(д｀ヽ彡ﾉ´д)ﾉ", false),
                EmoticonEntity(12, "ヾ(´ﾟДﾟ｀;)ゝ", false),
                EmoticonEntity(12, "(#｀ﾟд´)ﾉ", false),
                EmoticonEntity(12, "ε=ε=ε=(((怒ﾟДﾟ)ﾉﾉ", false),
                EmoticonEntity(12, "((ﾟ□ﾟ;))", false),
                EmoticonEntity(12, "ε=ε=ε=(*ﾉ´Д｀)ﾉﾟ", false),
                EmoticonEntity(12, "ヾ(*゜、ω゜*)ﾉﾟ", false),
                EmoticonEntity(12, "゛(●ﾉ´・Д・｀)ﾉ", false),
                EmoticonEntity(12, "!!((((((っ;ﾟ∀ﾟ)っ", false),
                EmoticonEntity(12, "ゞ◎Д◎ヾ", false),
                EmoticonEntity(
                    12, "へ( ʘ͡ ₒ ʘ͡ )╮/\\╱\\", false
                ),
                EmoticonEntity(
                    12, "╰། ᵒ̌ д ᵒ̌ །╯", false
                ),
                EmoticonEntity(12, "(●゜□゜)人(゜□゜○)", false),
                EmoticonEntity(12, "ヽ(○´Д｀)ﾉ", false),
                EmoticonEntity(12, "(゜Д゜*)", false),
                EmoticonEntity(12, "（（（（（（（（　゜□゜）ノ", false),
                EmoticonEntity(12, "⊃゜Д゜）⊃", false),
                EmoticonEntity(12, "⊂（゜Д゜⊂", false),
                EmoticonEntity(12, "§;ﾟﾛﾟ§", false),
                EmoticonEntity(12, "┗|*´ﾟДﾟ｀|┛", false),
                EmoticonEntity(12, "(ノ´ロ`)ノ", false),
                EmoticonEntity(12, "(ノ ゜口゜)ノ", false),
                EmoticonEntity(12, "ヾ(･c_,･｡) ﾉ =з =з= з", false),
                EmoticonEntity(12, "(ｼ;ﾟДﾟ)ｼ", false),
                EmoticonEntity(12, "ヾ(ﾟДﾟ;ヾ)", false),
                EmoticonEntity(12, "ヾ(;ﾟДﾟ;)ｼ", false),
                EmoticonEntity(12, "｡｡゛(ﾉ><)ﾉ", false),
                EmoticonEntity(12, "（ΩДΩ）", false),
                EmoticonEntity(12, "ε≡Ξ≡Ξ≡ヽ( ;￣〇￣)ﾉ", false),
                EmoticonEntity(12, "ヽ(ﾟ□ﾟ＼*≡*／ﾟ□ﾟ)ﾉ", false),
                EmoticonEntity(12, "!!!!!!(ﾟﾛﾟ屮)屮", false),
                EmoticonEntity(12, "ヽ(#ﾟДﾟ)ﾉ", false),
                EmoticonEntity(12, "ヾ(´囗｀｡)ﾉ", false),
                EmoticonEntity(12, "!!(ﾉ*ﾟДﾟ)ﾉ", false),
                EmoticonEntity(12, "(/;◇;)/", false),
                EmoticonEntity(12, ",､’`( ꒪Д꒪),､’`’`,､", false),
                EmoticonEntity(12, "◝(๑⁺д⁺๑)◞՞", false),
                EmoticonEntity(12, "ﾍ(;´o｀)ﾍ", false),
                EmoticonEntity(12, "(°□°)⊅", false),
                EmoticonEntity(12, "Σ(°□°)⊃", false),
                EmoticonEntity(12, "ε＝（ﾉﾟдﾟ）ﾉ", false),
                EmoticonEntity(12, "(＾ω＾ ≡ °д°)", false),
                EmoticonEntity(12, "(-@Д@)", false),
                EmoticonEntity(12, "(｢⊙Д⊙)｢", false),
                EmoticonEntity(12, "<|๑⊙Д⊙|/", false),
                EmoticonEntity(12, "ლ|’Д’ლ|", false),
                EmoticonEntity(12, "（｀〇Д〇）", false),
                EmoticonEntity(12, "…(ﾟⅩﾟ)…。", false),
                EmoticonEntity(12, "(＠O＠;)", false),
                EmoticonEntity(12, "（ΟΔΟ；；）", false),
                EmoticonEntity(12, "（┛〃°　Д°）┛", false),
                EmoticonEntity(12, "ヽ〔ﾟДﾟ〕丿", false),
                //OTHERS
                EmoticonEntity(13, "( ͡ຈ╭͜ʖ╮͡ຈ )", false),
                EmoticonEntity(13, "( ͡ಠ ʖ̯ ͡ಠ)", false),
                EmoticonEntity(13, "( ͡~ ͜ʖ ͡~)", false),
                EmoticonEntity(13, "( ͡~ ͜ʖ ͡°)", false),
                EmoticonEntity(13, "( ͠° ͟ʖ ͡°)", false),
                EmoticonEntity(13, "( ͡ʘ╭͜ʖ╮͡ʘ)", false),
                EmoticonEntity(13, "( ͝סּ ͜ʖ͡סּ)", false),
                EmoticonEntity(13, "( ͡ᵔ ͜ʖ ͡ᵔ )", false),
                EmoticonEntity(13, "( ͡^ ͜ʖ ͡^ )", false),
                EmoticonEntity(13, "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]", false),
                EmoticonEntity(13, "( ͡ຈ ͜ʖ ͡ຈ)", false),
                EmoticonEntity(13, "( ͡° ʖ̯ ͡°)", false),
                EmoticonEntity(13, "( ͡ ͜ʖ ͡ )", false),
                EmoticonEntity(13, "(☞ ͡° ͜ʖ ͡°)☞", false),
                EmoticonEntity(13, "ᕕ( ͡° ͜ʖ ͡° )ᕗ", false),
                EmoticonEntity(13, "( ͡° ͜ʖ ͡°)", false),
                EmoticonEntity(13, "( ͡°╭͜ʖ╮͡° )", false),
                EmoticonEntity(13, "(つ ͡° ͜ʖ ͡°)つ", false),
                EmoticonEntity(13, "( ͡⚆ ͜ʖ ͡⚆)", false),
                EmoticonEntity(13, "¯\\_( ͠° ͟ʖ °͠ )_/¯", false),
                EmoticonEntity(13, "(▀ ͜ʖ ͡°)", false),
                EmoticonEntity(13, "༼ ºل͟º ༽", false),
                EmoticonEntity(13, "┌༼ຈل͜ຈ༽┐", false),
                EmoticonEntity(13, "༼ ಠل͟ಠ༽", false),
                EmoticonEntity(13, "୧༼ ͡◉ل͜ ͡◉༽୨", false),
                EmoticonEntity(13, "ヽ༼ ಠ益ಠ ༽ﾉ", false),
                EmoticonEntity(13, "༼ ༎ຶ ෴ ༎ຶ༽", false),
                EmoticonEntity(13, "༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽", false),
                EmoticonEntity(13, "༼･ิɷ･ิ༽", false),
                EmoticonEntity(13, "༼ ͒ ̶ ͒༽", false),
                EmoticonEntity(13, "༼༼;; ;°;ਊ°;༽", false),
                EmoticonEntity(13, "༼( ⁍ืེ – ⁍ื༽༽", false),
                EmoticonEntity(13, "༼•͟ ͜ •༽", false),
                EmoticonEntity(13, "༼•̃͡ ɷ•̃͡༽", false),
                EmoticonEntity(13, "༼ ͒ ͓ ͒༽", false),
                EmoticonEntity(13, "༼༭ຶཬ༤ຶ༽", false),
                EmoticonEntity(13, "༼ꉺˇɷˇꉺ༽", false),
                EmoticonEntity(13, "༼இɷஇ༽", false),
                EmoticonEntity(13, "༼✷ɷ✷༽", false),
                EmoticonEntity(13, "༼ԾɷԾ༽", false),
                EmoticonEntity(13, "༼≖ɷ≖༽", false),
                EmoticonEntity(13, "༼ꉺ✺ꉺ༽", false),
                EmoticonEntity(13, "༼ꉺლꉺ༽", false),
                EmoticonEntity(13, "ヽ༼ຈل͜ຈ༽ﾉ", false),
                EmoticonEntity(13, "༼ꉺ౪ꉺ༽", false),
                EmoticonEntity(13, "༼ꉺεꉺ༽", false),
                EmoticonEntity(13, "༼;´༎ຶ ༎ຶ ༽", false),
                EmoticonEntity(13, "༼⁰o⁰；༽", false),
                EmoticonEntity(13, "༼(⁽͇ˊ̑⁾ ἴृ ⁽ˋ̑⁾͇)༽", false),
                EmoticonEntity(13, "˓ ू༼ ்ͦ॔ཀ ்ͦ॓ू༽", false),
                EmoticonEntity(13, "༼ ु ்ͦ॔ཫ ்ͦ॓༽ु˒˒", false),
                EmoticonEntity(13, "／༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽", false),
                EmoticonEntity(13, "༼ ்ͦ॔ཫ ்ͦ॓༽", false),
                EmoticonEntity(13, "༼ᶿ᷇ཫᶿ᷆༽", false),
                EmoticonEntity(13, "༼  ऀืົཀ  ऀืົ༽", false),
                EmoticonEntity(13, "༼՟ິͫཀ՟ິͫ༽", false),
                EmoticonEntity(13, "ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪", false),
                EmoticonEntity(13, "༼❁ɷ❁༽", false),
                EmoticonEntity(13, "༼ ຶཽཀ ຶཽ༽", false),
                EmoticonEntity(13, "ヽ༼၀-၀༽ﾉ", false),
                EmoticonEntity(13, "༼(❛)㇁(❛)༽", false),
                EmoticonEntity(13, "ヽ༼⊙_⊙༽ﾉ", false),
                EmoticonEntity(13, "༼⺤`皿′⺤༽", false),
                EmoticonEntity(13, "ヽ༼࿃っ࿃༽ﾉ", false),
                EmoticonEntity(13, "༼⌐■ل͟■༽", false),
                EmoticonEntity(13, "༼ง=ಠ益ಠ=༽ง", false),
                EmoticonEntity(13, "╰༼=ಠਊಠ=༽╯", false),
                EmoticonEntity(13, "ᕙ༼*◕_◕*༽ᕤ", false),
                EmoticonEntity(13, "ヽ༼ಢ_ಢ༽ﾉ", false),
                EmoticonEntity(13, "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ", false),
                EmoticonEntity(13, "┌༼ ⊘ _ ⊘ ༽┐", false),
                EmoticonEntity(13, "༼ : ౦ ‸ ౦ : ༽", false),
                EmoticonEntity(13, "༼∗ღ۝ღ∗༽", false),
                EmoticonEntity(13, "༼ง ͠ຈ ͟ل͜ ͠ຈ༽o:[]:::::::>", false),
                EmoticonEntity(13, "༼ᕗຈل͜ຈ༽ᕗ", false),
                EmoticonEntity(13, "ヽ༼ຈل͜ರೃ༽ﾉ", false),
                EmoticonEntity(13, "ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ", false),
                EmoticonEntity(13, "༼ ᕤ◕◡◕ ༽ᕤ", false),
                EmoticonEntity(13, "ᕙ༼˵͠ ͠°ل͜͠ ͠°˵༽ᕗ", false),
                EmoticonEntity(13, "ᕦ༼::ಥ෴ಠೃ::༽ノ", false),
                EmoticonEntity(13, "༼ •̀ ں •́ ༽", false),
                EmoticonEntity(13, "♫ ┌༼ຈل͜ຈ༽┘ ♪", false),
                EmoticonEntity(13, "༼ ಥل͟ಥ ༽", false),
                EmoticonEntity(13, "༼ﾉƟ͆ل͜Ɵ͆༽ﾉ", false),
                EmoticonEntity(13, "༼୨Ɵ͆ل͜Ɵ͆༽୨", false),
                EmoticonEntity(13, "ヽ༼Ɵ͆ل͜Ɵ͆ヽ༽", false),
                EmoticonEntity(13, "୧༼Ɵ͆ل͜Ɵ͆୧༽", false),
                EmoticonEntity(13, "┌༼ຈل͜ຈ༽┘", false),
                EmoticonEntity(13, "へ༼ ✪ Ĺ̯ ✪ ༽و", false),
                EmoticonEntity(13, "c༼ ͡° ͜ʖ ͡° ༽⊃", false),
                EmoticonEntity(13, "༼ ಠ ͟ʖ ಠ ༽", false),
                EmoticonEntity(13, "୧༼ ” ✖ ‸ ✖ ” ༽୨", false),
                EmoticonEntity(13, "¯\\_༼ᴼل͜ᴼ༽_/¯", false),
                EmoticonEntity(13, "┏༼ ◉ ╭╮ ◉༽┓", false),
                EmoticonEntity(13, "ヽ༼ ☯‿☯༼ ಠ益ಠ༽◕ل͜◕༽つ", false),
                EmoticonEntity(13, "└༼ •́ ͜ʖ •̀ ༽┘", false),
                EmoticonEntity(13, "୧༼ ヘ ᗜ ヘ ༽୨", false),
                EmoticonEntity(13, "༼ ◔ ͜ʖ ◔ ༽", false),
                EmoticonEntity(13, "╰༼⇀︿⇀༽つ-]═──", false),
                EmoticonEntity(13, "乁༼☯‿☯✿༽ㄏ", false),
                EmoticonEntity(13, "ヽ༼>ل͜<༽ﾉ", false),
                EmoticonEntity(13, "ɳ༼ຈل͜ຈ༽ɲ", false),
                EmoticonEntity(13, "¯\\_༼ ି ~ ି ༽_/¯", false),
                EmoticonEntity(13, "ᕦ༼ ˵ ◯ ਊ ◯ ˵ ༽ᕤ", false),
                EmoticonEntity(13, "¯\\_༼ ಥ ‿ ಥ ༽_/¯", false),
                EmoticonEntity(13, "༼♥ل͜♥༽", false),
                EmoticonEntity(13, "Ѱζ༼ᴼل͜ᴼ༽ᶘѰ", false),
                EmoticonEntity(13, "ζ༼Ɵ͆ل͜Ɵ͆༽ᶘ", false),
                EmoticonEntity(13, "ᕦ༼ ͡° ͜ ͝° ༽ᕤ", false),
                EmoticonEntity(13, "ヽ༼ ☭ل͜☭ ༽ﾉ", false),
                EmoticonEntity(13, "˓˓ ू༼ ⠁⃘ཀ ⠁⃘ू༽", false),
                EmoticonEntity(13, "༼ ु⠁⃘ཫ ⠁⃘༽ु˒˒", false),
                EmoticonEntity(13, "ᕕ༼✿•̀︿•́༽ᕗ", false),
                EmoticonEntity(13, "༼つಠ益ಠ༽つ ─=≡ΣO))", false),
                EmoticonEntity(13, "ヽ༼௵ل͜௵༽ﾉ", false),
                EmoticonEntity(13, "♡(•ི̛ᴗ•̛)ྀ", false),
                EmoticonEntity(13, "(((༼•̫͡•༽)))", false),
                EmoticonEntity(13, "(*ﾟ⚙͠ ∀ ⚙͠)ﾉ❣", false),
                EmoticonEntity(13, "(*ꆤ.̫ꆤ*)", false),
                EmoticonEntity(13, "(ી(΄◞ิ౪◟ิ‵)ʃ)", false),
                EmoticonEntity(13, "༼∵༽", false),
                EmoticonEntity(13, "༼⍤༽", false),
                EmoticonEntity(13, "༼⍢༽", false),
                EmoticonEntity(13, "༼⍨༽", false),
                EmoticonEntity(13, "✌(꒡͡ ો ̼̮ ꒡͡✌)", false),
                EmoticonEntity(13, "⋆•̵̑ ੭͜•̵̑⋆", false),
                EmoticonEntity(13, "♡*(ू•‧̫•ू⑅)♡⋆*ೃ:.✧", false),
                EmoticonEntity(13, "לּ_לּ", false),
                EmoticonEntity(13, "טּ_טּ", false),
                EmoticonEntity(13, "תּ_תּ", false),
                EmoticonEntity(13, "ཥ•̫͡•ཤ", false),
                EmoticonEntity(13, "༗.̫̮ ༗✧", false),
                EmoticonEntity(13, "૮(ㅍ◞◟ㅍ)ა", false),
                EmoticonEntity(13, "০ੇ৴ ੁ ০ੇ", false),
                EmoticonEntity(13, "ꁋꐪ", false),
                EmoticonEntity(13, "˚✧₊⁎❝᷀ົཽ≀ˍ̮ ❝᷀ົཽ⁎⁺˳✧༚", false),
                EmoticonEntity(13, "(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄", false),
                EmoticonEntity(13, "ˁ ¨̫͌ ˀ", false),
                EmoticonEntity(13, "ᓬᗽᗳ", false),
                EmoticonEntity(13, "(͔ઉ૮̭ઉે)͕", false),
                EmoticonEntity(13, "(⸅᷇˾ͨ⸅᷆ ˡ᷅ͮ˒)", false),
                EmoticonEntity(13, "(⸅᷇˾ͨ⸅᷆⸜⸌˒ े੭", false),
                EmoticonEntity(13, "(⸅᷇˾ͨ⸅᷆ ⁾˗̡⁾", false),
                EmoticonEntity(13, "(‧⃘︠˾ͨ̅‧⃘︡˒᷅̈́)", false),
                EmoticonEntity(13, "(⸅᷇˾ͨ⸅᷆ ⸌̈́˒̅̈́)", false),
                EmoticonEntity(13, "(̵⸅̥᷇̂ ̫̖⸅̮᷆̂ ˗̖́े", false),
                EmoticonEntity(13, "(ᴑ̨̨̍̆͞͡ ͦ̆ ॑ᵓ̩̗̍", false),
                EmoticonEntity(13, "(⸅̥᷇͏̵˲̎ͨ⸅̥̖᷆̾ ̵˒͋)", false),
                EmoticonEntity(13, "(⸅᷇᷅̑˾ͨ⸅᷆᷄̑ ⸌᷄̑˒ ेɜ", false),
                EmoticonEntity(13, "(⸅̥᷇͞͡͏̵ͺͨ⸅̥᷆ ̵ˡ͛˒̡ͥ͛", false),
                EmoticonEntity(13, "〈⸅̨᷇͞͞ˬ̵̮̑̉⸅̮̖᷆͵̸ͥ͛˒ͥͥ", false),
                EmoticonEntity(13, "(⸝⸝⸝՞̐ˀ̝՞̐)", false),
                EmoticonEntity(13, "◟₍ꇪ̥༵₎◞", false),
                EmoticonEntity(13, "﹡̤̥⃝", false),
                EmoticonEntity(13, "ᵋ̈⃝͚", false),
                EmoticonEntity(13, "⠒̫⃝", false),
                EmoticonEntity(13, "⍢⃞", false),
                EmoticonEntity(13, "⍥⃞", false),
                EmoticonEntity(13, "⍤⃞", false),
                EmoticonEntity(13, "⍨⃞", false),
                EmoticonEntity(13, "⍩⃞", false),
                EmoticonEntity(13, "ꀸꋰ)", false),
                EmoticonEntity(13, "༼¨̠༽", false),
                EmoticonEntity(13, "༼Ǖ༽", false),
                EmoticonEntity(13, "༼ɷ̈༽", false),
                EmoticonEntity(13, "༼ΐ̠༽", false),
                EmoticonEntity(13, "༼Ϊ̠༽", false),
                EmoticonEntity(13, "༼Ѫ̈༽", false),
                EmoticonEntity(13, "༼ѷ༽", false),
                EmoticonEntity(13, "༼Ӓ༽", false),
                EmoticonEntity(13, "༼ ˳̮̑̈༽", false),
                EmoticonEntity(13, " ˓˓༼ˀᵕ̈༽", false),
                EmoticonEntity(13, "ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪", false),
                EmoticonEntity(13, "(༼•̀ɷ•́༽)", false),
                EmoticonEntity(13, "ヽ༽ຈل͜ຈ༼ﾉ", false),
                //BEARS
                EmoticonEntity(14, "ʕ •́؈•̀ ₎", false),
                EmoticonEntity(14, "ᶘ ᵒᴥᵒᶅ", false),
                EmoticonEntity(14, "ʕノ•ᴥ•ʔノ ︵ ┻━┻", false),
                EmoticonEntity(14, "ᵔᴥᵔ", false),
                EmoticonEntity(14, "ଘ( ິ•ᆺ⃘• )ິଓ", false),
                EmoticonEntity(14, "ᵋ₍⚬ɷ⚬₎ᵌ", false),
                EmoticonEntity(14, "ˁ̡̡̡∗⁎⃙ ̫⁎⃙ˀ̡̡̡ ̩˳♡⃝", false),
                EmoticonEntity(14, "( ິ•ᆺ⃘• )ິฅ✧", false),
                EmoticonEntity(14, "ต( ິᵒ̴̶̷̤ ﻌ ᵒ̴̶̷̤ )ິ ♬", false),
                EmoticonEntity(14, "ฅ( ̳͒•ಲ• ̳͒)♪", false),
                EmoticonEntity(14, "ᶘ ᵒ㉨ᵒᶅ", false),
                EmoticonEntity(14, "ᶘ ͡°ᴥ͡°ᶅ", false),
                EmoticonEntity(14, "ต( ິᵒ̴̶̷̤́ᆺ⃘ᵒ̴̶̷̤̀ )ິต", false),
                EmoticonEntity(14, "٩ʕ•͡×•ʔ۶", false),
                EmoticonEntity(14, "v.ʕʘ‿ʘʔ.v", false),
                EmoticonEntity(14, "ʔ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ·͡ˑ·ཻʔ", false),
                EmoticonEntity(14, "ʕ•͡-•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ♡*:.✧", false),
                EmoticonEntity(14, "ʕ•̫͡•ིʔྀ", false),
                EmoticonEntity(14, "ʕ•͡ɛ•͡ʼʼʔ", false),
                EmoticonEntity(14, "ʕ•͡ω•ʔ", false),
                EmoticonEntity(14, "ʕ•̀ω•́ʔ✧", false),
                EmoticonEntity(14, "ʕ•ӫ̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͡દ•ʔ", false),
                EmoticonEntity(14, "ʕʽɞʼʔ", false),
                EmoticonEntity(14, "ʕʘ̅͜ʘ̅ʔ", false),
                EmoticonEntity(14, "ʢٛ•ꇵٛ•ʡ", false),
                EmoticonEntity(14, "ฅʕ•̫͡•ʔฅ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ♬✧", false),
                EmoticonEntity(14, "ʕ•ᴥ•ʔ", false),
                EmoticonEntity(14, "ʕ•͡౪•ʔ", false),
                EmoticonEntity(14, "ʕ•͡•ʔ", false),
                EmoticonEntity(14, "ʕ⁰̈●̫⁰̈ʔ", false),
                EmoticonEntity(14, "ʕ•ૅૄ•ʔ", false),
                EmoticonEntity(14, "ʕ⁎̯͡⁎ʔ༄", false),
                EmoticonEntity(14, "ʕ-͏̶̶̶̯͡-ʔ", false),
                EmoticonEntity(14, " ʢ•ꇵ͡•ʡ✩⃛", false),
                EmoticonEntity(14, "ʢ•ꇵ͡•ʡ✩⃛", false),
                EmoticonEntity(14, "ʕ๑◞◟๑ʔ", false),
                EmoticonEntity(14, "✌.ʕʘ‿ʘʔ.✌", false),
                EmoticonEntity(14, "ʕ灬￫ᴥ￩灬ʔ", false),
                EmoticonEntity(14, "ʕ•⍝͡•ʔ", false),
                EmoticonEntity(14, "ʕ ·(エ)· ʔ", false),
                EmoticonEntity(14, "ʕథ౪థʔ", false),
                EmoticonEntity(14, "ʕ￫ᴥ￩ʔ", false),
                EmoticonEntity(14, "ʕ•̫๑͡•ʔ∣ժ̅ʒ∾ෆ⃛", false),
                EmoticonEntity(14, "ʕ•༘͡.•ʔ", false),
                EmoticonEntity(14, "=͟͟͞͞•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʢᵕᴗᵕʡ", false),
                EmoticonEntity(14, "ʕ•̬͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͕͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͚͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͓͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͈͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̬͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̥͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̠͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̮͡•ʔ", false),
                EmoticonEntity(14, "ʕº̫͡ºʔ", false),
                EmoticonEntity(14, "◟ʕ´∀`ʔ◞", false),
                EmoticonEntity(14, "ʕ　·ᴥ·ʔ", false),
                EmoticonEntity(14, "ʕ·ᴥ·　ʔ", false),
                EmoticonEntity(14, "ʕ*̫͡*ʔ", false),
                EmoticonEntity(14, "˓˓ʕ՚Ջ՝ूɁ॰∘☼", false),
                EmoticonEntity(14, "ʕ•͡દ•ʔ❥ꋧ", false),
                EmoticonEntity(14, "ʕ•͜ ͢ ͞ •ʔ", false),
                EmoticonEntity(14, "ʕ∙ჲ∙ʔ", false),
                EmoticonEntity(14, "ʕっ•ᴥ•ʔっ", false),
                EmoticonEntity(14, "ʕ ∗ •́ ڡ •̀ ∗ ʔ", false),
                EmoticonEntity(14, "୧ʕ ⇀ ⌂ ↼ ʔ୨", false),
                EmoticonEntity(14, "ʕ •̀ o •́ ʔ", false),
                EmoticonEntity(14, "ʕ·͡ᴥ·ʔ", false),
                EmoticonEntity(14, "ʕง•ᴥ•ʔง", false),
                EmoticonEntity(14, "ʕっ˘ڡ˘ςʔ", false),
                EmoticonEntity(14, "ʕ≧㉨≦ʔ", false),
                EmoticonEntity(14, "ʕ　·㉨·ʔ", false),
                EmoticonEntity(14, "ʕ´•㉨•`ʔ", false),
                EmoticonEntity(14, "ʕ•㉨•ʔ", false),
                EmoticonEntity(14, "ʕ￫ᴥ￩　ʔ", false),
                EmoticonEntity(14, "╲ʕ·ᴥ·　╲ʔ", false),
                EmoticonEntity(14, "ʕ； •`ᴥ•´ʔ", false),
                EmoticonEntity(14, "ʕ≧ᴥ≦ʔ", false),
                EmoticonEntity(14, "ʕ♡˙ᴥ˙♡ʔ", false),
                EmoticonEntity(14, "ʕ´•ᴥ•`ʔ", false),
                EmoticonEntity(14, "ʕᴥ• ʔ☝", false),
                EmoticonEntity(14, "ʕ☞ᴥ ☜ʔ", false),
                EmoticonEntity(14, "ʕ╯• ⊱ •╰ʔ", false),
                EmoticonEntity(14, "ʕ/　·ᴥ·ʔ/", false),
                EmoticonEntity(14, "ʕノ)ᴥ(ヾʔ", false),
                EmoticonEntity(14, "ʅʕ•ᴥ•ʔʃ", false),
                EmoticonEntity(14, "ʕ´•ᴥ•`ʔσ”", false),
                EmoticonEntity(14, "ʕ*ﾉᴥﾉʔ", false),
                EmoticonEntity(14, "“φʕ•ᴥ•oʔ", false),
                EmoticonEntity(14, "Σʕﾟᴥﾟﾉʔﾉ", false),
                EmoticonEntity(14, "ʕ ﾟ ● ﾟʔ", false),
                EmoticonEntity(14, "ʕ •ᴥ•ʔ", false),
                EmoticonEntity(14, "ʕᴥ·　ʔ", false),
                EmoticonEntity(14, "ʕ　·ᴥʔ", false),
                EmoticonEntity(14, "ʕ ⊃･ ◡ ･ ʔ⊃", false),
                EmoticonEntity(14, "ʕ ಡ ﹏ ಡ ʔ", false),
                EmoticonEntity(14, "୧ʕ•̀ᴥ•́ʔ୨", false),
                EmoticonEntity(14, "ʕ·ᴥ·ʔ", false),
                EmoticonEntity(14, "ʕº́גº̀ʔ", false),
                EmoticonEntity(14, "ʕ ᵒ̌ ‸ ᵒ̌ ʔ", false),
                EmoticonEntity(14, "ʕ•͡•ʔ", false),
                EmoticonEntity(14, "ʕ ´ ل͜ ´ ʔ", false),
                EmoticonEntity(14, "ʕ – ▃ – ʔ", false),
                EmoticonEntity(14, " ʕ ˵ ̿ ౪ ̿ ˵ ʔ", false),
                EmoticonEntity(14, "ʕ-ᴥ – ʔԅ(`ɛ`ԅ)", false),
                EmoticonEntity(14, "ʕ ” – ∧ – ” ʔ", false),
                EmoticonEntity(14, "ʕ ▀ ਊ ▀ ʔ", false),
                EmoticonEntity(14, "ʕ ▀ ڡ ▀ ʔ", false),
                EmoticonEntity(14, "ʕ ି ڡ ି ʔ", false),
                EmoticonEntity(14, "ʕ ” ￣ Ĺ̯ ￣ ” ʔ", false),
                EmoticonEntity(14, "ʕ ཀ ⌂ ཀ ʔ", false),
                EmoticonEntity(14, "ʕ ☯ ڡ ☯ ʔ", false),
                EmoticonEntity(14, "ʕ ಡ Ĺ̯ ಡ ʔ", false),
                EmoticonEntity(14, "ԅʕ ◖ ᴥ ◗ ʔ୨", false),
                EmoticonEntity(14, "୧ʕ ◕ o ◕ ʔ୨", false),
                EmoticonEntity(14, " ʕ • ₒ • ʔ", false),
                EmoticonEntity(14, "ʕ ˵ ͒ ʖ̯ ͒ ˵ ʔ", false),
                EmoticonEntity(14, "ᕦʕ . ☯ ᴥ ☯ . ʔᕤ", false),
                EmoticonEntity(14, "ʕ”̣̫Ɂ", false),
                EmoticonEntity(14, "ʕ•͡ȅ•ʔ", false),
                EmoticonEntity(14, "ᕦʕ ⊙ ◡ ⊙ ʔᕤ", false),
                EmoticonEntity(14, "୧ʕ ⊚ ͟ل͜ ⊚ ʔ୨", false),
                EmoticonEntity(14, "ʕ ಡ ﹏ ಡ ʔ⊃―{}@{}@{}-", false),
                EmoticonEntity(14, "ʕﾉﾉﾉ؈ㅎʔ", false),
                EmoticonEntity(14, "ʕﾉﾉﾉ_ㅎʔ", false),
                EmoticonEntity(14, "ʕﾉﾉﾉ_ʖʘʔ", false),
                EmoticonEntity(14, "ʕﾉﾉﾉ_ɔㅎʔ", false),
                EmoticonEntity(14, "ʕ╹ヮ╹｡ʔ", false),
                EmoticonEntity(14, "ʕ≧⌄≦｡ʔ", false),
                EmoticonEntity(14, "ʕ๑廿ڡ廿ʔ", false),
                EmoticonEntity(14, "ʕʘʟ_ʘʔ", false),
                EmoticonEntity(14, "ʕ>⌓<｡ʔ", false),
                EmoticonEntity(14, "ʕ ◔ᴥ◔ ʔ", false),
                EmoticonEntity(14, "ʕ ␥_␥ʔ", false),
                EmoticonEntity(14, "ʕ ᏫᎲᏫ ʔ", false),
                EmoticonEntity(14, "ʕ ჽ ჟ ჽ ʔ", false),
                EmoticonEntity(14, "ʕ = •́ .̫ •̀ = ʔ", false),
                EmoticonEntity(14, "ʕ ⸋⸛⸋ʔ", false),
                EmoticonEntity(14, "ʕ ᘎ ჟ ᘏ ʔ", false),
                EmoticonEntity(14, "ʕ Ⴔ ჟ Ⴔ ʔ", false),
                EmoticonEntity(14, "ʕ ࿃࿆ _ ࿃࿆ ʔ", false),
                EmoticonEntity(14, "ʕ◉ᴥ◉ʔ", false),
                EmoticonEntity(14, "ʕつ ͡◔ ᴥ ͡◔ʔつ", false),
                EmoticonEntity(14, "ˁ˙˟˙ˀ", false),
                EmoticonEntity(14, "ˁ˙͠˟˙ˀ", false),
                EmoticonEntity(14, "ˁ˙͡˟˙ˀ", false),
                EmoticonEntity(14, "ˁᵒ͡ˑ̉ᵒˀ", false),
                EmoticonEntity(14, "ˁ῁̩ˀ", false),
                EmoticonEntity(14, "⁽͑˙˚̀Ꮉ˚́˙⁾̉", false),
                EmoticonEntity(14, "ˁ῁͓ˀ", false),
                EmoticonEntity(14, "ˁ῁̭ˀ", false),
                EmoticonEntity(14, "ˁ῁̮ˀ", false),
                EmoticonEntity(14, "ˁ῁̱ˀ", false),
                EmoticonEntity(14, "ˁ῁̥ˀ", false),
                EmoticonEntity(14, "ˁ῁̼ˀ", false),
                EmoticonEntity(14, "ˁ῁̩ˀ", false),
                EmoticonEntity(14, "ˁ῁̬ˀ", false),
                EmoticonEntity(14, "ˁ῁̯ˀ", false),
                EmoticonEntity(14, "ˁ῁̰ˀ", false),
                EmoticonEntity(14, "“(`(エ)´)ノ", false),
                EmoticonEntity(14, "(/-(ｴ)-＼)", false),
                EmoticonEntity(14, "(｀(エ)´)ﾉ", false),
                EmoticonEntity(14, "(´(エ)｀)", false),
                EmoticonEntity(14, "(*￣(ｴ)￣*)", false),
                EmoticonEntity(14, "(／(ｴ)＼)", false),
                EmoticonEntity(14, "(／￣(ｴ)￣)／", false),
                EmoticonEntity(14, "(^(エ)^)", false),
                EmoticonEntity(14, "(￣(エ)￣)", false),
                EmoticonEntity(14, "(￣(エ)￣)ゞ", false),
                EmoticonEntity(14, "(￣(ｴ)￣)ﾉ", false),
                EmoticonEntity(14, "(●｀･(ｴ)･´●)", false),
                EmoticonEntity(14, "(●￣(ｴ)￣●)", false),
                EmoticonEntity(14, "《/(￣(ｴ)￣)ゞ》", false),
                EmoticonEntity(14, "＼(・｀(ｪ)・)/", false),
                EmoticonEntity(14, "⊂(・(ェ)・)⊃", false),
                EmoticonEntity(14, "⊂(^(工)^)⊃", false),
                EmoticonEntity(14, "⊂(￣(ｴ)￣)⊃", false),
                EmoticonEntity(14, "⊂(￣(工)￣)⊃", false),
                EmoticonEntity(14, "⊂(◎(工)◎)⊃", false),
                EmoticonEntity(14, "ヾ(T(エ)Tヽ)", false),
                EmoticonEntity(14, "ヽ(￣(ｴ)￣)ﾉ", false),
                EmoticonEntity(14, "ヾ(´(ｴ)｀ﾉﾞ", false),
                EmoticonEntity(14, "Ψ(￣(ｴ)￣)Ψ", false),
                EmoticonEntity(14, "┏((＝￣(ｴ)￣=))┛", false),
                EmoticonEntity(14, "＼＼\\ ٩(`(エ)´ )و //／／", false),
                EmoticonEntity(14, "(///◔(ｪ)◔///)", false),
                EmoticonEntity(14, "(･(ｪ)･)", false),
                EmoticonEntity(14, "(∪￣ ㋓ ￣∪)", false),
                EmoticonEntity(14, "(இ(エ)இ｀)", false),
                EmoticonEntity(14, "(Θ(ｴ)Θ*)", false),
                EmoticonEntity(14, " ⊂(▼(工)▼ﾒ)⊃", false),
                EmoticonEntity(14, "(;ﾟ(ｴ)ﾟ)", false),
                EmoticonEntity(14, "＿〆ヾ(￣(エ)￣)", false),
                EmoticonEntity(14, "|](ｴ)￣)", false),
                EmoticonEntity(14, "( ;-(ｴ)-)ゞ", false),
                EmoticonEntity(14, "( -(ｴ)-)ゞ", false),
                EmoticonEntity(14, "┐(´(エ)｀)┌", false),
                EmoticonEntity(14, "∑(＿(工)＿;)", false),
                EmoticonEntity(14, "(●￣(ｴ)￣●)ゞ", false),
                EmoticonEntity(14, "|ｴ)･)⊃", false),
                EmoticonEntity(14, "┳┳ヾ(T(エ)Tヽ)", false),
                EmoticonEntity(14, "〔´（エ）｀〕", false),
                EmoticonEntity(14, "( ´ﾉ(ｴ)｀)´(ｴ)｀)", false),
                EmoticonEntity(14, "(´･(ｪ)･｀)", false),
                EmoticonEntity(14, "（＊￣（エ）￣）ノ", false),
                EmoticonEntity(14, "(*ゝ(ェ)･)ﾉ.｡o○", false),
                EmoticonEntity(14, "⊂(*’(ェ)’)⊃", false),
                EmoticonEntity(14, " (｡ﾉ･(ｴ)･｡)ﾉ", false),
                EmoticonEntity(14, "(✪㉨✪)", false),
                EmoticonEntity(14, "(ó㉨ò)", false),
                EmoticonEntity(14, "・㉨・", false),
                EmoticonEntity(14, "(♥ó㉨ò)ﾉ♡", false),
                EmoticonEntity(14, "ヾ(;￫㉨￩)ﾉ", false),
                EmoticonEntity(14, "⊂(ο･㉨･ο)⊃", false),
                EmoticonEntity(14, "✧(๑•́ᄌ⃝ก̀๑)⋆*ೃ:.", false),
                EmoticonEntity(14, "(๑･㉨･๑)", false),
                EmoticonEntity(14, "(๏㉨๏)", false),
                EmoticonEntity(14, "(♥ó㉨ò)ノ", false),
                EmoticonEntity(14, "ヾ(♥ó㉨ò)ﾉ", false),
                EmoticonEntity(14, "(´ᄌ⃝`๑)", false),
                EmoticonEntity(14, "(❝᷁ॕᄌ❝᷁ॕ)", false),
                EmoticonEntity(14, "(ó㉨ò)ﾉ♡", false),
                EmoticonEntity(14, "ヾ(๑￫ˇ㉨￩)ノ", false),
                EmoticonEntity(14, "⊂(ο･㉨･ο）⊃", false),
                EmoticonEntity(14, "(人´㉨｀)♡", false),
                EmoticonEntity(14, "[｡◉㉨◉]", false),
                EmoticonEntity(14, "ლ(❤◕㉨◕❤ლ", false),
                EmoticonEntity(14, "(人･㉨･)♡", false),
                EmoticonEntity(14, "( ͒•ㅈ• ͒)", false),
                EmoticonEntity(14, "⁝⁞⁝⁞ʕु•̫͡•ʔु☂⁝⁞⁝⁝", false),
                EmoticonEntity(14, "ʕु-̫͡-ʔु”♬", false),
                EmoticonEntity(14, "ʕ”̮ुॽु✚⃞ྉ*✲ﾟ*｡⋆", false),
                EmoticonEntity(14, "ʕु-̫͡-ʔु”", false),
                EmoticonEntity(14, "ʕु•̫͡•ʔु ✧", false),
                EmoticonEntity(14, "ʕु•̫͡•ʔु☂", false),
                EmoticonEntity(14, "ʕु-̫͡-ʔु”", false),
                EmoticonEntity(14, "ʕ•̫͡•ॽु✚⃞ྉ*✲ﾟ*｡⋆", false),
                EmoticonEntity(14, "°◦=͟͟͞͞ʕ̡̢̡ु•̫͡•ʔ̡̢̡ु ☏", false),
                EmoticonEntity(14, "(^(I)^)", false),
                EmoticonEntity(14, "( (ﾐ´ω`ﾐ))", false),
                EmoticonEntity(14, "(⋈⚭⃛ ⌅⃝⚭⃛)ᕘ", false),
                EmoticonEntity(14, "( ´ิ(ꈊ) ´ิ)", false),
                EmoticonEntity(14, "૮(ੱꀧੱ ⋆)ა", false),
                EmoticonEntity(14, "(･(仝)･)", false),
                EmoticonEntity(14, "( ◍•㉦•◍ )", false),
                EmoticonEntity(14, "∩(☉⌄⃝☉)∩", false),
                EmoticonEntity(14, "｡•ﻌ•｡ฅ ✩", false),
                EmoticonEntity(14, "(⚬॔ꀦ॓⚬)", false),
                EmoticonEntity(14, "❃ႣᄎႣ❃", false),
                EmoticonEntity(14, "ᑦ(⁎ᐡᆺᐡ)ᐣ", false),
                EmoticonEntity(14, "తꀧత", false),
                EmoticonEntity(14, "╰໒( ͡ຈ ᴥ ຈ͡ )७╯", false),
                EmoticonEntity(14, " ⪿ ◠﹏◠ ⫀", false),
                EmoticonEntity(14, "⊂(●´(Ω)｀●)⊃", false),
                EmoticonEntity(14, "(͒ˊ(❢)ˋ)", false),
                EmoticonEntity(14, "(｡･ω･｡)", false),
                EmoticonEntity(14, "(*ノ・ω・）", false),
                EmoticonEntity(14, "川´･ω･`川", false),
                EmoticonEntity(14, "ʕ̡̢̡̡̢̡̡̢̡✩˃̶͈̀ ॢ³˂̴`͈ॢʔ̢̡̢̢̡̢̢̡̢♡⃛", false),
                EmoticonEntity(14, "ʕ̡̢̡̡̢̡̡̢♡ᵒ̴̷͈艸ᵒ̴̷͈॰ʔ̢̡̢̢̡̢̢̡̢✧", false),
                EmoticonEntity(14, "✧ʕ̢̣̣̣̣̩̩̩̩·͡˔·ོɁ̡̣̣̣̣̩̩̩̩✧", false),
                EmoticonEntity(14, "ʕ ⁎❛ั ुꈊ͒ੁ❛ั ु)", false),
                EmoticonEntity(14, "ʕ̡̢̡*✪௰✪ૢʔ̢̡̢", false),
                EmoticonEntity(14, "ʕ̡̢̡ॢ•̫͡ॢ•ʔ̢̡̢", false),
                EmoticonEntity(14, "ʕ̡̢̡๑꒪͒ꇴ꒪͒๑ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ʕ̡̢̡◌･ꄃ･◌ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ʕ̡̢̡⚭◞₀͒◟⚭̀ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ʕ̡̢̡ʘ̅͟͜͡ʘ̲̅ʔ̢̡̢", false),
                EmoticonEntity(14, "ʕ̡̢̡,,Ծ‸Ծ,, ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ʕ̡̢̡  ͡͝  ືྀ͋ ◡ु ͡͝  ືི͋ ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ৎ｡ ॄཻ͡⁎̥̥̥̥̥̥ૂॽ", false),
                EmoticonEntity(14, "ৎ⁎́ ॄཻ͡⁎̀ूॽ྆྆", false),
                EmoticonEntity(14, "✧.*◌̗·͡˔·ོᵔ̩̩͔·͡˔·◌̖*·✧", false),
                EmoticonEntity(14, "ৎˊ̣̣̣࿄ˋ̣̣ूॽ ༘ؓ ँั๊ྃ", false),
                EmoticonEntity(14, "ৎ•ु·̫•ूॽ", false),
                EmoticonEntity(14, "o͡͡͡╮ʕ ¯͒ ~ ¯͒ ʔ╭o͡͡͡", false),
                EmoticonEntity(14, "ʕ ㅎ.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨ㅎʔ", false),
                EmoticonEntity(14, "ก็็็็็็็็็็็็็ʕ•͡ᴥ•ʔ ก้้้้้้้้้้้", false),
                EmoticonEntity(14, "✧ʕ̢̣̣̣̣̩̩̩̩·͡˔·ོɁ̡̣̣̣̣̩̩̩̩✧", false),
                EmoticonEntity(14, "ʕ̡̢̡̡̢̡̡̢♡ᵒ̴̷͈艸ᵒ̴̷͈॰ʔ̢̡̢̢̡̢̢̡̢✧", false),
                EmoticonEntity(14, "ʕ̡̢̡ʘ̅͟͜͡ʘ̲̅ʔ̢̡̢", false),
                EmoticonEntity(14, "ʕ̡̢̡̡̢̡̡̢̡✩˃̶͈̀ ॢ³˂̴`͈ॢʔ̢̡̢̢̡̢̢̡̢♡⃛", false),
                EmoticonEntity(14, "ʕ̡̢̡ॢ•̫͡ॢ•ʔ̢̡̢", false),
                EmoticonEntity(14, "ৎ｡ ॄཻ͡⁎̥̥̥̥̥̥ૂॽ", false),
                EmoticonEntity(14, "˞͛ʕ̡̢̡,,Ծ‸Ծ,, ʔ̢̡̢˞͛", false),
                EmoticonEntity(14, "ʕ ㅎ.̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̸̨̨̨̨̨̨̨̨̨̨̨̨.̸̸̨̨ㅎʔ", false),
                EmoticonEntity(14, "o͡͡͡╮ʕ ¯͒ ~ ¯͒ ʔ╭o͡͡͡", false),
                EmoticonEntity(14, "ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ·͡ˑ·ཻʔෆ⃛ʕ•̫͡•ོʔ", false),
                EmoticonEntity(14, "ʕ͙•̫͑͡•ʔͦʕͮ•̫ͤ͡•ʔ͙", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̼͛͡•ʕ-̺͛͡•ʔ•̮͛͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̭͡•ʕ•̯ͦ͡•ʕ•̻̀•́ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ོʔ•̫͡•ཻʕ•̫͡•ʔ•͓͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ❣ʕ-̼͡-ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ*̫͡*ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ-̫͡-ʔ", false),
                EmoticonEntity(14, "– =͟͟͞͞ʕ•̫͡•ʔ=͟͟͞͞ʕ•̫͡•ʔ=͟͟͞͞ʕ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ*̫͡*ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ", false),
                EmoticonEntity(14, "ʕ·͡ˑ·ཻʔෆ⃛ʕ•̫͡•ོʔ", false),
                EmoticonEntity(14, "ʕ•ི̮͡•ྀʕ•̹͡-ʔ•ི̬͡•ྀʔ", false),
                EmoticonEntity(14, "ʕ•̼͡•ʕ-̺͡•ʔ•̮͡•ʔ", false),
                EmoticonEntity(14, "ʕ•̬͡•ʕ•̫͡•♥", false),
                EmoticonEntity(14, "ʕ•̫͡•ིʔྀʕ•̫͡•ིʔྀʕ•̫͡•ིʔྀ", false),
                EmoticonEntity(14, "◟ʕ´∀`ʔ◞◟ʕ´∀`ʔ ◞", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ♡ʕ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ•͡ω•ʔʕ•͡-•ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡ʕ•̫͡ʕ•̫͡ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʔ•̫͡•ʔ", false),
                EmoticonEntity(14, "=͟͟͞͞ʕ•̀=͟͟͞͞ʕ•̀▿•́=͟͟͞͞ʕ•̀▿•́ʔ=͟͟͞͞ʕ•̀▿•", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ*̫͡*ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ-̫͡-ʔ", false),
                EmoticonEntity(14, "•̫͡•ʔʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ̫͡ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ̫͡ʔ-̫͡-ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ", false),
                EmoticonEntity(14, "ʕ･_･ ;ʔ≡ʕ; ･_･ʔ", false),
                EmoticonEntity(14, "ʕㅎ_ㅎ ʔっ)´ζ｀;ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʕ*̫͡*ʕ•͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ-̫͡-ʔ", false),
                EmoticonEntity(14, "ʕ•̫͡•ʔ❤ʕ•̫͡•ʔ", false),
                //CATS
                EmoticonEntity(15, "（ΦωΦ）", false),
                EmoticonEntity(15, "((ΦωΦ))", false),
                EmoticonEntity(15, "(*ΦωΦ*)", false),
                EmoticonEntity(15, "(=ΦｴΦ=)", false),
                EmoticonEntity(15, "(ΦωΦ)", false),
                EmoticonEntity(15, "(ΦзΦ)", false),
                EmoticonEntity(15, "(Ф∀Ф)", false),
                EmoticonEntity(15, "(ФДФ)", false),
                EmoticonEntity(15, "（三ФÅФ三）", false),
                EmoticonEntity(15, "<(*ΦωΦ*)>", false),
                EmoticonEntity(15, "|ΦωΦ|", false),
                EmoticonEntity(15, "ヾ(*ΦωΦ)ﾉ", false),
                EmoticonEntity(15, "٩(ↀДↀ)۶", false),
                EmoticonEntity(15, "(ↀДↀ)✧", false),
                EmoticonEntity(15, "(ↀДↀ)", false),
                EmoticonEntity(15, "(ↀДↀ)⁼³₌₃", false),
                EmoticonEntity(15, "(=ↀωↀ=)✧", false),
                EmoticonEntity(15, "(๑ↀᆺↀ๑)✧", false),
                EmoticonEntity(15, "(=ↀωↀ=)", false),
                EmoticonEntity(15, "(●ↀωↀ●)", false),
                EmoticonEntity(15, "(๑ↀᆺↀ๑)", false),
                EmoticonEntity(15, "ლ(=ↀωↀ=)ლ", false),
                EmoticonEntity(15, "ლ(●ↀωↀ●)ლ", false),
                EmoticonEntity(15, "^ↀᴥↀ^", false),
                EmoticonEntity(15, "～((Φ◇Φ)‡", false),
                EmoticonEntity(15, "ヽ(ΦωΦヽ)", false),
                EmoticonEntity(15, "(ﾉΦωΦ)ﾉ", false),
                EmoticonEntity(15, "(ΦωΦσ)σ", false),
                EmoticonEntity(15, "]*ΦωΦ)ノ", false),
                EmoticonEntity(15, "(*Φ皿Φ*)", false),
                EmoticonEntity(15, "（ФоФ)", false),
                EmoticonEntity(15, "(=ΦÅΦ=)", false),
                EmoticonEntity(15, "ฅ(*ΦωΦ*) ฅ", false),
                EmoticonEntity(15, "(ﾉ*ФωФ)ﾉ", false),
                EmoticonEntity(15, "(^-人-^)", false),
                EmoticonEntity(15, "(^・ω・^ )", false),
                EmoticonEntity(15, "(=;ェ;=)", false),
                EmoticonEntity(15, "(=^-ω-^=)", false),
                EmoticonEntity(15, "(=^･ω･^)y＝", false),
                EmoticonEntity(15, "~(=^‥^)_旦~", false),
                EmoticonEntity(15, "ヽ(^‥^=ゞ)", false),
                EmoticonEntity(15, "b(=^‥^=)o", false),
                EmoticonEntity(15, "=＾● ⋏ ●＾=", false),
                EmoticonEntity(15, "｡＾･ｪ･＾｡", false),
                EmoticonEntity(15, "( ^..^)ﾉ", false),
                EmoticonEntity(15, "(・∀・)", false),
                EmoticonEntity(15, "(.=^・ェ・^=)", false),
                EmoticonEntity(15, "((≡^⚲͜^≡))", false),
                EmoticonEntity(15, "(^･o･^)ﾉ”", false),
                EmoticonEntity(15, "(^._.^)ﾉ", false),
                EmoticonEntity(15, "(^人^)", false),
                EmoticonEntity(15, "(=；ェ；=)", false),
                EmoticonEntity(15, "(=｀ω´=)", false),
                EmoticonEntity(15, "(=｀ェ´=)", false),
                EmoticonEntity(15, "（=´∇｀=）", false),
                EmoticonEntity(15, "(=^･^=)", false),
                EmoticonEntity(15, "(=^･ｪ･^=)", false),
                EmoticonEntity(15, "(=^‥^=)", false),
                EmoticonEntity(15, "(=ＴェＴ=)", false),
                EmoticonEntity(15, "(=ｘェｘ=)", false),
                EmoticonEntity(15, "＼(=^‥^)/’`", false),
                EmoticonEntity(15, "~(=^‥^)/", false),
                EmoticonEntity(15, "└(=^‥^=)┐", false),
                EmoticonEntity(15, "ヾ(=ﾟ･ﾟ=)ﾉ", false),
                EmoticonEntity(15, "ヽ(=^･ω･^=)丿", false),
                EmoticonEntity(15, "d(=^･ω･^=)b", false),
                EmoticonEntity(15, "o(^・x・^)o", false),
                EmoticonEntity(15, "V(=^･ω･^=)v", false),
                EmoticonEntity(15, "(⁎˃ᆺ˂)", false),
                EmoticonEntity(15, "(,,^・⋏・^,,)", false),
                EmoticonEntity(15, "(ะ^・ω・^ะ)", false),
                EmoticonEntity(15, "(ะ`・ω・´ะ)", false),
                EmoticonEntity(15, "ฅ(≚ᄌ≚)", false),
                EmoticonEntity(15, "(≚ᄌ≚)ƶƵ", false),
                EmoticonEntity(15, "(≚ᄌ≚)ℒℴѵℯ❤", false),
                EmoticonEntity(15, "(^･ｪ･^)", false),
                EmoticonEntity(15, "(^-x-^*)", false),
                EmoticonEntity(15, "σ((=ﾟｴﾟ=))", false),
                EmoticonEntity(15, "((≡ﾟ♀ﾟ≡))", false),
                EmoticonEntity(15, "(=^･ｪ･^=))ﾉ彡☆", false),
                EmoticonEntity(15, "（（≡￣♀￣≡））", false),
                EmoticonEntity(15, "~(=^‥^)ノ☆", false),
                EmoticonEntity(15, "(^･ω･^=)~", false),
                EmoticonEntity(15, "┌(=^‥^=)┘", false),
                EmoticonEntity(15, "┌(=^‥^=)┐", false),
                EmoticonEntity(15, "└(=^‥^=)┘", false),
                EmoticonEntity(15, "(^･o･^)ﾉ”", false),
                EmoticonEntity(15, "(=･ｪ･=?", false),
                EmoticonEntity(15, "ﾍ(^･･^=)~", false),
                EmoticonEntity(15, "(´pゝω･)", false),
                EmoticonEntity(15, "ﾍ(=^･ω･^= )ﾉ", false),
                EmoticonEntity(15, "=^∇^*=", false),
                EmoticonEntity(15, "~(=^–^)", false),
                EmoticonEntity(15, "v(=∩_∩=)", false),
                EmoticonEntity(15, "o(=´∇｀=)o", false),
                EmoticonEntity(15, "|n＾ω＾|η", false),
                EmoticonEntity(15, "(o^‥^)o", false),
                EmoticonEntity(15, "(＾*･.･*＾)", false),
                EmoticonEntity(15, "~(=^┬ ┬^)", false),
                EmoticonEntity(15, "o(^・x・^)w", false),
                EmoticonEntity(15, "ω(=＾・＾=)ω", false),
                EmoticonEntity(15, "(^=˃ᆺ˂)", false),
                EmoticonEntity(15, "=( ^>w< ^)=", false),
                EmoticonEntity(15, "( =①ω①=)", false),
                EmoticonEntity(15, "=’①。①’=", false),
                EmoticonEntity(15, "(*✧×✧*)", false),
                EmoticonEntity(15, "(ꀄꀾꀄ)", false),
                EmoticonEntity(15, "(✦థ ｪ థ)", false),
                EmoticonEntity(15, "=ộ⍛ộ=", false),
                EmoticonEntity(15, "(ꅈꇅꅈ)", false),
                EmoticonEntity(15, "ಠಿ ˑ̫ ಠಿ", false),
                EmoticonEntity(15, "ʘ̥ꀾʘ̥", false),
                EmoticonEntity(15, "(⌯⊙⍛⊙)", false),
                EmoticonEntity(15, "චᆽච", false),
                EmoticonEntity(15, "(ꏨ º̖̫º̖̫ ꏨ)", false),
                EmoticonEntity(15, "((≡ຶ⚲͜≡ຶ))", false),
                EmoticonEntity(15, "( ⓛ ω ⓛ *)", false),
                EmoticonEntity(15, "ଲ( ⓛ ω ⓛ *)ଲ", false),
                EmoticonEntity(15, "ὃ⍜ὅ", false),
                EmoticonEntity(15, "(ㅇㅅㅇ❀)", false),
                EmoticonEntity(15, "ㅇㅅㅇ", false),
                EmoticonEntity(15, "[^._.^]ﾉ彡", false),
                EmoticonEntity(15, "โ๏∀๏ใ", false),
                EmoticonEntity(15, "⋆ටᆼට⋆", false),
                EmoticonEntity(15, "ऴिाी", false),
                EmoticonEntity(15, "ि०॰०ॢी", false),
                EmoticonEntity(15, "ଲ(⁃̗̀̂❍⃓ˑ̫❍⃓⁃̠́̂)ଲ", false),
                EmoticonEntity(15, "=^._.^= ∫", false),
                EmoticonEntity(15, "] ‘͇̂•̩̫’͇̂ ͒)ฅ ﾆｬ❣", false),
                EmoticonEntity(15, "(ٛ₌டுͩ ˑ̭ டுͩٛ₌)ฅ", false),
                EmoticonEntity(15, "₍˄ุ.͡˳̫.˄ุ₎ฅ˒˒", false),
                EmoticonEntity(15, "✩⃛( ͒ ु•·̫• ू ͒)", false),
                EmoticonEntity(15, "( ͒ ु- •̫̮ – ू ͒)", false),
                EmoticonEntity(15, "ฅ(⌯͒• ɪ •⌯͒)ฅ❣", false),
                EmoticonEntity(15, "ฅ⃛(⌯͒꒪ั ˑ̫ ꒪ั ⌯͒) ﾆｬｯ❣", false),
                EmoticonEntity(15, "(ٛ⁎꒪̕ॢ ˙̫ ꒪ٛ̕ॢ⁎)", false),
                EmoticonEntity(15, "( ͒ ˘̩̩̩̩̩̩ꇵ͒˘̩̩̩̩̩̩ ͒)", false),
                EmoticonEntity(15, "ฅ ̂⋒ิ ˑ̫ ⋒ิ ̂ฅ", false),
                EmoticonEntity(15, "ฅ( ͒ᵕ̳ωᵕ̳ ͒)｡o○", false),
                EmoticonEntity(15, "˚₊✩‧₊(⌯͒o̶̶̷̤ ꀾ o̴̶̷̤⌯͒)* ✩‧₊˚", false),
                EmoticonEntity(15, "(⌯͒ᵕɪᵕ⌯͒)zzZ", false),
                EmoticonEntity(15, "₍˄⌓⃘ ˳̫̬ ⌓⃘˄₎ค˒˒", false),
                EmoticonEntity(15, "✧ٛ˃̶̨̡˙ˣੰ͚˙͚ٛ˂̶̧̢༿˒˒", false),
                EmoticonEntity(15, "₍ ̂ˑ̫̈̄ ̂₎", false),
                EmoticonEntity(15, "( ‘͇̂•̩̫’͇̂ )ﾆｬ-♡", false),
                EmoticonEntity(15, "(ꃋิꎴꃋิ)", false),
                EmoticonEntity(15, "(⌯꒪͒ ૢ࿄ ૢ꒪͒)", false),
                EmoticonEntity(15, "(ꃪꄳꃪ)", false),
                EmoticonEntity(15, "(ٛɲ′᷄ ˑ̣̮ ‵᷅ٛɳ)՞", false),
                EmoticonEntity(15, "ʕ⌯˃ꎤु˂⌯ʔ⌕", false),
                EmoticonEntity(15, "ᖇ(( ͇ꆨ ꉴ ꉺ ͇))ᖆ≈ᘊ", false),
                EmoticonEntity(15, "♡͙♡͚₍⸉ॢ⸍͕͈ ˕̫ ⸌͔͈⸊ॢ₎♡͚♡͙", false),
                EmoticonEntity(15, "₍꒵꒱′͈ॢㅈ‵͈ॢ꒰꒵₎*·✧", false),
                EmoticonEntity(15, "ฅ(⌯͒•ꈊ͒ू •⌯͒)", false),
                EmoticonEntity(15, "₍˄·͈༝·͈˄₎◞ ̑̑ෆ⃛", false),
                EmoticonEntity(15, "₍˄·͈༝·͈˄₎ฅ˒˒", false),
                EmoticonEntity(15, "(ृ˄·͈༝·͈˄ ृ )", false),
                EmoticonEntity(15, "(ृʾ́꒳ʿ̀ ृ　)ु", false),
                EmoticonEntity(15, "₍ᵔ·͈༝·͈ᵔ₎", false),
                EmoticonEntity(15, "(˙̂·̫ॅ˙̂)", false),
                EmoticonEntity(15, "꒰⌯͒•ɷ•⌯͒꒱ฅ", false),
                EmoticonEntity(15, "ৎˊ͈ˣੰૢˋ͈ॢॽ∗｡", false),
                EmoticonEntity(15, "♡ॢ₍⸍⸌̣ʷ̣̫⸍̣⸌₎", false),
                EmoticonEntity(15, "˓˓ฅ₍˄ุ.͡ ̫.˄ุ₎ฅ˒˒", false),
                EmoticonEntity(15, "₍˄·͈༝·͈˄*₎◞ ̑̑", false),
                EmoticonEntity(15, "|˄·͈༝·͈˄₎.｡oO", false),
                EmoticonEntity(15, "ฅ^•ﻌ•^ฅ", false),
                EmoticonEntity(15, "ฅ⁽͑ ˚̀ ˙̭ ˚́ ⁾̉ฅ", false),
                EmoticonEntity(15, "ฅ ̳͒•ˑ̫• ̳͒ฅ♡", false),
                EmoticonEntity(15, "ฅ(⌯͒• ɪ •⌯͒)ฅnya～ﾝ❣", false),
                EmoticonEntity(15, "˓˓ก₍⸍⸌̣ʷ̣̫⸍̣⸌₎ค˒˒", false),
                EmoticonEntity(15, "(ฅ•.•ฅ)", false),
                EmoticonEntity(15, "ฅ(*°ω°*ฅ)", false),
                EmoticonEntity(15, "◥(ฅº￦ºฅ)◤", false),
                EmoticonEntity(15, "(´ฅω•ฅ｀)", false),
                EmoticonEntity(15, "ฅ(˘ω˘ )ฅ", false),
                EmoticonEntity(15, "ฅ(⌯͒•̩̩̩́ ˑ̫ •̩̩̩̀⌯͒)ฅ", false),
                EmoticonEntity(15, "ฅ( ̳͒ᵕ ˑ̫ ᵕ ̳͒)ฅ", false),
                EmoticonEntity(15, "ฅ(⌯͒⚭̈́ ˑ̫ ⚭̈́⌯͒)ฅ", false),
                EmoticonEntity(15, "❣ฅ(⌯͒▾ ˑ̫ ▾⌯͒)ฅ", false),
                EmoticonEntity(15, "ฅ⃛(⌯͒▾ ˑ̫ ▾⌯͒)ฅ⃛", false),
                EmoticonEntity(15, "ฅ(三´ ͡ (ェ)´ ͡ 三)ฅ", false),
                EmoticonEntity(15, "ฅ(۩۞ω۞۩) ฅ", false),
                EmoticonEntity(15, "(ฅ^･ω･^ ฅ)", false),
                EmoticonEntity(15, "ฅ(´-ω-`)ฅ", false),
                EmoticonEntity(15, "~(=^･ω･^)ﾍ >ﾟ)))彡", false),
                EmoticonEntity(15, "~(=^･･^)ﾉ>ﾟ)##)彡", false),
                EmoticonEntity(15, "~(=^･･^)ﾍ >ﾟ)))彡", false),
                EmoticonEntity(15, "₍˄·͈༝·͈˄*₎◞ ̑̑❤️くコ:≡", false),
                EmoticonEntity(15, "₍˄·͈༝·͈˄*₎◞ ̑̑ᗦ↞◃", false),
                EmoticonEntity(15, "~(=^･･^)_旦~ (ﾟoﾟ;)", false),
                EmoticonEntity(15, "ｰ8-(^._.^)ﾉ☆( _ _).oO", false),
                EmoticonEntity(15, "~(=^‥^)ﾉ◎～", false),
                EmoticonEntity(15, "┫o(^‥^=)~ ~(=^‥^)o┳", false),
                EmoticonEntity(15, "ε=ε=((( ^-x-^)ﾉ", false),
                EmoticonEntity(15, "ε=ε=ε=ヾ(э^・ｪ・^)э", false),
                EmoticonEntity(15, "0( =^･_･^)=〇", false),
                EmoticonEntity(15, "~(=^･ω･^)ヾ(^^ )", false),
                EmoticonEntity(15, "ヾ(=^・ｪ・^)ヾ(^^ )", false),
                EmoticonEntity(15, "ヾ(=^・・^)ヾ(^^ )", false),
                EmoticonEntity(15, "┏━o(=´∇｀=)o━┓", false),
                EmoticonEntity(15, "目=ﾍ(=^･ω･^)", false),
                EmoticonEntity(15, "~□Pヘ(^‥^=)~", false),
                EmoticonEntity(15, "~(=^‥^)_｡", false),
                EmoticonEntity(15, "~(=^･ω･^)ﾉ◎～", false),
                EmoticonEntity(15, "(*･∀･)／(=^・^=)", false),
                EmoticonEntity(15, "○)))ﾍ(^･･^=)~", false),
                //DOGS
                EmoticonEntity(16, "◖⚆ᴥ⚆◗", false),
                EmoticonEntity(16, "⎩ ♨ᴥ♨ ⎭", false),
                EmoticonEntity(16, "-ᄒᴥᄒ-", false),
                EmoticonEntity(16, "[⑇◍ᴥ◍•⑇]", false),
                EmoticonEntity(16, "(ノ ̿ ̿ᴥ ̿ ̿)ノ", false),
                EmoticonEntity(16, "୧༼◕ ᴥ ◕༽୨", false),
                EmoticonEntity(16, "ᕙ༼◕ ᴥ ◕༽ᕗ", false),
                EmoticonEntity(16, "(_/¯⊘_ᴥ_⊘)_/¯", false),
                EmoticonEntity(16, "⊆ↂᴥↂ⊇", false),
                EmoticonEntity(16, "⎰≀.⎔ᴥ⎔≀⎰", false),
                EmoticonEntity(16, "⊂▶ᴥ◀⊃", false),
                EmoticonEntity(16, "°˖✧◝(ਠᴥਠ)◜✧˖°", false),
                EmoticonEntity(16, "(っ⊂•⊃_ᴥ_⊂•⊃)っ", false),
                EmoticonEntity(16, "●ᴥ●", false),
                EmoticonEntity(16, "ヽ(°ᴥ°)ﾉ", false),
                EmoticonEntity(16, "└(°ᴥ°)┘", false),
                EmoticonEntity(16, "┏(°ᴥ°)┓", false),
                EmoticonEntity(16, "へ║ ◉ ᴥ ◉ ║〜", false),
                EmoticonEntity(16, "乁[ ◕ ᴥ ◕ ]ㄏ", false),
                EmoticonEntity(16, "(‷\\(ᓄ ᴥ ᓇ)/‴)", false),
                EmoticonEntity(16, "▐ ☯ ᴥ ☯ ▐", false),
                EmoticonEntity(16, "໒( ̿ ᴥ ̿ )७", false),
                EmoticonEntity(16, "໒( ◉ ᴥ ◉ )७", false),
                EmoticonEntity(16, "| * O ᴥ O * |", false),
                EmoticonEntity(16, "٩། ಠ ᴥ ಠ །ᕗ", false),
                EmoticonEntity(16, "୧╏ ~ ᴥ ~ ╏୨", false),
                EmoticonEntity(16, "⋋〳 ￣ ᴥ ￣ 〵⋌", false),
                EmoticonEntity(16, "╏ ◯ ᴥ ◯ ╏", false),
                EmoticonEntity(16, "੧〳 ˵ ಠ ᴥ ಠ ˵ 〵ノ⌒.", false),
                EmoticonEntity(16, "( ͡° ᴥ ͡°)", false),
                EmoticonEntity(16, "…(๑╯ﻌ╰๑)=3", false),
                EmoticonEntity(16, "୧| ⁰ ᴥ ⁰ |୨", false),
                EmoticonEntity(16, "໒(◉ᴥ◉)७", false),
                EmoticonEntity(16, "ᘳ´• ᴥ •`ᘰ", false),
                EmoticonEntity(16, "⁞ ✿ ᵒ̌ ᴥ ᵒ̌ ✿ ⁞", false),
                EmoticonEntity(16, "Ψ(●°̥̥̥̥̥̥̥̥ ཅ °̥̥̥̥̥̥̥̥●)Ψ", false),
                //FIGHT
                EmoticonEntity(17, "(๑و•̀ω•́)و", false),
                EmoticonEntity(17, "(ง •̀_•́)ง", false),
                EmoticonEntity(17, "‾͟͟͞(((ꎤˋ⁻̫ˊ)—̳͟͞͞o", false),
                EmoticonEntity(17, "꒰๑͒•̀ुꇵ͒•꒱و ̑̑", false),
                EmoticonEntity(17, "ʕง•ᴥ•ʔง", false),
                EmoticonEntity(17, "༼ ᓄºل͟º ༽ᓄ", false),
                EmoticonEntity(17, "(ง⌐□ل͜□)ง", false),
                EmoticonEntity(17, "(งಠل͜ಠ)ง", false),
                EmoticonEntity(17, "(ᓄಠ_ಠ)ᓄ", false),
                EmoticonEntity(17, "ᕙ(° ͜ಠ ͜ʖ ͜ಠ°)ᓄ", false),
                EmoticonEntity(17, "(ง ͡ʘ ͜ʖ ͡ʘ)ง", false),
                EmoticonEntity(17, "(งಠ_ಠ)ง", false),
                EmoticonEntity(17, "(ง ° ͜ ʖ °)ง", false),
                EmoticonEntity(17, "(ง’̀-‘́)ง", false),
                EmoticonEntity(17, "(́ง◉◞౪◟◉‵)ง", false),
                EmoticonEntity(17, "( ง ͡°╭ ͟ʖ╮͡° ) ง", false),
                EmoticonEntity(17, "(ง ͠° ͟ل͜ ͡°)ง", false),
                EmoticonEntity(17, "(ง ͠° ͟ʖ ͡°)ง", false),
                EmoticonEntity(17, "(ง ͠ ͠° ل͜ °)ง", false),
                EmoticonEntity(17, "(ง ͠° ͟ʖ #)ง", false),
                EmoticonEntity(17, "(ง •̀ゝ•́)ง", false),
                EmoticonEntity(17, "(⋆ˋ⑉̈ˊ)൭൭⁼³₌₃", false),
                EmoticonEntity(17, "(ง°ل͜°)ง", false),
                EmoticonEntity(17, "(૭ ఠ༬ఠ)૭", false),
                EmoticonEntity(17, "0( =^･_･^)=〇", false),
                EmoticonEntity(17, "༼ง=ಠ益ಠ=༽ง", false),
                EmoticonEntity(17, "Ｃ≡(・。・Ｃ≡)≡≡≡", false),
                EmoticonEntity(17, "(೨♛‿♛೨)", false),
                EmoticonEntity(17, "★o(･д´･+)９”", false),
                EmoticonEntity(17, "((งง •̀•̀__•́•́))งง", false),
                EmoticonEntity(17, "༼ง ◉_◉༽ง", false),
                EmoticonEntity(17, "༼ ᕤ◕◡◕ ༽ᕤ", false),
                EmoticonEntity(17, "༼ง’̀-‘́༽ง", false),
                EmoticonEntity(17, "༼ง ͠ຈ ͟ل͜ ͠ຈ༽ง", false),
                EmoticonEntity(17, "୧༼◔益◔୧ ༽", false),
                EmoticonEntity(17, "ᕙﾉ•̀ʖ•́ﾉ୨", false),
                EmoticonEntity(17, "୧▐ ್ ﹏ ್ ▐୨", false),
                EmoticonEntity(17, "=͟͟͞͞(งꏿ᷅॓৺ꏿ᷄॔)ง⁼³₌₃", false),
                EmoticonEntity(17, "‾͟͟͞(((ꎤ๑‾᷅༬‾᷄๑)̂—̳͟͞͞o", false),
                EmoticonEntity(17, "Q–(’̀-’̀Q )", false),
                EmoticonEntity(17, "Q–(’̀-’̀Q )", false),
                EmoticonEntity(17, "ϱ(`ન̇´)⁼³̳", false),
                EmoticonEntity(17, "|ง།°╭͜ʖ╮°།|ง", false),
                EmoticonEntity(17, "╾━╤デ╦︻", false),
                EmoticonEntity(17, "▄︻̷̿┻̿═━一", false),
                EmoticonEntity(17, "︻╦̵̵͇̿̿̿̿══╤─", false),
                EmoticonEntity(17, "⌐╦╦═─", false),
                EmoticonEntity(17, "̿̿ ̿̿ ̿’̿’̵͇̿̿з=༼ ▀̿̿Ĺ̯̿̿▀̿ ̿ ༽", false),
                EmoticonEntity(17, "━╤デ╦︻(▀̿̿Ĺ̯̿̿▀̿ ̿)", false),
                EmoticonEntity(17, "(⌐■_■)–︻╦╤─", false),
                EmoticonEntity(17, "༼ ಠل͟ಠ༽ ̿ ̿ ̿ ̿’̿’̵з=༼ຈل͜ຈ༽ﾉ", false),
                EmoticonEntity(17, "̿’ ̿’\\̵͇̿̿\\з=(ಡل͟ಡ)=ε/̵͇̿̿/’̿’̿", false),
                EmoticonEntity(17, "￢o(￣-￣ﾒ)", false),
                EmoticonEntity(17, "(҂`з´).っ︻デ═一", false),
                EmoticonEntity(17, "ᕕ╏ ͡ᵔ ‸ ͡ᵔ ╏و︻̷┻̿═━一", false),
                EmoticonEntity(17, "[ﾉಠೃಠ]︻̷┻̿═━一", false),
                EmoticonEntity(17, "……┳┓o(▼▼ｷ)", false),
                EmoticonEntity(17, "(ｷ▼▼)o┏┳……", false),
                EmoticonEntity(17, "̿̿’̿’\\̵͇̿̿\\=(•̪●)=/̵͇̿̿/’̿̿ ̿ ̿ ̿", false),
                EmoticonEntity(17, "ξ(✿ ❛‿❛)ξ▄︻┻┳═一", false),
                EmoticonEntity(17, "⁞ つ: •̀ ⌂ •́ : ⁞-︻╦̵̵͇̿̿̿̿══╤─", false),
                EmoticonEntity(17, "┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿ └། ๑ _ ๑ །┘", false),
                EmoticonEntity(17, "(‥)←￢~(▼▼#)~~", false),
                EmoticonEntity(17, "‘̿’\\̵͇̿̿\\=( `◟ 、)=/̵͇̿̿/’̿̿ ̿", false),
                EmoticonEntity(17, "༼ ºل͟º ༽ ̿ ̿ ̿ ̿’̿’̵з=༼ ▀̿Ĺ̯▀̿ ̿ ༽", false),
                EmoticonEntity(17, "(キ▼▼)＿┏┳……", false),
                EmoticonEntity(17, "( ͝ಠ ʖ ಠ)=ε/̵͇̿̿/’̿’̿ ̿", false),
                EmoticonEntity(17, "ლ(~•̀︿•́~)つ︻̷┻̿═━一", false),
                EmoticonEntity(17, "(ง ͠° / ^ \\ °)-/̵͇̿̿/’̿’̿ ̿", false),
                EmoticonEntity(17, "(‘ºل͟º)ノ⌒. ̿̿ ̿̿ ̿’̿’̵͇̿̿з=༼ ▀̿̿Ĺ̯̿̿▀̿ ̿ ༽", false),
                EmoticonEntity(17, "(∩ ͡ ° ʖ ͡ °) ⊃-(===>", false),
                EmoticonEntity(17, "ヽ༼ಥل͟ಥ༽¤=[]:::::>", false),
                EmoticonEntity(17, "¯\\_( ͡° ͜ʖ ͡°)ง-]—-", false),
                EmoticonEntity(17, "(ง ͠ ᵒ̌ Дᵒ̌)¤=[]:::::>", false),
                EmoticonEntity(17, "(ง ͠° ͟ل͜ ͡°)¤=[]:::::>", false),
                EmoticonEntity(17, "ᗜಠ o ಠ)¤=[]:::::>", false),
                EmoticonEntity(17, "(ﾒ▼へ▼)ﾉ0=|⊃―", false),
                EmoticonEntity(17, "੧| ⊗ ▾ ⊗ |⊃¤=(————-", false),
                EmoticonEntity(17, "╰༼.◕ヮ◕.༽つ¤=[]————", false),
                EmoticonEntity(17, "———–[]=¤ԅ༼ ･ 〜 ･ ༽╯", false),
                EmoticonEntity(17, "ᕦ[ •́ ﹏ •̀ ]⊃¤=[]::::::::>", false),
                EmoticonEntity(17, "(*ﾟ∀ﾟ)つ＝lニニフ", false),
                EmoticonEntity(17, "༼ง ͠ຈ ͟ل͜ ͠ຈ༽o:[]:::::::>", false),
                EmoticonEntity(17, "ᕙ༼◕ل͜◕༽つ¤=[]:::::>", false),
                EmoticonEntity(17, "<:::::[]=¤༼ຈل͜ຈ༽ﾉ", false),
                EmoticonEntity(17, "╰༼⇀︿⇀༽つ-]═──", false),
                EmoticonEntity(17, "(つ･･)つ¤=[]:::::::>", false),
                EmoticonEntity(17, "༼ຈل͜ຈ༽ﾉ¤=[]:::::>", false),
                EmoticonEntity(17, "~~~~~~~[]=¤ԅ໒( ☯ ᗜ ☯ )७ᕗ", false),
                EmoticonEntity(17, "c:::::::::::::[]=¤ԅ╏ ˵ ⊚ ◡ ⊚ ˵ ╏┐", false),
                EmoticonEntity(17, "─=≡Σ((( つ◕ل͜◕)つ¤=[]:::::>", false),
                EmoticonEntity(17, "ᕙ╏✖۝✖╏⊃-(===>", false),
                EmoticonEntity(17, "(　´,_ゝ｀)つ━╂──( ﾟ∀ﾟ)─", false),
                EmoticonEntity(17, "∩༼˵☯‿☯˵༽つ¤=[]:::::>", false),
                EmoticonEntity(17, "༼ຈل͜ຈ༽▬▬ι═══════ﺤ", false),
                EmoticonEntity(17, "(╯°□°)ຈ҉̛༽̨҉҉ﾉ̨", false),
                EmoticonEntity(17, "*~● ))))o(･.･;)", false),
                EmoticonEntity(17, "( ･_･)ﾉ⌒●~*", false),
                EmoticonEntity(17, "( ・_・)ノΞ●~*", false),
                EmoticonEntity(17, "ヾ(;ﾟ⊿ﾟ)ﾉ *～●…", false),
                EmoticonEntity(17, "*~( ///// )ヽ(ﾟﾛﾟ)ﾉ", false),
                EmoticonEntity(17, "●~*⌒☆＼_(–* )", false),
                EmoticonEntity(17, "(o･_･)_……………….●~*", false),
                EmoticonEntity(17, "(ノ^-^)ノ ⌒ ●~*●~*", false),
                EmoticonEntity(17, "!!( ･_･)r鹵~<巛巛巛", false),
                EmoticonEntity(17, "（　＾）／占~~~~~", false),
                EmoticonEntity(17, "( ﾟДﾟ)ﾉ占~<巛巛巛", false),
                //HIDE
                EmoticonEntity(18, "┬┴┬┴┤(･_├┬┴┬┴", false),
                EmoticonEntity(18, "┻┳|･ω･)", false),
                EmoticonEntity(18, "┻┳|･ω･)ﾉﾉ", false),
                EmoticonEntity(18, "(ʘ ل͟├┬┴┬┴", false),
                EmoticonEntity(18, "(☯‿├┬┴┬┴", false),
                EmoticonEntity(18, "( ͡°╭ ͟ʖ╮͡├┬┴┬┴", false),
                EmoticonEntity(18, "ԅ[ •́ ﹏├┬┴┬┴", false),
                EmoticonEntity(18, "ᕦ༼ ºººل͟ºº├┬┴┬┴", false),
                EmoticonEntity(18, "┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴", false),
                EmoticonEntity(18, "༼ຈل͜├┬┴┬┴", false),
                EmoticonEntity(18, "川o･-･)ﾉ", false),
                EmoticonEntity(18, ")Д⊙`)", false),
                EmoticonEntity(18, "‾̠̠̠̠̠̠̠̄| ॣ•͈̀๑)", false),
                EmoticonEntity(18, "|　|д･)", false),
                EmoticonEntity(18, "░ฺ|◕ฺΘ◕ฺ)ノ", false),
                //CRAZY
                EmoticonEntity(19, "ヘ（。□°）ヘ", false),
                EmoticonEntity(19, "(☉ε　⊙ﾉ)ﾉ", false),
                EmoticonEntity(19, "＼(●o○;)ノ", false),
                EmoticonEntity(19, "＼(☆o◎)／", false),
                EmoticonEntity(19, "⁀⊙﹏☉⁀", false),
                EmoticonEntity(19, "¯\\(°_o)/¯", false),
                EmoticonEntity(19, "~(๑ñ﹏ ⊙☆)ノ", false),
                EmoticonEntity(19, "ヾ (✿＞﹏ ⊙〃)ノ", false),
                EmoticonEntity(19, "ヽ(。_°)ノ", false),
                EmoticonEntity(19, "ヽ(｡ゝω・｡)ﾉ", false),
                EmoticonEntity(19, "ヾ(｡ꏿ﹏ꏿ)ﾉﾞ", false),
                EmoticonEntity(19, "ヽ(‘ ∇‘ )ノ", false),
                EmoticonEntity(19, "ヾ(@゜∇゜@)ノ", false),
                EmoticonEntity(19, "ヾ(@°▽°@)ノ", false),
                EmoticonEntity(19, "ヽ(゜Q。)ノ", false),
                EmoticonEntity(19, "Σ(♡＠﹏ ＠☆)ﾉ”", false),
                EmoticonEntity(19, "щ (*ㅇ△ Φ☆)ノ", false),
                EmoticonEntity(19, "へ(゜∇、°)へ", false),
                EmoticonEntity(19, "ヘ（゜◇、゜）ノ", false),
                EmoticonEntity(19, "ヘ(゜Д、゜)ノ", false),
                EmoticonEntity(19, "ヘ(°◇、°)ノ", false),
                EmoticonEntity(19, "ミ●﹏☉ミ", false),
                EmoticonEntity(19, "⁽⁽◝(ˊʂ˴⁎)◞՞", false),
                EmoticonEntity(19, "ヽ(°▽、°)ﾉ", false),
                EmoticonEntity(19, "(ლ ۞ิ ჴ ۞ิ)ლ", false),
                EmoticonEntity(19, "(/●◔∀◐●)/", false),
                EmoticonEntity(19, "ヾ|`･､●･|ﾉ", false),
                EmoticonEntity(19, "(ノ)ʘ﹃ʘ(ヾ)", false),
                EmoticonEntity(19, "＼(´◓Д◔`)／", false),
                EmoticonEntity(19, "◝₍ᴑ̑ДO͝₎◞", false),
                EmoticonEntity(19, "(╯⊙ ⊱⊙╰ )", false),
                EmoticonEntity(19, "੧| ⊗ ▾ ⊗ |୨", false),
                EmoticonEntity(19, "⊂(©෴©)つ", false),
                EmoticonEntity(19, "ゞ(ↂ ω ↂ)ゞ", false),
                EmoticonEntity(19, "ﾍ(ﾟ∇ﾟﾍ)", false),
                EmoticonEntity(19, "(⑅ 「O_o)「", false),
                EmoticonEntity(19, "(⑅∫°ਊ°)∫", false),
                EmoticonEntity(19, "ヽ(๏∀◕ )ﾉ", false),
                EmoticonEntity(19, "へ[ ᴼ ▃ ᴼ ]_/¯", false),
                EmoticonEntity(19, "(｡□ﾟﾉ)ﾉ", false),
                EmoticonEntity(19, "Σ(+Oдo;艸;)", false),
                EmoticonEntity(19, "⁽⁽◝(∗ ❛⃘ ꒫ ❜⃘⃘ ∗)◜⁾⁾", false),
                EmoticonEntity(19, "(⊙﹏⊙✿)", false),
                EmoticonEntity(19, "(⊙_◎)", false),
                EmoticonEntity(19, "(♠_♦)", false),
                EmoticonEntity(19, "( ख़ืིڞ◟྄ख़ืི)", false),
                EmoticonEntity(19, "(｡☉౪ ⊙｡)", false),
                EmoticonEntity(19, "(๑꒪͒∀꒪͒๑)", false),
                EmoticonEntity(19, "(ּơ̑ළּơ̑)", false),
                EmoticonEntity(19, "(ʺʘੂ๔̈ੁʘੂ)", false),
                EmoticonEntity(19, "⊙_ʘ", false),
                EmoticonEntity(19, "◴_◶", false),
                EmoticonEntity(19, "◖|◔◡◉|◗", false),
                EmoticonEntity(19, "˛˛(๑ּగ˞ּగ๑) ̉ ̉", false),
                EmoticonEntity(19, "ಠ ּ͜೦", false),
                EmoticonEntity(19, "( ◎⃝⃘∀◎⃝⃘ )", false),
                EmoticonEntity(19, "⊆◍益◍⊇", false),
                EmoticonEntity(19, "(＊☉౪ ⊙｡)", false),
                EmoticonEntity(19, "∑（*☼＿☉*）", false),
                EmoticonEntity(19, "(╬☉д⊙)⊰⊹ฺ", false),
                EmoticonEntity(19, "~(-◎ω◎)", false),
                EmoticonEntity(19, "~(-◎y◎)", false),
                EmoticonEntity(19, "(◎ω◎*)", false),
                EmoticonEntity(19, "( ◎⃝✦⃟ོ◎⃝ )", false),
                EmoticonEntity(19, "(◦△☆)~~!!!", false),
                EmoticonEntity(19, "（͡°͜ʖ͡°）", false),
                EmoticonEntity(19, "(。ヘ°)", false),
                EmoticonEntity(19, "(゜▼゜＊）", false),
                EmoticonEntity(19, "(゜▽゜;)", false),
                EmoticonEntity(19, "`(๑ △ ๑)`*", false),
                EmoticonEntity(19, "(*ﾟ∀ﾟ*)", false),
                EmoticonEntity(19, "(*°∀°)", false),
                EmoticonEntity(19, "ъ川ﾟд^川", false),
                EmoticonEntity(19, "(o≧▽ﾟ)o", false),
                EmoticonEntity(19, "Σ(・A゜)", false),
                EmoticonEntity(19, "┏( .-. ┏ ) ┓", false),
                EmoticonEntity(19, "( ┐΄✹ਊ✹)┐", false),
                EmoticonEntity(19, "σ(●ﾟ┏∀┛｡●)ﾉ", false),
                //SAD
                EmoticonEntity(20, "( ≧Д≦)", false),
                EmoticonEntity(20, "((´д｀))", false),
                EmoticonEntity(20, "(∩︵∩)", false),
                EmoticonEntity(20, "(▰˘︹˘▰)", false),
                EmoticonEntity(20, "(✖╭╮✖)", false),
                EmoticonEntity(20, "(‘A`)", false),
                EmoticonEntity(20, "(︶︹︺)", false),
                EmoticonEntity(20, "(＠´＿｀＠)", false),
                EmoticonEntity(20, "（´＿｀）", false),
                EmoticonEntity(20, "(⊙︿⊙✿)", false),
                EmoticonEntity(20, "(⌣_⌣”)", false),
                EmoticonEntity(20, "(▰︶︹︺▰)", false),
                EmoticonEntity(20, "~(｡☉︵ ಠ@)>", false),
                EmoticonEntity(20, "⊙︿⊙", false),
                EmoticonEntity(20, "ヽ(●ﾟ´Д｀ﾟ●)ﾉﾟ", false),
                EmoticonEntity(20, "(.﹒︣︿﹒︣.)", false),
                EmoticonEntity(20, "(Θ︹Θ)ს", false),
                EmoticonEntity(20, "٩꒰´·⌢•｀꒱۶⁼³₌₃", false),
                EmoticonEntity(20, ":: ˓(ᑊᘩᑊ⁎) ::", false),
                EmoticonEntity(20, "˓˓(ᑊᘩᑊ⁎)", false),
                EmoticonEntity(20, "(๑◕︵◕๑)", false),
                EmoticonEntity(20, "( .. )", false),
                EmoticonEntity(20, "(｡•́︿•̀｡)", false),
                EmoticonEntity(20, "(´°ω°`)", false),
                EmoticonEntity(20, "੨( ･᷄ ︵･᷅ )ｼ", false),
                EmoticonEntity(20, "꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥", false),
                EmoticonEntity(20, "(⌯˃̶᷄ ﹏ ˂̶᷄⌯)ﾟ", false),
                EmoticonEntity(20, "(っ- ‸ – ς)", false),
                EmoticonEntity(20, "(๑′°︿°๑)", false),
                EmoticonEntity(20, "⊛ठ̯⊛", false),
                EmoticonEntity(20, "ಠ╭╮ಠ", false),
                EmoticonEntity(20, "( ◞᷄દ◟᷅ )", false),
                EmoticonEntity(20, "(oꆤ︵ꆤo)", false),
                EmoticonEntity(20, "ಗಾ ﹏ ಗಾ", false),
                EmoticonEntity(20, "ᵟຶᴖ ᵟຶ", false),
                EmoticonEntity(20, "(⋅⃘˕̭⋅⃘)", false),
                EmoticonEntity(20, "ōۃō", false),
                EmoticonEntity(20, "( ⁍᷄⌢̻⁍᷅ )", false),
                EmoticonEntity(20, "(.﹒︠₋﹒︡.)", false),
                EmoticonEntity(20, "(˵¯͒⌢͗¯͒˵)", false),
                EmoticonEntity(20, "☹ै", false),
                EmoticonEntity(20, "(　´_ﾉ` )", false),
                EmoticonEntity(20, "ʕ ಡ ﹏ ಡ ʔ", false),
                EmoticonEntity(20, "●︿●", false),
                EmoticonEntity(20, "(◕︿◕✿)", false),
                EmoticonEntity(20, "ਉ_ਉ", false),
                EmoticonEntity(20, "༶ඬ༝ඬ༶", false),
                EmoticonEntity(20, "(;-_-)/", false),
                EmoticonEntity(20, "(oT-T)尸", false),
                EmoticonEntity(20, "(一。一;;）", false),
                EmoticonEntity(20, "(　-。-)", false),
                EmoticonEntity(20, "(-_＼)", false),
                EmoticonEntity(20, "(;-_-)ノ", false),
                EmoticonEntity(20, "(;*´Д`)ﾉ", false),
                EmoticonEntity(20, "（；￣д￣）", false),
                EmoticonEntity(20, "(。-ω-)ﾉ", false),
                EmoticonEntity(20, "((-_-))", false),
                EmoticonEntity(20, "(@_@)", false),
                EmoticonEntity(20, "(/ _ ; )", false),
                EmoticonEntity(20, "（￣□￣；）", false),
                EmoticonEntity(20, "（~～~）", false),
                EmoticonEntity(20, "（◎ー◎；）", false),
                EmoticonEntity(20, "（ー△ー；）", false),
                EmoticonEntity(20, "(o_ _)o", false),
                EmoticonEntity(20, "(ﾉ_ _)ﾉ", false),
                EmoticonEntity(20, "(ノ#-_-)ノ", false),
                EmoticonEntity(20, "(ﾉ´ｰ`)ﾉ", false),
                EmoticonEntity(20, "(ﾉ￣д￣)ﾉ", false),
                EmoticonEntity(20, "(￣^￣)尸", false),
                EmoticonEntity(20, "/(;-_-)", false),
                EmoticonEntity(20, "＼( ｀.∀´)／", false),
                EmoticonEntity(20, "＼(-___________-;)／", false),
                EmoticonEntity(20, "＼（－－）／", false),
                EmoticonEntity(20, "＼(-o- )", false),
                EmoticonEntity(20, "~(>_<。)＼", false),
                EmoticonEntity(20, "ヾ(-_-;)", false),
                EmoticonEntity(20, "ヽ(｀◇´)/", false),
                EmoticonEntity(20, "o(-_-;*)", false),
                EmoticonEntity(20, "o(╥﹏╥)o", false),
                EmoticonEntity(20, "ƪ(‾_‾)ʃ", false),
                EmoticonEntity(20, "t(-_-t)", false),
                EmoticonEntity(20, "y-(~。~；)", false),
                EmoticonEntity(20, "ヘ(_ _ヘ)", false),
                EmoticonEntity(20, "ﾍ(;´Д｀ﾍ)", false),
                EmoticonEntity(20, "ヘ（´ｏ｀）ヘ", false),
                EmoticonEntity(20, "ﾍ(￣ ￣;ﾍ)", false),
                EmoticonEntity(20, "ヘ(￣ー￣ヘ)", false),
                EmoticonEntity(20, "彡(-_-;)彡", false),
                EmoticonEntity(20, "┌（-.-)┐", false),
                EmoticonEntity(20, "\\(-ㅂ-)/", false),
                EmoticonEntity(20, "t(-.-t)", false),
                EmoticonEntity(20, "Y(-.-Y)", false),
                EmoticonEntity(20, "╭✬⌢✬╮", false),
                EmoticonEntity(20, "ﾍ(-.-ﾍ;)…", false),
                EmoticonEntity(20, "੧(⸍⸓⸌੧)", false),
                EmoticonEntity(20, "ლ（ӨᆸӨ）۳", false),
                EmoticonEntity(20, "˄̞⁽⁽⚑(꒪ͦᴗ̵̍꒪ͦ=͟͟͞͞ ꒪ͦ ˈ̫̮ ꒪ͦ)⚑⁾⁾˄̩̞", false),
                EmoticonEntity(20, "٩(-̃_̮̮̃-̃)۶", false),
                EmoticonEntity(20, "(o尸’▽’)o尸", false),
                EmoticonEntity(20, "(○p>ω<)尸”", false),
                EmoticonEntity(20, "!(*´∀｀*)尸”", false),
                EmoticonEntity(20, "{ﾉ｡⊍_⊍｡}ﾉ", false),
                EmoticonEntity(20, "(oT-T)尸~~", false),
                EmoticonEntity(20, "|┘–|┘~", false),
                EmoticonEntity(20, "└(―_―；)_―；)―；)；))┐", false),
                EmoticonEntity(20, "……┌┤´д`├┐", false),
                EmoticonEntity(20, "o-[･o･]-o尸", false),
                EmoticonEntity(20, "o(- -;*)ゞ", false),
                EmoticonEntity(20, "໒( •́ ∧ •̀ )७", false),
                EmoticonEntity(20, "へ[ •́ ‸ •̀ ]ʋ", false),
                EmoticonEntity(20, "┏༼ ◉ ╭╮ ◉༽┓", false),
                EmoticonEntity(20, "▐ ﹒︣ Ĺ̯ ﹒︣ ▐", false),
                EmoticonEntity(20, "( ˃̶͈ ̯ ̜ ˂̶͈ˊ ) ︠³", false),
                EmoticonEntity(20, "(๑´╹‸╹`๑)", false),
                EmoticonEntity(20, "(⌯˃̶᷄ ﹏ ˂̶᷄⌯)", false),
                EmoticonEntity(20, "（（●´∧｀●））", false),
                EmoticonEntity(20, "(;*△*;)", false),
                EmoticonEntity(20, "（ ; ; ）", false),
                EmoticonEntity(20, "(っ˘̩╭╮˘̩)っ", false),
                EmoticonEntity(20, "(个_个)", false),
                EmoticonEntity(20, "（；へ：）", false),
                EmoticonEntity(20, "o(；△；)o", false),
                EmoticonEntity(20, "((o(;△;)o))", false),
                EmoticonEntity(20, "ͼ(ݓ_ݓ)ͽ", false),
                EmoticonEntity(20, "(*´；ェ；`*)", false),
                EmoticonEntity(20, "(´；ω；`)", false),
                EmoticonEntity(20, "(´；д；`)", false),
                EmoticonEntity(20, "(´；Д；｀)", false),
                EmoticonEntity(20, "(゜´Д｀゜)", false),
                EmoticonEntity(20, "ಥ_ಥ", false),
                EmoticonEntity(20, "(ఠ్ఠ ˓̭ ఠ్ఠ)", false),
                EmoticonEntity(20, "(๑′̥̥̥▵‵̥̥̥ ૂ๑)", false),
                EmoticonEntity(20, "(٭°̧̧̧꒳°̧̧̧٭)", false),
                EmoticonEntity(20, "（ｉДｉ）", false),
                EmoticonEntity(20, "( ´•̥×•̥` )", false),
                EmoticonEntity(20, "( ᵒ̴̶̷̥́ _ᵒ̴̶̷̣̥̀ )", false),
                EmoticonEntity(20, "( ˃̣̣̥ω˂̣̣̥ )", false),
                EmoticonEntity(20, "꒰๑•̥﹏•̥๑꒱", false),
                EmoticonEntity(20, "(੭ ˃̣̣̥ ㅂ˂̣̣̥)੭ु", false),
                EmoticonEntity(20, "( ɵ̥̥ ˑ̫ ɵ̥̥)", false),
                EmoticonEntity(20, "(´;︵;`)", false),
                EmoticonEntity(20, "( ´•̥̥̥ω•̥̥̥` )", false),
                EmoticonEntity(20, "(ˊ̥̥̥̥̥ ³ ˋ̥̥̥̥̥)", false),
                EmoticonEntity(20, "(⌯͒⁍̩̩᷄ ɪ ⁍̩̩᷄ฅ͒)", false),
                EmoticonEntity(20, "(๑ १д१)", false),
                EmoticonEntity(20, "(๑⃙⃘°̧̧̧ㅿ°̧̧̧๑⃙⃘)", false),
                EmoticonEntity(20, "(῭̩̩̩̥ꄗ΅̩̩̩̥)", false),
                EmoticonEntity(20, "(̥ ̥এ́ ̼ এ̥̀)̥̥", false),
                EmoticonEntity(20, "(̥ ̥এ́ ̼ এ̥̀)̥̥੭ੇʓ ੭ੇʓ", false),
                EmoticonEntity(20, "⁝(˚͈͈͈͈̥̆₍₎˚͈͈͈͈̥̆⁎)⁝", false),
                EmoticonEntity(20, "(;﹏;)", false),
                EmoticonEntity(20, "(˃̥̥ω˂̥̥̥)", false),
                EmoticonEntity(20, "( ͒˃̩̩⌂˂̩̩ ͒)", false),
                EmoticonEntity(20, "(ᵕ̣̣̣̣̣̣﹏ᵕ̣̣̣̣̣̣)", false),
                EmoticonEntity(20, "(˃̩̩̥ɷ˂̩̩̥)", false),
                EmoticonEntity(20, "( -̩̩̩͡˛ -̩̩̩͡ )", false),
                EmoticonEntity(20, "(﹡ᵗ ᵔ ᵗ ﹡)", false),
                EmoticonEntity(20, "( ب_ب )", false),
                EmoticonEntity(20, "c〳 ݓ ﹏ ݓ 〵੭", false),
                EmoticonEntity(20, "( Ĭ ^ Ĭ )", false),
                EmoticonEntity(20, "(´;ω;｀)", false),
                EmoticonEntity(20, "(;•͈́༚•͈̀)", false),
                EmoticonEntity(20, "＼（＠；◇；＠）／", false),
                EmoticonEntity(20, "(ﾟ´Д｀ﾟ)ﾟ", false),
                EmoticonEntity(20, "・(/Д`)・", false),
                EmoticonEntity(20, "・゜・(ノД`)", false),
                EmoticonEntity(20, ".·´¯`(>▂<)´¯`·.", false),
                EmoticonEntity(20, "｡：ﾟ(｡ﾉω＼｡)ﾟ･｡", false),
                EmoticonEntity(20, "。：゜(；´∩｀；)゜：。", false),
                EmoticonEntity(20, "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡", false),
                EmoticonEntity(20, "。ﾟ(ﾟﾉД｀ﾟ)ﾟ｡", false),
                EmoticonEntity(20, "｡゜(｀Д´)゜｡", false),
                EmoticonEntity(20, "(ノД`)・゜・。", false),
                EmoticonEntity(20, "˚‧º·(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )‧º·˚", false),
                EmoticonEntity(20, "°(ಗдಗ。)°.", false),
                EmoticonEntity(20, "(/□＼*)・゜", false),
                EmoticonEntity(20, ".°(ಗдಗ。)°.", false),
                EmoticonEntity(20, "｡ﾟ(ﾟ∩´﹏`∩ﾟ)ﾟ｡", false),
                EmoticonEntity(20, "｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡", false),
                EmoticonEntity(20, "‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚", false),
                EmoticonEntity(20, "๐·°(৹˃̵﹏˂̵৹)°·๐", false),
                EmoticonEntity(20, "⋆*:.｡. (-᷄◞८ૄ◟-᷅) .｡.:*⋆", false),
                EmoticonEntity(20, "｡･+ﾟﾟ(うд´｡)ﾟﾟ+･｡", false),
                EmoticonEntity(20, "｡･ﾟ(ﾟ⊃ω⊂ﾟ)ﾟ･｡", false),
                EmoticonEntity(20, "｡･ﾟ･(*ﾉД`*)･ﾟ･。", false),
                EmoticonEntity(20, "ﾟ｡･ﾟヾ(ﾟ｀ｪ´ﾟ)ﾉ｡ﾟ･｡", false),
                EmoticonEntity(20, "｡ﾟヽ(ﾟ´Д｀)ﾉﾟ｡", false),
                EmoticonEntity(20, "｡･ﾟ’(*/益＼*) ‘ﾟ･｡", false),
                EmoticonEntity(20, "｡ﾟ(ﾟ`⊿゜)ﾟ｡", false),
                EmoticonEntity(20, "˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚", false),
                EmoticonEntity(20, "｡ﾟ(ﾟ´Д`ﾟ)ﾟ｡", false),
                EmoticonEntity(20, "｡ﾟ(ﾟ∩´﹏`∩ﾟ)ﾟ｡", false),
                EmoticonEntity(20, "゜．(つx･｡`*)゜．・", false),
                EmoticonEntity(20, "｡ﾟ( ﾟஇ‸இﾟ+)ﾟ｡", false),
                EmoticonEntity(20, "(つ﹏<)･ﾟ｡", false),
                EmoticonEntity(20, "｡ﾟ･（>﹏<）･ﾟ｡", false),
                EmoticonEntity(20, "｡ﾟ(*´□`)ﾟ｡", false),
                EmoticonEntity(20, "｡:ﾟ(;´∩`;)ﾟ:｡", false),
                EmoticonEntity(20, "。･゜･(｡´ﾉω･`)", false),
                EmoticonEntity(20, ".・゜゜・（／。＼）・゜゜・．", false),
                EmoticonEntity(20, "｡･ﾟﾟ･(>д<)･ﾟﾟ･｡", false),
                EmoticonEntity(20, "｡･ﾟﾟ･o（ｉДｉ）o･ﾟﾟ･｡", false),
                EmoticonEntity(20, "(╯︵╰,)", false),
                EmoticonEntity(20, "ヽ(´□｀。)ﾉ", false),
                EmoticonEntity(20, "( p′︵‵。)", false),
                EmoticonEntity(20, "（；_・）", false),
                EmoticonEntity(20, "（；￣д￣）", false),
                EmoticonEntity(20, "(/ _ ; )", false),
                EmoticonEntity(20, "(′︿‵｡)", false),
                EmoticonEntity(20, "(´＿｀。)", false),
                EmoticonEntity(20, "(´∩｀。)", false),
                EmoticonEntity(20, "(´Ａ｀。)", false),
                EmoticonEntity(20, "(´Д｀。)", false),
                EmoticonEntity(20, "(|||❛︵❛.)", false),
                EmoticonEntity(20, "(இ﹏இ`｡)", false),
                EmoticonEntity(20, "p(´⌒｀｡q)", false),
                EmoticonEntity(20, "(ᗒᗣᗕ)՞", false),
                EmoticonEntity(20, "(≖͞_≖̥)", false),
                EmoticonEntity(20, "(๑•́₋•̩̥̀๑)", false),
                EmoticonEntity(20, "(˃ ⌑ ˂ഃ )", false),
                EmoticonEntity(20, "(´•ω•̥`)", false),
                EmoticonEntity(20, "(;•͈́༚•͈̀)", false),
                EmoticonEntity(20, "(◞‸◟；)", false),
                EmoticonEntity(20, "(•̥́_•ૅू˳)", false),
                EmoticonEntity(20, "(-人-。)", false),
                EmoticonEntity(20, "(T＿T)", false),
                EmoticonEntity(20, "(o;TωT)o", false),
                EmoticonEntity(20, "(━┳━ _ ━┳━)", false),
                EmoticonEntity(20, "(┳◇┳)", false),
                EmoticonEntity(20, "(┳Д┳)", false),
                EmoticonEntity(20, "(╥_╥)", false),
                EmoticonEntity(20, "(。┰ω┰。)", false),
                EmoticonEntity(20, "(； T.T))", false),
                EmoticonEntity(20, "（ ＴДＴ）", false),
                EmoticonEntity(20, "((T.T； )", false),
                EmoticonEntity(20, "(T_T)", false),
                EmoticonEntity(20, "(T⌓T)", false),
                EmoticonEntity(20, "(Ｔ▽Ｔ)", false),
                EmoticonEntity(20, "(ToT)", false),
                EmoticonEntity(20, "（πーπ）", false),
                EmoticonEntity(20, "(ㄒoㄒ)", false),
                EmoticonEntity(20, "╥﹏╥", false),
                EmoticonEntity(20, "o(╥﹏╥)o", false),
                EmoticonEntity(20, "o(TヘTo)", false),
                EmoticonEntity(20, "(╥_╥)", false),
                EmoticonEntity(20, "(╥╯θ╰╥)", false),
                EmoticonEntity(20, "Σ(ＴωＴ)", false),
                EmoticonEntity(20, "(╥ᆺ╥；)", false),
                EmoticonEntity(20, "【T__T】", false),
                EmoticonEntity(20, "o(TﾍTo)", false),
                EmoticonEntity(20, "ヽ(T-T )ノ", false),
                EmoticonEntity(20, "ヽ( T-T)ノ", false),
                EmoticonEntity(20, "(T～T；。)", false),
                EmoticonEntity(20, "(╥︣﹏᷅╥᷅)", false),
                EmoticonEntity(20, "૮( ꒦ິ⍣꒦ີ)ა", false),
                EmoticonEntity(20, "(๑꒦ິ ̼ ꒦ິ๑)", false),
                EmoticonEntity(20, "૮(꒦ິཅ꒦ິ)ა", false),
                EmoticonEntity(20, "(꒦ິ⍸꒦ິ)", false),
                EmoticonEntity(20, "(*꒦ິ⌓꒦ີ)", false),
                EmoticonEntity(20, "(*꒦ິ꒦ີ)", false),
                EmoticonEntity(20, "(*꒦ິ³꒦ີ)", false),
                EmoticonEntity(20, "(*꒦ິ꒳꒦ີ)", false),
                EmoticonEntity(20, "(*꒦ິㅂ꒦ີ)", false),
                EmoticonEntity(20, "(*꒦ິㅿ꒦ີ)", false),
                EmoticonEntity(20, "| ू*꒦ິ꒳꒦ີ)｡oO", false),
                EmoticonEntity(20, "༼ ༎ຶ ෴ ༎ຶ༽", false),
                EmoticonEntity(20, "(༎ຶ⌑༎ຶ)", false),
                EmoticonEntity(20, "(༎ຶ ෴ ༎ຶ)", false),
                EmoticonEntity(20, "( ´༎ຶㅂ༎ຶ`)", false),
                EmoticonEntity(20, "(༎ຶ ෴ ༎ຶ)", false),
                EmoticonEntity(20, "( ´༎ຶㅂ༎ຶ`)", false),
                EmoticonEntity(20, "( ཀ͝ ∧ ཀ͝ )", false),
                //EVIL
                EmoticonEntity(21, "“ψ(｀∇´)ψ", false),
                EmoticonEntity(21, " (。-`ω´-)", false),
                EmoticonEntity(21, "(=｀(∞)´=)", false),
                EmoticonEntity(21, "(○｀ε´○)／＼(○｀ε´○)", false),
                EmoticonEntity(21, "“ψ(｀∇´)ψ", false),
                EmoticonEntity(21, "( ►_◄ )-c<*_*; )", false),
                EmoticonEntity(21, "(・｀ω´・)", false),
                EmoticonEntity(21, "(｡･｀ω´･｡)", false),
                EmoticonEntity(21, "(*-`ω´- )人", false),
                EmoticonEntity(21, "(*｀▽´)_旦~~", false),
                EmoticonEntity(21, "(｀∀´)Ψ", false),
                EmoticonEntity(21, "（｀ー´）", false),
                EmoticonEntity(21, "(｀ε´)", false),
                EmoticonEntity(21, "(｀Д´*)", false),
                EmoticonEntity(21, "（=｀〜´=）", false),
                EmoticonEntity(21, "(=｀ω´=)", false),
                EmoticonEntity(21, "(=｀ェ´=)", false),
                EmoticonEntity(21, "(◞≼◉ื≽◟ ;益;◞≼◉ื≽◟)Ψ", false),
                EmoticonEntity(21, "(☼Д☼)", false),
                EmoticonEntity(21, "(σ-`д･´)", false),
                EmoticonEntity(21, "(ц｀ω´ц*)", false),
                EmoticonEntity(21, "(ﾒ｀ﾛ´)/", false),
                EmoticonEntity(21, "^(#｀∀´)_Ψ", false),
                EmoticonEntity(21, "^（｀ω´ ）^ψ", false),
                EmoticonEntity(21, "←～（o ｀▽´ )oΨ", false),
                EmoticonEntity(21, "←~∋(｡Ψ▼ｰ▼)∈", false),
                EmoticonEntity(21, "∋━━o(｀∀´oメ）～→", false),
                EmoticonEntity(21, "| ｀Д´|", false),
                EmoticonEntity(21, "꒰(@｀꒳´)꒱", false),
                EmoticonEntity(21, "o(｀ω´*)o", false),
                EmoticonEntity(21, "ƪ(`▿▿▿▿´ƪ)", false),
                EmoticonEntity(21, "ψ(*｀ー´)ψ", false),
                EmoticonEntity(21, "ψ(｀∇´)ψ", false),
                EmoticonEntity(21, "Ψ(｀▽´)Ψ", false),
                EmoticonEntity(21, "Ψ(｀◇´)Ψ", false),
                EmoticonEntity(21, "ಠﭛಠ", false),
                EmoticonEntity(21, "⁞⁝•ֱ̀␣̍•́⁝⁞", false),
                EmoticonEntity(21, "(屮｀∀´)屮", false),
                EmoticonEntity(21, "↜(͛ ꒪͒৫͏̈́꒪͒)͛⌰", false),
                EmoticonEntity(21, "↑_(ΦwΦ;)Ψ", false),
                EmoticonEntity(21, "p(｀ε´q）", false),
                EmoticonEntity(21, "Щ(･｀ω´･Щ)", false),
                EmoticonEntity(21, "ﾍ(｀▽´*)", false),
                EmoticonEntity(21, "(-｀ω´-,,)", false),
                EmoticonEntity(21, "Ψ(￣∀￣)Ψ", false),
                EmoticonEntity(21, "Ψ(☆ｗ☆)Ψ", false),
                EmoticonEntity(21, "Ψ( ●｀▽´● )Ψ", false),
                EmoticonEntity(21, "(｀▽´)", false),
                EmoticonEntity(21, "ρ(｀.´)ρ", false),
                EmoticonEntity(21, "ψ（｀Д´）ψ", false),
                EmoticonEntity(21, "ψ`ー´)ﾉ", false),
                EmoticonEntity(21, "(･｀ω´･+)", false),
                EmoticonEntity(21, "Ψ(｀∀´#)ﾉ", false),
                EmoticonEntity(21, "()`艸´()", false),
                EmoticonEntity(21, "ლ(｀∀´ლ)", false),
                EmoticonEntity(21, "＜(●｀∀´●)＞”", false),
                EmoticonEntity(21, "o(○｀ω´○)9", false)
            )
            return result
        }

    }
}