package com.nitroapps.emoticons.helpers

import com.nitroapps.emoticons.EmoticonEntity

class HelperClass1 {
    companion object {
        fun generateData(): Array<EmoticonEntity> {
            val result = arrayOf(
                //HAPPY
                EmoticonEntity(1, "( ͡° ͜ʖ ͡°)", false),
                EmoticonEntity(1, "∠( ᐛ 」∠)＿", false),
                EmoticonEntity(1, "(ﾟ⊿ﾟ)", false),
                EmoticonEntity(1, "ᕕ( ᐛ )ᕗ", false),
                EmoticonEntity(1, "_へ__(‾◡◝ )>", false),
                EmoticonEntity(1, "( ᐛ )و", false),
                EmoticonEntity(1, "( ´ ▽ ` )ﾉ", false),
                EmoticonEntity(1, "(*^▽^*)", false),
                EmoticonEntity(1, "(´∇ﾉ｀*)ノ", false),
                EmoticonEntity(1, "(ノ^∇^)", false),
                EmoticonEntity(1, "⊂((・▽・))⊃", false),
                EmoticonEntity(1, "(　＾∇＾)", false),
                EmoticonEntity(1, "( ﾟ▽ﾟ)/", false),
                EmoticonEntity(1, "（‐＾▽＾‐）", false),
                EmoticonEntity(1, "(“⌒∇⌒”)", false),
                EmoticonEntity(1, "（*´▽｀*）", false),
                EmoticonEntity(1, "(*＾▽＾)／", false),
                EmoticonEntity(1, "(*^▽^*)", false),
                EmoticonEntity(1, "(*~▽~)", false),
                EmoticonEntity(1, "(*≧▽≦)", false),
                EmoticonEntity(1, "(*⌒∇⌒*)", false),
                EmoticonEntity(1, "(*⌒▽⌒*)θ～♪", false),
                EmoticonEntity(1, "(/^▽^)/", false),
                EmoticonEntity(1, "(^∇^)", false),
                EmoticonEntity(1, "(＾▽＾)", false),
                EmoticonEntity(1, "(￣▽￣)ノ", false),
                EmoticonEntity(1, "(￣▽+￣*)", false),
                EmoticonEntity(1, "(゜▽゜;)", false),
                EmoticonEntity(1, "（=´∇｀=）", false),
                EmoticonEntity(1, "(＝⌒▽⌒＝)", false),
                EmoticonEntity(1, "(≡^∇^≡)", false),
                EmoticonEntity(1, "(≧∇≦)/", false),
                EmoticonEntity(1, "（⌒▽⌒）", false),
                EmoticonEntity(1, "(⌒▽⌒)☆", false),
                EmoticonEntity(1, "（⌒▽⌒ゞ", false),
                EmoticonEntity(1, "(●⌒∇⌒●)", false),
                EmoticonEntity(1, "(❁´▽`❁)*✲ﾟ*", false),
                EmoticonEntity(1, "(ノ*゜▽゜*)", false),
                EmoticonEntity(1, "°˖✧◝(⁰▿⁰)◜✧˖°", false),
                EmoticonEntity(1, "~ヾ(＾∇＾)", false),
                EmoticonEntity(1, "∩(︶▽︶)∩", false),
                EmoticonEntity(1, "≧(´▽｀)≦", false),
                EmoticonEntity(1, "ー( ´ ▽ ` )ﾉ", false),
                EmoticonEntity(1, "ヾ(´▽｀;)ゝ", false),
                EmoticonEntity(1, "ヾ(＾∇＾)", false),
                EmoticonEntity(1, "d=(´▽｀)=b", false),
                EmoticonEntity(1, "o(〃＾▽＾〃)o", false),
                EmoticonEntity(1, "o(^▽^)o", false),
                EmoticonEntity(1, "Ｏ(≧∇≦)Ｏ", false),
                EmoticonEntity(1, "o(≧∇≦o)", false),
                EmoticonEntity(1, "(๑꒪▿꒪)*", false),
                EmoticonEntity(1, "(⁎⚈᷀᷁▿⚈᷀᷁⁎)", false),
                EmoticonEntity(1, "(≧∇≦*)", false),
                EmoticonEntity(1, "(=^▽^=)", false),
                EmoticonEntity(1, "o(*^▽^*)o", false),
                EmoticonEntity(1, "೭੧(❛▿❛✿)੭೨", false),
                EmoticonEntity(1, "☜(⌒▽⌒)☞", false),
                EmoticonEntity(1, "☜(˚▽˚)☞", false),
                EmoticonEntity(1, "ɾ⚈▿⚈ɹ", false),
                EmoticonEntity(1, "ﾍ(=￣∇￣)ﾉ", false),
                EmoticonEntity(1, "φ(*⌒▽⌒)ﾉ", false),
                EmoticonEntity(1, "(*･▽･*)", false),
                EmoticonEntity(1, "(☆▽☆)", false),
                EmoticonEntity(1, "≡(*′▽`)っ", false),
                EmoticonEntity(1, "」(￣▽￣」)", false),
                EmoticonEntity(1, "(〃⌒∇⌒)", false),
                EmoticonEntity(1, "〔´∇｀〕", false),
                EmoticonEntity(1, "(゜▼゜＊）", false),
                EmoticonEntity(1, "(｡´∀｀)ﾉ", false),
                EmoticonEntity(1, "(　´∀｀)", false),
                EmoticonEntity(1, "(・∀・)", false),
                EmoticonEntity(1, "(´∀`)", false),
                EmoticonEntity(1, "(°∀°)b", false),
                EmoticonEntity(1, "(●´∀｀●)", false),
                EmoticonEntity(1, "(✌ﾟ∀ﾟ)☞", false),
                EmoticonEntity(1, "*(*´∀｀*)☆", false),
                EmoticonEntity(1, "( ´ ∀ ` )", false),
                EmoticonEntity(1, "ヽ(･∀･)ﾉ", false),
                EmoticonEntity(1, "(。≖ˇ∀ˇ≖。)", false),
                EmoticonEntity(1, "((o(´∀｀)o))", false),
                EmoticonEntity(1, "o(´∀｀*)", false),
                EmoticonEntity(1, "(ﾟ∀ﾟ　)", false),
                EmoticonEntity(1, "(*≧∀≦*)", false),
                EmoticonEntity(1, "(*ﾟ∀ﾟ*)", false),
                EmoticonEntity(1, "ヾ(*´∀｀*)ﾉ", false),
                EmoticonEntity(1, "(o^∀^o)", false),
                EmoticonEntity(1, "ヾ(^ิ∀^ิ)", false),
                EmoticonEntity(1, "o(｀・∀・´)○", false),
                EmoticonEntity(1, "(ᗒᗊᗕ)", false),
                EmoticonEntity(1, "(ノ・∀・)ノ", false),
                EmoticonEntity(1, "o((◕ฺ∀ ◕✿ฺ))o", false),
                EmoticonEntity(1, "～̎̎٩(⌒͡∀⌒͡⌯̊)̥̊◦", false),
                EmoticonEntity(1, "(´･∀･`)", false),
                EmoticonEntity(1, "∩(´∀｀∩)", false),
                EmoticonEntity(1, "(ﾉ `･∀･)ﾉﾞ", false),
                EmoticonEntity(1, "( ﾟ∀ ﾟ)", false),
                EmoticonEntity(1, "Ψ(ﾟ∀ﾟ )Ψ", false),
                EmoticonEntity(1, "Ψ(　ﾟ∀ﾟ)Ψ", false),
                EmoticonEntity(1, "Ψ(ﾟ∀ﾟ)Ψ", false),
                EmoticonEntity(1, "d┃･∀･┃b", false),
                EmoticonEntity(1, "(*´･∀･)", false),
                EmoticonEntity(1, "(･∀･○)", false),
                EmoticonEntity(1, "【°∀°】", false),
                EmoticonEntity(1, "（★￣∀￣★）", false),
                EmoticonEntity(1, "(m*´∀`)m", false),
                EmoticonEntity(1, "=͟͟͞͞( ✌°∀° )☛", false),
                EmoticonEntity(1, "∩(´∀`∩)", false),
                EmoticonEntity(1, "∩( ´∀` )∩", false),
                EmoticonEntity(1, "(∩´∀`)∩", false),
                EmoticonEntity(1, "⊂( ・ ̫・)⊃", false),
                EmoticonEntity(1, "(*′☉.̫☉)", false),
                EmoticonEntity(1, "((ඏ.̫ඏ*))", false),
                EmoticonEntity(1, "⁽͑˙ˆ˙̫ˆ˙⁾̉", false),
                EmoticonEntity(1, "(๑★ .̫ ★๑)", false),
                EmoticonEntity(1, "‧⁺◟( ᵒ̴̶̷̥́ ·̫ ᵒ̴̶̷̣̥̀ )", false),
                EmoticonEntity(1, "(^～^)", false),
                EmoticonEntity(1, "(⌯⚈ै〰̇⚈ै)", false),
                EmoticonEntity(1, "( ‾ʖ̫‾)", false),
                EmoticonEntity(1, "(̂ ˃̥̥̥ ˑ̫ ˂̥̥̥ )̂", false),
                EmoticonEntity(1, "⁽ˇ́˙̫ˇ̀˵⁾", false),
                EmoticonEntity(1, "( ᵕ̤ ‧̫̮ ᵕ̤ )", false),
                EmoticonEntity(1, "⁽͑΅ ˙̫ ῭⁾̉", false),
                EmoticonEntity(1, "(⋆ʾ ˙̫̮ ʿ⋆)", false),
                EmoticonEntity(1, "(*´・ｖ・)", false),
                EmoticonEntity(1, "(*＾v＾*)", false),
                EmoticonEntity(1, "（＾ｖ＾）", false),
                EmoticonEntity(1, "(▰˘v˘▰)", false),
                EmoticonEntity(1, "(n˘v˘•)¬", false),
                EmoticonEntity(1, "(´｡･v･｡｀)", false),
                EmoticonEntity(1, "♡✧( ु•⌄• )", false),
                EmoticonEntity(1, "( •⌄• ू )✧", false),
                EmoticonEntity(1, "(⌯⌅⌄⌅)", false),
                EmoticonEntity(1, "῍̩̞(∗ɞ⌄ɞ∗)◞", false),
                EmoticonEntity(1, "(′ʘ⌄ʘ‵)", false),
                EmoticonEntity(1, "( ^_^)／", false),
                EmoticonEntity(1, "(^ _ ^)/", false),
                EmoticonEntity(1, "（＾_＾）", false),
                EmoticonEntity(1, "(^-^*)/", false),
                EmoticonEntity(1, "（￣ー￣）", false),
                EmoticonEntity(1, "(∩_∩)", false),
                EmoticonEntity(1, "(∩▂∩)", false),
                EmoticonEntity(1, "(☆^ー^☆)", false),
                EmoticonEntity(1, "（ｖ＾＿＾）ｖ", false),
                EmoticonEntity(1, "p(*＾-＾*)q", false),
                EmoticonEntity(1, "(^・ω・^ )", false),
                EmoticonEntity(1, "(=^-ω-^=)", false),
                EmoticonEntity(1, "(=^･ω･^)y＝", false),
                EmoticonEntity(1, "( ﾉ^ω^)ﾉﾟ", false),
                EmoticonEntity(1, "（＿´ω｀）", false),
                EmoticonEntity(1, "(｡･ω･｡)", false),
                EmoticonEntity(1, "(︶ω︶)", false),
                EmoticonEntity(1, "(｀・ω・´)”", false),
                EmoticonEntity(1, "(´ω｀★)", false),
                EmoticonEntity(1, "(＾ω＾)", false),
                EmoticonEntity(1, "(◐ω◑ )", false),
                EmoticonEntity(1, "∩( ・ω・)∩", false),
                EmoticonEntity(1, "ヾ(｡･ω･｡)", false),
                EmoticonEntity(1, "୧( ॑ധ ॑)୨", false),
                EmoticonEntity(1, "d(=^･ω･^=)b", false),
                EmoticonEntity(1, "ｏ（Ｕ・ω・）⊃", false),
                EmoticonEntity(1, "V(=^･ω･^=)v", false),
                EmoticonEntity(1, "川´･ω･`川", false),
                EmoticonEntity(1, "(*´꒳`*)", false),
                EmoticonEntity(1, "(*^ω^*)", false),
                EmoticonEntity(1, "(❁´ω`❁)", false),
                EmoticonEntity(1, "(´-ω-`)", false),
                EmoticonEntity(1, "ଘ(੭ˊ꒳ˋ)੭✧", false),
                EmoticonEntity(1, "(´へωへ`*)", false),
                EmoticonEntity(1, "(　^ω^）", false),
                EmoticonEntity(1, "（　＾ω＾）", false),
                EmoticonEntity(1, "(✌’ω’)✌", false),
                EmoticonEntity(1, "✌(‘ω’)✌", false),
                EmoticonEntity(1, "✌(‘ω’✌)", false),
                EmoticonEntity(1, "٩(ↁωↁ❀)", false),
                EmoticonEntity(1, "˚✧₊⁎( ˘ω˘ )⁎⁺˳✧༚", false),
                EmoticonEntity(1, "(◜௰◝)", false),
                EmoticonEntity(1, "✾(〜 ☌ω☌)〜✾", false),
                EmoticonEntity(1, "(´∩ω∩｀)", false),
                EmoticonEntity(1, "(¬‿¬)", false),
                EmoticonEntity(1, "( ⋂‿⋂’)", false),
                EmoticonEntity(1, "(-‿◦☀)", false),
                EmoticonEntity(1, "(*‿*✿)", false),
                EmoticonEntity(1, "(•‿•)", false),
                EmoticonEntity(1, "(•̀ᴗ•́)و ̑̑", false),
                EmoticonEntity(1, "(─‿─)", false),
                EmoticonEntity(1, "(◍•ᴗ•◍)❤", false),
                EmoticonEntity(1, "(◑‿◐)", false),
                EmoticonEntity(1, "(✿´‿`)", false),
                EmoticonEntity(1, "(❀◦‿◦)", false),
                EmoticonEntity(1, "(❁´‿`❁)*✲ﾟ*", false),
                EmoticonEntity(1, "(ᅌᴗᅌ* )", false),
                EmoticonEntity(1, "(•ˇ‿ˇ•)-→", false),
                EmoticonEntity(1, "♫꒰･‿･๑꒱", false),
                EmoticonEntity(1, "o (^‿^✿)", false),
                EmoticonEntity(1, "(◑‿◐✿)", false),
                EmoticonEntity(1, "(◡‿◡✿)", false),
                EmoticonEntity(1, "(✿◠‿◠)", false),
                EmoticonEntity(1, "(◕‿◕✿)", false),
                EmoticonEntity(1, "(๑>ᴗ<๑)", false),
                EmoticonEntity(1, "(๑✧◡✧๑)", false),
                EmoticonEntity(1, "(๑>◡<๑)", false),
                EmoticonEntity(1, "♪(๑ᴖ◡ᴖ๑)♪", false),
                EmoticonEntity(1, "(｡◝‿◜｡)", false),
                EmoticonEntity(1, "(๑^ں^๑)", false),
                EmoticonEntity(1, "( ்ͦˏ౦͜ˎ ்ͦ)", false),
                EmoticonEntity(1, "(ෆ ͒•∘̬• ͒)◞", false),
                EmoticonEntity(1, "(•⚗৺⚗•)", false),
                EmoticonEntity(1, "(ට˓˳̮ට๑)", false),
                EmoticonEntity(1, "(๑•͈ᴗ•͈)", false),
                EmoticonEntity(1, "₍՞◌′ᵕ‵ू◌₎♡", false),
                EmoticonEntity(1, "(੭ˊ͈ ꒵ˋ͈)੭̸*✧⁺˚", false),
                EmoticonEntity(1, "꒰⁎ᵉ̷͈ ॣ꒵ ॢᵉ̷͈⁎꒱໊", false),
                EmoticonEntity(1, "(⑅˘͈ ᵕ ˘͈ )", false),
                EmoticonEntity(1, ":: ೖ(⑅σ̑ᴗσ̑)ೖ ::", false),
                EmoticonEntity(1, "三⊂( っ⌒◡|", false),
                EmoticonEntity(1, "(ؑᵒᵕؑ̇ᵒ)◞✧", false),
                EmoticonEntity(1, "꒰•́ॢ৺•̀ॢ๑͒꒱", false),
                EmoticonEntity(1, "(｡≍ฺ‿ฺ≍ฺ)", false),
                EmoticonEntity(1, "(⚈᷁‿᷇⚈᷁)", false),
                EmoticonEntity(1, "(๑◕ฺ‿ฺ◕ฺ๑)", false),
                EmoticonEntity(1, "⁽(◍˃̵͈̑ᴗ˂̵͈̑)", false),
                EmoticonEntity(1, "(人 •͈ᴗ•͈)", false),
                EmoticonEntity(1, "(*˙︶˙*)☆*°", false),
                EmoticonEntity(1, "(୨୧ ❛ᴗ❛)✧", false),
                EmoticonEntity(1, "( ¨̮ )", false),
                EmoticonEntity(1, "(＊◕ᴗ◕＊)", false),
                EmoticonEntity(1, "(*´╰╯`๓)♬", false),
                EmoticonEntity(1, "(∗❛ัᴗ❛ั∗)", false),
                EmoticonEntity(1, "⊂(◉‿◉)つ", false),
                EmoticonEntity(1, "(人 •͈ᴗ•͈✿ฺ)", false),
                EmoticonEntity(1, "( ･ᴗ･̥̥̥ )", false),
                EmoticonEntity(1, "(≖ ‿ ≖)", false),
                EmoticonEntity(1, "(๑˃͈꒵˂͈๑)", false),
                EmoticonEntity(1, "(⑅‾̥̥̥̥̥̑⌣‾̥̥̥̥̥̑⑅)", false),
                EmoticonEntity(1, "(>̯-̮<̯)", false),
                EmoticonEntity(1, "(⁎⚈᷀᷁ᴗ⚈᷀᷁⁎)", false),
                EmoticonEntity(1, "  (⁰ੌ⌣⁰ੌ๑)", false),
                EmoticonEntity(1, "(⚈᷀᷁ᴗ⚈᷀᷁⁎)", false),
                EmoticonEntity(1, "✌(-‿-)✌", false),
                EmoticonEntity(1, "(⋓ื◡⋓ื)", false),
                EmoticonEntity(1, "（。≖ิ‿≖ิ）", false),
                EmoticonEntity(1, "(๑￫‿ฺ￩๑)", false),
                EmoticonEntity(1, "ˆ̭̭͙(๑ ົ̅ ͔৹͜ ົ̅๑)", false),
                EmoticonEntity(1, "(∗ᵕ̴᷄◡ᵕ̴᷅∗)՞", false),
                EmoticonEntity(1, "( •॒◞ ͜◟•॒ )", false),
                EmoticonEntity(1, "(ㆁᴗㆁ✿)", false),
                EmoticonEntity(1, "(๑’◡͐’๑)", false),
                EmoticonEntity(1, "(⌒⃝৺⌒⃝)", false),
                EmoticonEntity(1, "{´◕ ◡ ◕｀}", false),
                EmoticonEntity(1, "(ට ̥̆ ට)", false),
                EmoticonEntity(1, "⁽͑˙˚̀ᵕ˚́˙⁾̉", false),
                EmoticonEntity(1, "(*☌ᴗ☌)｡*ﾟ", false),
                EmoticonEntity(1, "( ´◡‿ゝ◡`)", false),
                EmoticonEntity(1, "(　◠ ◡ ◠　)", false),
                EmoticonEntity(1, "ల(*´= ◡ =｀*)", false),
                EmoticonEntity(1, "₊⚛⁺(ؔ꒨◡ؔ꒨)ᵌ", false),
                EmoticonEntity(1, "( ்ͧˏ౦͜ˎ ்ͧ)", false),
                EmoticonEntity(1, "꒰⁎❛⃘ੌ ᵕ ❛⃘ੌ⁎꒱", false),
                EmoticonEntity(1, "( ́⋅⃘ˬ̇⋅⃘ ̀ˋ)", false),
                EmoticonEntity(1, "(. ົ̅ ੭͜ ົ̅.)", false),
                EmoticonEntity(1, "( ᵘ ᵕ ᵘ ⁎)", false),
                EmoticonEntity(1, "( ᵘ ᵕ ᵘ ⁎)", false),
                EmoticonEntity(1, "(๑`･ᴗ･´๑)", false),
                EmoticonEntity(1, "❀.(*´◡`*)❀.", false),
                EmoticonEntity(1, "◟(๑•͈ᴗ•͈)◞", false),
                EmoticonEntity(1, "₍ఠ ͜ఠ₎", false),
                EmoticonEntity(1, "(•‾̑⌣‾̑•)", false),
                EmoticonEntity(1, "(∗ᒩ͜∗)", false),
                EmoticonEntity(1, "( ்ૂ౧͜ ்)", false),
                EmoticonEntity(1, "(⋈･◡･)✰", false),
                EmoticonEntity(1, "(⁝̥ꑦᴗꑦ)", false),
                EmoticonEntity(1, "(︶.̮︶✽)", false),
                EmoticonEntity(1, "(❍❛‿❛❍❋)", false),
                EmoticonEntity(1, "₍•͈ᴗ•͈₎", false),
                EmoticonEntity(1, "(ͼ ̥̆ ͽ)", false),
                EmoticonEntity(1, "(≖ᴗ≖๑)", false),
                EmoticonEntity(1, "( °̥̥̥̥̥̥̥̥◡͐°̥̥̥̥̥̥̥̥)", false),
                EmoticonEntity(1, "( ´͈ ◡ `͈ )", false),
                EmoticonEntity(1, "( ๑॔•◡ુ•๑॓)", false),
                EmoticonEntity(1, "  (๑･`◡´･๑)", false),
                EmoticonEntity(1, ",､’`(((;ŏᴗŏ))),､’`’`,､", false),
                EmoticonEntity(1, "ෆ⃛(ට◡ට⁎)ფ", false),
                EmoticonEntity(1, "੬ჴ❛‿❛ჴჱ̒̒", false),
                EmoticonEntity(1, "৵( °͜ °৵)", false),
                EmoticonEntity(1, "(✿◕ ‿◕ฺ)ノ))。₀: *゜", false),
                EmoticonEntity(1, "☆(❁‿❁)☆", false),
                EmoticonEntity(1, "◃┆◉◡◉┆▷", false),
                EmoticonEntity(1, "q(❂‿❂)p", false),
                EmoticonEntity(1, "☆(◒‿◒)☆", false),
                EmoticonEntity(1, "⊂◉‿◉つ", false),
                EmoticonEntity(1, "(｡✿‿✿｡)", false),
                EmoticonEntity(1, "໒( ﹒ ͜ر ﹒ )७", false),
                EmoticonEntity(1, "( ‾̮‿͂‾̮ ꐦ)", false),
                EmoticonEntity(1, "(˘･ᴗ･˘)", false),
                EmoticonEntity(1, "(ό‿ὸ)ﾉ", false),
                EmoticonEntity(1, "ヾ|๑　╹　◡　╹　๑|ﾉ", false),
                EmoticonEntity(1, "(((;◔ᴗ◔;)))", false),
                EmoticonEntity(1, "໒( ” ¤ ‿ ¤ ” )७", false),
                EmoticonEntity(1, "✩*॰ ( ¨̮ ) ॰*✩", false),
                EmoticonEntity(1, "(✧≖‿ゝ≖)", false),
                EmoticonEntity(1, "☝( ◠‿◠ )☝", false),
                EmoticonEntity(1, "(*´◡｀​*)", false),
                EmoticonEntity(1, "(๑◔‿◔๑)", false),
                EmoticonEntity(1, "(◕‿‿◕｡)", false),
                EmoticonEntity(1, "(✿╹◡╹)", false),
                EmoticonEntity(1, "(◕ฺ ◡ฺ ◕ฺ)", false),
                EmoticonEntity(1, "(✿ฺ◡ฺ‿ฺ◡ฺ)", false),
                EmoticonEntity(1, "（◞‿◟）", false),
                EmoticonEntity(1, "(o˘◡˘o)", false),
                EmoticonEntity(1, "ꉂꉂ ( ˆᴗˆ )", false),
                EmoticonEntity(1, "₊·(ϱ॔⌄ᵕ๑॓)‧*", false),
                EmoticonEntity(1, "-(๑☆‿ ☆#)ᕗ", false),
                EmoticonEntity(1, "╭ (oㅇ‿ o#)ᕗ", false),
                EmoticonEntity(1, "／人◕ ‿‿ ◕人＼", false),
                EmoticonEntity(1, "(o^^)o", false),
                EmoticonEntity(1, "ヾ(^ ^ゞ", false),
                EmoticonEntity(1, "o(^^o)", false),
                EmoticonEntity(1, "(o^^o)♪", false),
                EmoticonEntity(1, "(o⌒．⌒o)", false),
                EmoticonEntity(1, "(=^･^=)", false),
                EmoticonEntity(1, "。(⌒.⌒。)", false),
                EmoticonEntity(1, "( ﾉ^.^)ﾉﾟ", false),
                EmoticonEntity(1, "(“⌒.⌒”)", false),
                EmoticonEntity(1, "(≧.≦*)", false),
                EmoticonEntity(1, "(*^^*)", false),
                EmoticonEntity(1, "(ꐦ ´͈ ᗨ `͈ )", false),
                EmoticonEntity(1, "( ´͈ ॢꇴ  `͈)੭ु", false),
                EmoticonEntity(1, "（ꉺᗜꉺ）", false),
                EmoticonEntity(1, "(･ัᗜ･ั)و", false),
                EmoticonEntity(1, "✌✌(➲ ᗜ ➲)✌✌", false),
                EmoticonEntity(1, "✌✌(˵¯̴͒ꇴ¯̴͒˵)✌✌", false),
                EmoticonEntity(1, "( ˙̣̣̣ↂ⃙⃙⃚᷄ᗨↂ⃙⃙⃚ )ꋧ", false),
                EmoticonEntity(1, "(ᗒᗨᗕ)", false),
                EmoticonEntity(1, "(๑’ᗢ’๑)ฅ", false),
                EmoticonEntity(1, "(✤❛⃘ͫ Ʉ̮ ❛⃘ͫ)", false),
                EmoticonEntity(1, "┌༼ ˵ ° ᗜ ° ˵ ༽┐", false),
                EmoticonEntity(1, "ˉ̶̡̭̭ ( ´͈ ᗨ `͈ ) ˉ̶̡̭̭", false),
                EmoticonEntity(1, "(□ᗜ□)", false),
                EmoticonEntity(1, "(-^〇^-)", false),
                EmoticonEntity(1, "(.=^・ェ・^=)", false),
                EmoticonEntity(1, "(・◇・)", false),
                EmoticonEntity(1, "(*＾ワ＾*)", false),
                EmoticonEntity(1, "(*¬*)", false),
                EmoticonEntity(1, "(´ヮ`)", false),
                EmoticonEntity(1, "(^(I)^)", false),
                EmoticonEntity(1, "(^(エ)^)", false),
                EmoticonEntity(1, "（＾⊆＾）", false),
                EmoticonEntity(1, "(๑^っ^๑)", false),
                EmoticonEntity(1, "（＞ｙ＜）", false),
                EmoticonEntity(1, "(⊙ヮ⊙)", false),
                EmoticonEntity(1, "(☆^O^☆)", false),
                EmoticonEntity(1, "°˖ ✧◝(○ ヮ ○)◜✧˖ °", false),
                EmoticonEntity(1, "⊂(^(工)^)⊃", false),
                EmoticonEntity(1, "ヾ（*⌒ヮ⌒*）ゞ", false),
                EmoticonEntity(1, "(ⓥꇳⓥ*)", false),
                EmoticonEntity(1, "((ꉺꈊꉺ)ꀢ༣", false),
                EmoticonEntity(1, "(๑❛ꆚ❛๑)", false),
                EmoticonEntity(1, "(ᵒ̴̶̷̤́◞౪◟ ᵒ̴̶̷̤̀ )", false),
                EmoticonEntity(1, "(^ワ^＝)", false),
                EmoticonEntity(1, "(*´ч ` *)", false),
                EmoticonEntity(1, "（｡◑ヮ◑｡）", false),
                EmoticonEntity(1, "（ꉺ౪ꉺ）", false),
                EmoticonEntity(1, "( ◑ٹ◐)", false),
                EmoticonEntity(1, "(´ёٹё)", false),
                EmoticonEntity(1, "(*^ิ益^ิ*)", false),
                EmoticonEntity(1, "(´◉◞౪◟◉)", false),
                EmoticonEntity(1, "(*^｡^*)", false),
                EmoticonEntity(1, "(๑*౪*๑)", false),
                EmoticonEntity(1, "（＾凹＾）", false),
                EmoticonEntity(1, ",､’`<(❛ヮ❛✿)>,､’`’`,､", false),
                EmoticonEntity(1, "ೖ(σ̑˽σ̑)ೖ", false),
                EmoticonEntity(1, "(●⌃ٹ⌃)", false),
                EmoticonEntity(1, "(*꒩̐﹀꒩̐*)", false),
                EmoticonEntity(1, "(^◇^；)", false),
                EmoticonEntity(1, "(✿ ◜◒◝ )", false),
                EmoticonEntity(1, "(´◉◞౪◟◉｀)", false),
                EmoticonEntity(1, "(థฺˇ౪ˇథ)", false),
                EmoticonEntity(1, "(⁎ؔꇵ ˒̠̮ ؔꇵ)", false),
                EmoticonEntity(1, "( •˓◞•̀ )", false),
                EmoticonEntity(1, "(*ꄱͦ︺ꄱͦ*)", false),
                EmoticonEntity(1, "( ՞ٹ՞)", false),
                EmoticonEntity(1, "( ´•౪•`)", false),
                EmoticonEntity(1, "(*´∪`)", false),
                EmoticonEntity(1, "(◍ȋ ₎໐͜₍ ȋ◍)", false),
                EmoticonEntity(1, "♪~♪ d(⌒o⌒)b♪~♪", false),
                EmoticonEntity(1, "♪♪ｖ(⌒ｏ⌒)ｖ♪♪", false),
                EmoticonEntity(1, "∩`･◇･)", false),
                EmoticonEntity(1, "(★^O^★)", false),
                EmoticonEntity(1, "(((o(*ﾟ▽ﾟ*)o)))", false),
                EmoticonEntity(1, "＼（＠￣∇￣＠）／", false),
                EmoticonEntity(1, "ヽ(；▽；)ノ", false),
                EmoticonEntity(1, "ヾ(@^▽^@)ノ", false),
                EmoticonEntity(1, "o((*^▽^*))o", false),
                EmoticonEntity(1, "Ｏ(≧▽≦)Ｏ", false),
                EmoticonEntity(1, "– =͟͟͞͞ ( ꒪౪꒪)ฅ✧", false),
                EmoticonEntity(1, "“ヽ(´▽｀)ノ”", false),
                EmoticonEntity(1, "(((＼（＠v＠）／)))", false),
                EmoticonEntity(1, "(ﾉ´ヮ´)ﾉ*:･ﾟ✧", false),
                EmoticonEntity(1, "(ノ^_^)ノ", false),
                EmoticonEntity(1, "(ノ＞▽＜。)ノ", false),
                EmoticonEntity(1, "(ﾉﾟ▽ﾟ)ﾉ", false),
                EmoticonEntity(1, "〈( ^.^)ノ", false),
                EmoticonEntity(1, "＼(*T▽T*)／", false),
                EmoticonEntity(1, "＼（＾▽＾）／", false),
                EmoticonEntity(1, "＼(^ω^＼)", false),
                EmoticonEntity(1, "＼（Ｔ∇Ｔ）／", false),
                EmoticonEntity(1, "☆*:.｡. o(≧▽≦)o .｡.:*☆", false),
                EmoticonEntity(1, "ヽ(;^o^ヽ)", false),
                EmoticonEntity(1, "ヽ(；▽；)ノ", false),
                EmoticonEntity(1, "ヽ(‘ ∇‘ )ノ", false),
                EmoticonEntity(1, "ヾ(＠† ▽ †＠）ノ", false),
                EmoticonEntity(1, "ヾ(＠^∇^＠)ノ", false),
                EmoticonEntity(1, "ヾ(＠^▽^＠)ﾉ", false),
                EmoticonEntity(1, "ヾ（＠＾▽＾＠）ノ", false),
                EmoticonEntity(1, "ヾ(@゜∇゜@)ノ", false),
                EmoticonEntity(1, "ヾ(＠゜▽゜＠）ノ", false),
                EmoticonEntity(1, "ヾ(@°▽°@)ノ", false),
                EmoticonEntity(1, "ヾ(＠⌒ー⌒＠)ノ", false),
                EmoticonEntity(1, "ヽ(*≧ω≦)ﾉ", false),
                EmoticonEntity(1, "ヽ(*・ω・)ﾉ", false),
                EmoticonEntity(1, "ヽ(*⌒∇⌒*)ﾉ", false),
                EmoticonEntity(1, "ヾ(＾-＾)ノ", false),
                EmoticonEntity(1, "ヽ(^。^)丿", false),
                EmoticonEntity(1, "ヽ(＾Д＾)ﾉ", false),
                EmoticonEntity(1, "ヽ(=^･ω･^=)丿", false),
                EmoticonEntity(1, "٩(^ᴗ^)۶", false),
                EmoticonEntity(1, "о(ж＞▽＜)ｙ ☆", false),
                EmoticonEntity(1, "ヘ(^_^ヘ)", false),
                EmoticonEntity(1, "ヘ(^o^ヘ)", false),
                EmoticonEntity(1, "へ(゜∇、°)へ", false),
                EmoticonEntity(1, "＼＼\\ ٩(`(エ)´ )و //／／", false),
                EmoticonEntity(1, "(／・ω・)／", false),
                EmoticonEntity(1, "୧(﹒︠ᴗ﹒︡)୨", false),
                EmoticonEntity(1, "(☝ ՞ਊ ՞)☝", false),
                EmoticonEntity(1, "⸂⸂⸜(രᴗര๑)⸝⸃⸃", false),
                EmoticonEntity(1, "˛˛ƪ(⌾⃝ ౪ ⌾⃝ ๑)و ̉ ̉", false),
                EmoticonEntity(1, "ヾ(๑╹ヮ╹๑)ﾉ”", false),
                EmoticonEntity(1, "ヾ(๑╹ꇴ◠๑)ﾉ”", false),
                EmoticonEntity(1, "ヾ(๑ㆁᗜㆁ๑)ﾉ”", false),
                EmoticonEntity(1, "⁽⁽◞(꒪ͦᴗ̵̍꒪ͦ=͟͟͞͞ ꒪ͦᴗ̵̍꒪ͦ)◟⁾⁾", false),
                EmoticonEntity(1, "ヾ(Ő∀Ő๑)ﾉ", false),
                EmoticonEntity(1, "(੭ु｡╹▿╹｡)੭ु⁾⁾", false),
                EmoticonEntity(1, "₍₍ (ง Ŏ౪Ŏ)ว ⁾⁾", false),
                EmoticonEntity(1, "(ง •ૅ౪•᷄)ว", false),
                EmoticonEntity(1, "₍₍⁽⁽(ી(^‿ゝ^)ʃ)₎₎⁾⁾", false),
                EmoticonEntity(1, "(´ ↂ⃙⃙⃚ꇴↂ⃙⃙⃚ `≡´ ↂ⃙⃙⃚ꇴↂ⃙⃙⃚ `)", false),
                EmoticonEntity(1, "(ﾉ^_^)ﾉ", false),
                EmoticonEntity(1, "◦°˚\\(*❛‿❛)/˚°◦", false),
                EmoticonEntity(1, "⌒°(ᴖ◡ᴖ)°⌒", false),
                EmoticonEntity(1, "⌒(o＾▽＾o)ノﾟ", false),
                EmoticonEntity(1, "｡:.ﾟヽ(´∀`｡)ﾉﾟ.:｡+ﾟ", false),
                EmoticonEntity(1, "ﾟ+｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡+ﾟ", false),
                EmoticonEntity(1, "ヾ(○･ω･)ﾉ☆", false),
                EmoticonEntity(1, "୧( “̮ )୨✧", false),
                EmoticonEntity(1, "✌(๑˃̶͈̀◡˂̶͈́๑)✌", false),
                EmoticonEntity(1, "✩◝(◍⌣̎◍)◜✩", false),
                EmoticonEntity(1, "∕∕∕ ∕ ∕∕˛₍˴◅ˋ)੭✧∕∕∕ ∕∕", false),
                EmoticonEntity(1, "(◜▿‾ ≡‾▿◝)", false),
                EmoticonEntity(1, "୧[ ˵ ͡ᵔ ͜ʟ ͡ᵔ ˵ ]୨", false),
                EmoticonEntity(1, "ヾ( ~▽~)ﾂ", false),
                EmoticonEntity(1, "(ﾉ*´▽)ﾉ", false),
                EmoticonEntity(1, "ヽ(^◇^*)/", false),
                EmoticonEntity(1, "ヾ（ ❀◕◡◕ฺฺ ）ノ", false),
                EmoticonEntity(1, "ヽ（◕◡◕❀ฺ ）ノ", false),
                EmoticonEntity(1, "ヾ(^▽^ヾ)", false),
                EmoticonEntity(1, "୧〳 ＾ ౪ ＾ 〵୨", false),
                EmoticonEntity(1, "=͟͟͞͞٩(๑☉ᴗ☉)੭ु⁾⁾", false),
                EmoticonEntity(1, "(((o(*ﾟ▽ﾟ*)o)))", false),
                EmoticonEntity(1, "o((*^▽^*))o", false),
                EmoticonEntity(1, "Ｏ(≧▽≦)Ｏ", false),
                EmoticonEntity(1, "o(〃＾▽＾〃)o", false),
                EmoticonEntity(1, "o(^▽^)o", false),
                EmoticonEntity(1, "Ｏ(≧∇≦)Ｏ", false),
                EmoticonEntity(1, "o(≧∇≦o)", false),
                EmoticonEntity(1, "σ(≧ε≦ｏ)", false),
                EmoticonEntity(1, "o(*^▽^*)o", false),
                EmoticonEntity(1, "⌒°(❛ᴗ❛)°⌒", false),
                EmoticonEntity(1, "o(^∀^*)o", false),
                EmoticonEntity(1, "o(^◇^)o", false),
                EmoticonEntity(1, "《《o(≧◇≦)o》》", false),
                EmoticonEntity(1, "o(*≧□≦)o", false),
                EmoticonEntity(1, "o(*>ω<*)o", false),
                EmoticonEntity(1, "(ﾉ･ｪ･)ﾉ", false),
                EmoticonEntity(1, "(/^▽^)/", false),
                EmoticonEntity(1, "(ﾉ´ヮ´)ﾉ*:･ﾟ✧", false),
                EmoticonEntity(1, "(ﾉ≧∀≦)ﾉ", false),
                EmoticonEntity(1, "(ﾉ^ヮ^)ﾉ*:・ﾟ✧", false),
                EmoticonEntity(1, "(/ ‘з’)/", false),
                EmoticonEntity(1, "(۶ꈨຶꎁꈨຶ )۶ʸᵉᵃʰᵎ", false),
                EmoticonEntity(1, "⁽(◍˃̵͈̑ᴗ˂̵͈̑)⁽", false),
                EmoticonEntity(1, "(╯✧∇✧)╯", false),
                EmoticonEntity(1, "Σ(ノ°▽°)ノ", false),
                EmoticonEntity(1, "( ƅ°ਉ°)ƅ", false),
                EmoticonEntity(1, "ヽ(　･∀･)ﾉ", false),
                EmoticonEntity(1, "˭̡̞(◞⁎˃ᆺ˂)◞*✰", false),
                EmoticonEntity(1, "(p^-^)p", false),
                EmoticonEntity(1, "(ﾉ^∇^)ﾉﾟ", false),
                EmoticonEntity(1, "ヽ(〃･ω･)ﾉ", false),
                EmoticonEntity(1, "(۶* ‘ꆚ’)۶”", false),
                EmoticonEntity(1, "（。＞ω＜）。", false),
                EmoticonEntity(1, "（ﾉ｡≧◇≦）ﾉ", false),
                EmoticonEntity(1, "ヾ(｡･ω･)ｼ", false),
                EmoticonEntity(1, "(ﾉ･д･)ﾉ", false),
                EmoticonEntity(1, ".+:｡(ﾉ･ω･)ﾉﾞ", false),
                EmoticonEntity(1, "Σ(*ﾉ´>ω<｡`)ﾉ", false),
                EmoticonEntity(1, "ヾ（〃＾∇＾）ﾉ♪", false),
                EmoticonEntity(1, ".ﾟ☆(ノё∀ё)ノ☆ﾟ.", false),
                EmoticonEntity(1, "ヽ(;^o^ヽ)", false),
                EmoticonEntity(1, "╰(✧∇✧╰)", false),
                EmoticonEntity(1, "٩(◕ั ∀◕ั๑٩)", false),
                EmoticonEntity(1, "٩(•౪•٩)三", false),
                EmoticonEntity(1, "₍•͟ ͜ • ₎", false),
                EmoticonEntity(1, "q(^-^q)", false),
                EmoticonEntity(1, "＼（・c＿・●）ゞ", false),
                EmoticonEntity(1, "۹⌤_⌤۹", false),
                EmoticonEntity(1, "ヾ(０∀０*★)ﾟ*･.｡", false),
                EmoticonEntity(1, "ヾ│・ェ・ヾ│", false),
                EmoticonEntity(1, "╰(・∇・╰)", false),
                EmoticonEntity(1, "。（＞ω＜。）", false),
                EmoticonEntity(1, "ヾ(･ω･｡)ｼ", false),
                EmoticonEntity(1, "ヾ(･д･ヾ)", false),
                EmoticonEntity(1, "ヽ(´∀｀ヽ)", false),
                EmoticonEntity(1, "ヽ(´ω｀○)ﾉ.+ﾟ*｡:ﾟ+", false),
                EmoticonEntity(1, "ヾ(≧∇≦*)ゝ", false),
                EmoticonEntity(1, "＼（＠￣∇￣＠）／", false),
                EmoticonEntity(1, "＼(^▽^＠)ノ", false),
                EmoticonEntity(1, "ヾ(@^▽^@)ノ", false),
                EmoticonEntity(1, "(((＼（＠v＠）／)))", false),
                EmoticonEntity(1, "＼(*T▽T*)／", false),
                EmoticonEntity(1, "＼（＾▽＾）／", false),
                EmoticonEntity(1, "＼（Ｔ∇Ｔ）／", false),
                EmoticonEntity(1, "ヽ( ★ω★)ノ", false),
                EmoticonEntity(1, "ヽ(；▽；)ノ", false),
                EmoticonEntity(1, "ヾ(。◕ฺ∀◕ฺ)ノ", false),
                EmoticonEntity(1, "ヾ(＠† ▽ †＠）ノ", false),
                EmoticonEntity(1, "ヾ(＠^∇^＠)ノ", false),
                EmoticonEntity(1, "ヾ(＠^▽^＠)ﾉ", false),
                EmoticonEntity(1, "ヾ（＠＾▽＾＠）ノ", false),
                EmoticonEntity(1, "ヾ(＠゜▽゜＠）ノ", false),
                EmoticonEntity(1, "ヾ(@°▽°@)ノ", false),
                EmoticonEntity(1, "ヾ(＠°▽°＠)ﾉ", false),
                EmoticonEntity(1, "ヽ(*≧ω≦)ﾉ", false),
                EmoticonEntity(1, "ヽ(*⌒∇⌒*)ﾉ", false),
                EmoticonEntity(1, "ヽ(^。^)丿", false),
                EmoticonEntity(1, "ヽ(＾Д＾)ﾉ", false),
                EmoticonEntity(1, "ヽ(=^･ω･^=)丿", false),
                EmoticonEntity(1, "⸂⸂⸜(രᴗര๑)⸝⸃⸃", false),
                EmoticonEntity(1, "⸜(ّᶿധّᶿ)⸝", false),
                EmoticonEntity(1, "ヽ(｡･ω･｡)ﾉ", false),
                EmoticonEntity(1, "╰(‘ω’ )╯", false),
                EmoticonEntity(1, "╰(°ㅂ°)╯", false),
                EmoticonEntity(1, "┗(＾∀＾)┛", false),
                EmoticonEntity(1, "ヾ(๑’౪`๑)ﾉﾞ", false),
                EmoticonEntity(1, "ヾ(*Őฺ∀Őฺ*)ﾉ", false),
                EmoticonEntity(1, "╰(✧∇✧)╯", false),
                EmoticonEntity(1, "ヾ(๑⃙⃘´ꇴ｀๑⃙⃘)ﾉ", false),
                EmoticonEntity(1, "✯⸜(ّᶿ̷ധّᶿ̷)⸝✯", false),
                EmoticonEntity(1, "◦°˚\\(´°౪°`)/˚°◦", false),
                EmoticonEntity(1, "\\(-ㅂ-)/", false),
                EmoticonEntity(1, "◦°˚\\(*❛‿❛)/˚°◦", false),
                EmoticonEntity(1, "╰(◉ᾥ◉)╯", false),
                EmoticonEntity(1, "⌒°(ᴖ◡ᴖ)°⌒", false),
                EmoticonEntity(1, "ヾ(´∀｀○)ﾉ", false),
                EmoticonEntity(1, "｡ﾟ✶ฺ.ヽ(*´∀`*)ﾉ.✶ฺﾟ｡", false),
                EmoticonEntity(1, "＼(;ﾟ∇ﾟ)/", false),
                EmoticonEntity(1, "ヽ(*´∀`)ﾉﾞ", false),
                EmoticonEntity(1, "⸂⸂⸜(ೆ௰ೆ๑)⸝⸃⸃", false),
                EmoticonEntity(1, "✧⁺⸜(●′▾‵●)⸝⁺✧", false),
                EmoticonEntity(1, "ヾ(`ω`　)/", false),
                EmoticonEntity(1, "◦°˚\\☻/˚°◦", false),
                EmoticonEntity(1, "ヾ(｡^ω^｡)ノ", false),
                EmoticonEntity(1, "⸜(ّᶿॕധّᶿॕ)⸝", false),
                EmoticonEntity(1, "⸜(ؔᶿധؔᶿ)⸝", false),
                EmoticonEntity(1, "╰( ･ ᗜ ･ )╯", false),
                EmoticonEntity(1, "┏○ ＼(ﾟ 0ﾟ ;)/┓", false),
                EmoticonEntity(1, "  ヽ(^◇^*)/", false),
                EmoticonEntity(1, "ヾ(≧∇≦)ゞ", false),
                EmoticonEntity(1, "o͡͡͡͡͡͡͡͡͡͡͡͡͡͡╮(^ ਊ ^)╭o͡͡͡͡͡͡͡͡͡͡͡͡͡͡", false),
                EmoticonEntity(1, "☆*~ﾟ⌒(‘-‘*)⌒ﾟ~*☆", false),
                EmoticonEntity(1, "ヽ(ﾟ∀ﾟ)ﾉ", false),
                EmoticonEntity(1, "ヾ(o≧∀≦o)ﾉﾞ", false),
                EmoticonEntity(1, ".｡ﾟ+.ヽ| ゝ∀・*|ﾉ｡+.ﾟ", false),
                EmoticonEntity(1, "(ﾟ<|＼(･ω･)／|>ﾟ)", false),
                EmoticonEntity(1, "╰| ° ◞౪◟ ° |╯", false),
                EmoticonEntity(1, "ヽ༼>ل͜<༽ﾉ", false),
                EmoticonEntity(1, "ヽ[ヘ ل͟ ヘ]╯", false),
                EmoticonEntity(1, "＼(・ω・)/", false),
                EmoticonEntity(1, "ヽ（゜ω゜○）ノ", false),
                EmoticonEntity(1, "☆~~ヾ(>▽<)ﾉ｡･☆", false),
                EmoticonEntity(1, "＼（*´･∀･｀*）／", false),
                EmoticonEntity(1, "＼（゜э゜）／", false),
                EmoticonEntity(1, "ヾ(￣◇￣)ノ", false),
                EmoticonEntity(1, "ヾ【*≧д≦】ノ", false),
                EmoticonEntity(1, "ヽ(^O^)ノ", false),
                EmoticonEntity(1, "ヾ(´▽｀*)ﾉ☆", false),
                EmoticonEntity(1, "ヾ(・∀・｀*)ﾉ☆", false),
                EmoticonEntity(1, "☆ヾ(*´▽｀)ﾉ", false),
                EmoticonEntity(1, "☆ヾ(*´・∀・)ﾉ", false),
                EmoticonEntity(1, "ヾ(*・ω・)ノ", false),
                EmoticonEntity(1, "ヾ(・ω・*)ノ", false),
                EmoticonEntity(1, "ヽ( ´￢`)ﾉ", false),
                EmoticonEntity(1, "ヾ(≧∪≦*)ノ〃", false),
                EmoticonEntity(1, "ヾ(*ゝω・*)ノ", false),
                EmoticonEntity(1, "＼（○＾ω＾○）／", false),
                EmoticonEntity(1, "╰(*´︶`*)╯", false),
                EmoticonEntity(1, "ヽ( ´ー`)ノ", false),
                EmoticonEntity(1, "┝＼( ‘∇^*)^☆／┥", false),
                EmoticonEntity(1, "ヽ(^o^)丿", false),
                EmoticonEntity(1, "┗|⌒O⌒|┛", false),
                EmoticonEntity(1, "┗|・o・|┛", false),
                EmoticonEntity(1, "ヾ(●・◇・●)ノ", false),
                EmoticonEntity(1, "ヽ( ‘ω’ )ﾉ", false),
                EmoticonEntity(1, "((ヾ(* ´∀｀)ノ))", false),
                EmoticonEntity(1, "ヽ(´∇｀)ﾉ", false),
                EmoticonEntity(1, "･:*+.\\(( °ω° ))/.:+", false),
                EmoticonEntity(1, "ヽ(^□^｡)ノ", false),
                EmoticonEntity(1, "ヾ(o✪‿✪o)ｼ", false),
                EmoticonEntity(1, "＼(*ﾟ∀ﾟ*)／", false),
                EmoticonEntity(1, "＼(*^￢^*)／", false),
                EmoticonEntity(1, "Ψ(≧ω≦)Ψ", false),
                EmoticonEntity(1, "ヽ(*≧л≦)ﾉ", false),
                EmoticonEntity(1, "*。ヾ(｡>ｖ<｡)ﾉﾞ*。", false),
                EmoticonEntity(1, "҉*\\( ‘ω’ )/*҉", false),
                EmoticonEntity(1, "(* >ω<)", false),
                EmoticonEntity(1, "(*≧▽≦)", false),
                EmoticonEntity(1, "(๑>ᴗ<๑)", false),
                EmoticonEntity(1, "( ˃̶ω˂̶ ૃ)", false),
                EmoticonEntity(1, "(٭°̧̧̧ω°̧̧̧٭)", false),
                EmoticonEntity(1, "⸍⚙̥ꇴ⚙̥⸌", false),
                EmoticonEntity(1, "(⊙ꇴ⊙)", false),
                EmoticonEntity(1, "(*≧∀≦*)", false),
                EmoticonEntity(1, "(≧∇≦*)", false),
                EmoticonEntity(1, "（๑✧∀✧๑）", false),
                EmoticonEntity(1, "(★^O^★)", false),
                EmoticonEntity(1, "(ᗒᗨᗕ)", false),
                EmoticonEntity(1, "(⌯꒪͒ ꌂ̇ ꒪͒)", false),
                EmoticonEntity(1, "(≧∀≦)", false),
                EmoticonEntity(1, "(⌬̀⌄⌬́)", false),
                EmoticonEntity(1, "₊·*◟(˶╹̆ꇴ╹̆˵)◜‧*･", false),
                EmoticonEntity(1, "(ᗒᏬᗕ) ˡ̵˖✮⃛", false),
                EmoticonEntity(1, "(ؑ⸍⸍ᵕؑ̇⸍⸍)◞✧", false),
                EmoticonEntity(1, "✮⃛( ◞´•௰•`)✮⃛", false),
                EmoticonEntity(1, "(ؑᵒᵕؑ̇ᵒ)◞✧", false),
                EmoticonEntity(1, "₍₍ ◝(●˙꒳˙●)◜ ₎₎", false),
                EmoticonEntity(1, "(´｡✪ω✪｡｀)", false),
                EmoticonEntity(1, "｡;+*(★`∪´☆)*+;｡", false),
                EmoticonEntity(1, "(๑˃̶͈̀o˂̶͈́๑)", false),
                EmoticonEntity(1, "≧ω≦", false),
                EmoticonEntity(1, "٩(^ᴗ^)۶", false),
                EmoticonEntity(1, "٩(๑꒦ິȏ꒦ິ๑)۶", false),
                EmoticonEntity(1, "٩(●˙▿˙●)۶…⋆ฺ", false),
                EmoticonEntity(1, "٩(๑ơలơ)۶♡", false),
                EmoticonEntity(1, "୧(﹒︠ᴗ﹒︡)୨", false),
                EmoticonEntity(1, "٩(ó｡ò۶ ♡)))♬", false),
                EmoticonEntity(1, "ε٩( ºωº )۶з", false),
                EmoticonEntity(1, "٩(๑òωó๑)۶", false),
                EmoticonEntity(1, "٩( ๑^ ꇴ^)۶", false),
                EmoticonEntity(1, "٩(๑˃́ꇴ˂̀๑)۶", false),
                EmoticonEntity(1, "٩(๑∂▿∂๑)۶♡", false),
                EmoticonEntity(1, "٩(♡ε♡ )۶", false),
                EmoticonEntity(1, "۹(ÒہÓ)۶", false),
                EmoticonEntity(1, "٩(⚙ȏ⚙)۶", false),
                EmoticonEntity(1, "٩(✿∂‿∂✿)۶", false),
                EmoticonEntity(1, "୧⍢⃝୨", false),
                EmoticonEntity(1, "⁽⁽٩(๑˃̶͈̀ ᗨ ˂̶͈́)۶⁾⁾", false),
                EmoticonEntity(1, "(୨৩́ಐ৩̀੧)", false),
                EmoticonEntity(1, "٩(;ʘ¿ʘ;)۶", false),
                EmoticonEntity(1, "=。:.ﾟ٩(๑>ω<๑)۶:.｡+ﾟ", false),
                EmoticonEntity(1, "٩(˘◊˘)۶", false),
                EmoticonEntity(1, "٩(*ゝڡゝ๑)۶♥", false),
                EmoticonEntity(1, "٩(｡θᗨθ｡)۶", false),
                EmoticonEntity(1, "٩(⚙ᴗ⚙)۶", false),
                EmoticonEntity(1, "୧(˃◡ु˂)୨", false),
                EmoticonEntity(1, "۹(˒௰˓)۶", false),
                EmoticonEntity(1, "٩(●ᴗ●)۶", false),
                EmoticonEntity(1, "♡〜٩( ˃́▿˂̀ )۶〜♡", false),
                EmoticonEntity(1, "٩(º౪º๑)۶", false),
                EmoticonEntity(1, "=。:.ﾟ٩(๑>◊<๑)۶:.｡+ﾟ", false),
                EmoticonEntity(1, "٩(๑❛ᴗ❛๑)۶", false),
                EmoticonEntity(1, "୧| ͡ᵔ ﹏ ͡ᵔ |୨", false),
                EmoticonEntity(1, "୧〳 ” ʘ̆ ᗜ ʘ̆ ” 〵୨", false),
                EmoticonEntity(1, "٩(๑❛ʚ❛๑)۶", false),
                EmoticonEntity(1, "٩(இ ⌓ இ๑)۶", false),
                EmoticonEntity(1, "୧| ” •̀ ل͜ •́ ” |୨", false),
                EmoticonEntity(1, "୧( , ＾ 〰 ＾ , )୨", false),
                EmoticonEntity(1, "٩| ര ‿ ര |╯", false),
                EmoticonEntity(1, "୧〳 ＾ ౪ ＾ 〵୨", false),
                EmoticonEntity(1, "୧( ˵ ° ~ ° ˵ )୨", false),
                EmoticonEntity(1, "୧། ☉ ౪ ☉ །୨", false),
                EmoticonEntity(1, "୧༼ ヘ ᗜ ヘ ༽୨", false),
                EmoticonEntity(1, "❣࿌ིྀ྇°˚࿅୧( ॑ധ ॑)୨࿅˳०࿌ིྀ྇", false),
                EmoticonEntity(1, "٩(◦`꒳´◦)۶", false),
                EmoticonEntity(1, "٩(๑˃̌ۿ˂̌๑)۶", false),
                EmoticonEntity(1, "٩(θ‿θ)۶", false),
                EmoticonEntity(1, "(⁼̴̀ૢ꒳​⁼̴́ૢ๑)", false),
                EmoticonEntity(1, "ෆු(*˃ர்˂*)ෆු", false),
                EmoticonEntity(1, "(ٛɲ˃ ˑ̣̮ ˂ٛɳ)", false),
                EmoticonEntity(1, "d(๑꒪່౪̮꒪່๑)b", false),
                EmoticonEntity(1, "( ˃̆ૢ௰˂̆ૢഃ )", false),
                EmoticonEntity(1, "ლ(*꒪ヮ꒪*)ლ", false),
                EmoticonEntity(1, "૮(ᶿ̴͈᷇ॢ௰ᶿ̴͈᷆ॢ)ა✧", false),
                EmoticonEntity(1, "∗˚(* ˃̤൬˂̤ *)˚∗", false),
                EmoticonEntity(1, "б（＞ε＜）∂", false),
                EmoticonEntity(1, "∩|*`・ρ・´|∩", false),
                EmoticonEntity(1, "(gΦ皿Φ)g〃 ", false),
                EmoticonEntity(1, "о(ж＞▽＜)ｙ ☆", false),
                EmoticonEntity(1, "*＼( *ω*)┓", false),
                EmoticonEntity(1, "โ๏∀๏ใ", false),
                EmoticonEntity(1, "癶(癶✺౪✺ )癶", false),
                EmoticonEntity(1, "⊂((〃≧▽≦〃))⊃", false),
                EmoticonEntity(1, "~(≧◇≦)/ﾞﾞﾞﾞ", false),
                EmoticonEntity(1, "(*•̀ᴗ•́*)و ̑̑", false),
                EmoticonEntity(1, "╭( ･ㅂ･)و ̑̑", false),
                EmoticonEntity(1, "(๑•̀ㅂ•́)و", false),
                EmoticonEntity(1, "(๑˃̵ᴗ˂̵)و", false),
                EmoticonEntity(1, "╭( ･ㅂ･)و", false),
                EmoticonEntity(1, "( •̀ᄇ• ́)ﻭ✧", false),
                EmoticonEntity(1, "(ര̀ᴗര́)و ̑̑", false),
                EmoticonEntity(1, "╭(♡･ㅂ･)و ̑̑", false),
                EmoticonEntity(1, "◝( ′ㅂ`)و ̑̑", false),
                EmoticonEntity(1, "╭( ･ㅂ･)و ̑̑ ＂", false),
                EmoticonEntity(1, "╭( ･ㅂ･)و )))", false),
                EmoticonEntity(1, "╭(๑ ॔ㅂ ਂ ॓)و ̑̑", false),
                EmoticonEntity(1, "( ⁼̴̤̆ ළ̉ ⁼̴̤̆)و ̑̑", false),
                EmoticonEntity(1, "(๑˃̵ᴗ˂̵)و", false),
                EmoticonEntity(1, " (๑•̀ㅂ•́)و✧", false),
                EmoticonEntity(1, "꒰๑͒•̀ुꇵ͒•꒱و ̑̑", false),
                EmoticonEntity(1, "ଘ꒰ ๑ ˃̶ ᴗ ᵒ̴̶̷๑꒱و ̑̑", false),
                EmoticonEntity(1, "(ฅ⁍̴̀◊⁍̴́)و ̑̑", false),
                EmoticonEntity(1, "╭( ･ㅂ･)و ̑̑ ˂ᵒ͜͡ᵏᵎ⁾✩", false),
                EmoticonEntity(1, "(•́⌄•́๑)૭✧", false),
                EmoticonEntity(1, "(•̀ᴗ•́)൬༉", false),
                EmoticonEntity(1, "!(•̀ᴗ•́)و ̑̑", false),
                EmoticonEntity(1, "٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ", false),
                EmoticonEntity(1, "ೕ(`･୰･´)", false),
                EmoticonEntity(1, "ೕ(･ㅂ･ )", false),
                EmoticonEntity(1, "ೕ(•̀ᴗ•́)", false),
                EmoticonEntity(1, "٩(ര̀ᴗര́)", false),
                EmoticonEntity(1, "ೕ(˃̵ᴗ˂̵ ๑)", false),
                EmoticonEntity(1, "ೕ(•̀ㅂ•́ )", false),
                EmoticonEntity(1, "✧٩(•́⌄•́๑)", false),
                EmoticonEntity(1, "ೕ(⁍̴̀◊⁍̴́ฅ)", false),
                EmoticonEntity(1, "٩(｡•ω•｡)و", false),
                EmoticonEntity(1, "٩(⸝⸝⸝◕ั ௰ ◕ั⸝⸝⸝ )و", false),
                EmoticonEntity(1, "٩(✪ꀾ⍟༶)و", false),
                EmoticonEntity(1, "୧( ⁼̴̶̤̀ω⁼̴̶̤́ )૭", false),
                EmoticonEntity(1, "٩(˃̶͈̀௰˂̶͈́)و", false),
                EmoticonEntity(1, "٩( ‘ω’ )و", false),
                EmoticonEntity(1, "٩(｡•ㅅ•｡)و", false),
                EmoticonEntity(1, "٩( ´･ш･)و", false),
                EmoticonEntity(1, "٩(•̤̀ᵕ•̤́๑)૭✧", false),
                EmoticonEntity(1, "ː̗̀٩꒰ꋃ꒱وː̖́", false),
                EmoticonEntity(1, "٩(๑❛ワ❛๑)و", false),
                EmoticonEntity(1, "(۶•̀ᴗ•́)۶", false),
                EmoticonEntity(1, "٩( ᐛ )و", false),
                EmoticonEntity(1, "✧٩(•́⌄•́๑)و ✧", false),
                EmoticonEntity(1, "ೕ(`･୰･´)و ̑̑", false),
                EmoticonEntity(1, "٩(๑•̀ㅂ•́)و", false),
                EmoticonEntity(1, "٩(๑˃̵ᴗ˂̵)و", false),
                EmoticonEntity(1, "(((ೕ( ･ㅂ･)و )))", false),
                EmoticonEntity(1, "٩( ′ㅂ`)و ̑̑", false),
                EmoticonEntity(1, "٩(ˊᗜˋ*)و", false),
                EmoticonEntity(1, "(و ˃̵ᴗ˂̵)و", false),
                EmoticonEntity(1, "(ง ͡ʘ ͜ʖ ͡ʘ)ง", false),
                EmoticonEntity(1, "(ง ͠ ͠° ل͜ °)ง", false),
                //SUNGLASSES
                EmoticonEntity(2, "▨-▨¬ლ(•_•) (▨_▨¬)", false),
                EmoticonEntity(2, "(⌐▨_▨)", false),
                EmoticonEntity(2, "(⌐■_■)", false),
                EmoticonEntity(2, "(*▼▽▼*)", false),
                EmoticonEntity(2, "ヽ(⌐■_■)ノ♪♬", false),
                EmoticonEntity(2, "(▼皿▼ﾒ)ﾉ", false),
                EmoticonEntity(2, "┌(▀Ĺ̯ ▀-͠ )┐", false),
                EmoticonEntity(2, "( ͡° ͜ʖ ͡°)>⌐■-■", false),
                EmoticonEntity(2, "ლ(▀̿̿Ĺ̯̿̿▀̿ლ)", false),
                EmoticonEntity(2, "༼⌐■ل͜■༽", false),
                EmoticonEntity(2, "(*▼o▼*)ノ", false),
                EmoticonEntity(2, "(ﾒ■_■)y-～", false),
                EmoticonEntity(2, "( •_•)>⌐■-■", false),
                EmoticonEntity(2, "//(*▼▽▼)∩//", false),
                EmoticonEntity(2, "◎(▼●▼)◎ｙ－゜゜゜", false),
                EmoticonEntity(2, "凸（◆◆メ", false),
                EmoticonEntity(2, "σ(*▼▽▼*)", false),
                EmoticonEntity(2, "Σ(▼□▼ﾒ)", false),
                EmoticonEntity(2, "σ(＊▼‐▼＊)", false),
                EmoticonEntity(2, "(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄", false),
                EmoticonEntity(2, "ಠ_ರೃ", false),
                EmoticonEntity(2, "┌(▼▼メ)┘", false),
                EmoticonEntity(2, "└( ▼▼ )┐", false),
                EmoticonEntity(2, "┌(メ▼▼)┘", false),
                EmoticonEntity(2, "ヽ( ▼∀▼)ﾉ", false),
                EmoticonEntity(2, "ヾ(*●Д●)ﾉ゛", false),
                EmoticonEntity(2, "v(▼ω▼ﾒ)ゞ", false),
                EmoticonEntity(2, "┌(▀Ĺ̯▀)┐", false),
                EmoticonEntity(2, "༼⌐■ل͟■༽", false),
                EmoticonEntity(2, "(▼∀▼)", false),
                EmoticonEntity(2, "(▼-▼*)", false),
                EmoticonEntity(2, "▼ω▼", false),
                EmoticonEntity(2, "(ﾒ▼_▼)", false),
                EmoticonEntity(2, "( ▼Д▼)y─┛~~", false),
                EmoticonEntity(2, "ヽ(▼ｰ▼ｷ)", false),
                EmoticonEntity(2, "(▼へ▼ﾒ)σ", false),
                EmoticonEntity(2, "(ﾒ▼皿▼)ノ　⌒　○┼＜", false),
                EmoticonEntity(2, "(▼O▼ﾒ)", false),
                EmoticonEntity(2, "(ｷ▼O▼)/", false),
                EmoticonEntity(2, "|*▼皿▼)", false),
                EmoticonEntity(2, "（▼(00）▼ﾒ）", false),
                EmoticonEntity(2, "(｡▼皿▼)σ", false),
                EmoticonEntity(2, "~~・-v(▼、▼ﾒ)", false),
                EmoticonEntity(2, "ヽ(▼皿▼ヽ)", false),
                EmoticonEntity(2, "(ﾉ▼皿▼)ﾉ", false),
                EmoticonEntity(2, "(▼ω▼o)y-~~~", false),
                EmoticonEntity(2, "(▼皿▼)y-.｡o○", false),
                EmoticonEntity(2, "(▼皿▼#)", false),
                EmoticonEntity(2, "ヾ(▼ﾍ▼；)", false),
                EmoticonEntity(2, "(▼▽▼)人(▼▽▼)", false),
                EmoticonEntity(2, "щ(▼ﾛ▼щ)", false),
                EmoticonEntity(2, "(ｷ▼⊿▼)ﾉ", false),
                EmoticonEntity(2, "（▼∀▼）", false),
                EmoticonEntity(2, "-●-●-ヽ(｀∀´)ゝ", false),
                EmoticonEntity(2, "(ง⌐□ل͜□)ง", false),
                EmoticonEntity(2, "(७⌐■ل͟■)७", false),
                EmoticonEntity(2, "ヽ༼ຈل͜ರೃ༽ﾉ", false),
                EmoticonEntity(2, "ヽ( ͡°╭͜ʖ╮͡ರೃ )ﾉ", false),
                EmoticonEntity(2, "ᕕ༼⌐■-■༽ᕗ", false),
                EmoticonEntity(2, "(ง⌐□ل͜□)", false),
                EmoticonEntity(2, "[ ಠ Ĺ̯ ಠೃ ]", false),
                EmoticonEntity(2, "[ . ಠ o ಠೃ . ]", false),
                EmoticonEntity(2, "( ▀ 益 ▀ )", false),
                EmoticonEntity(2, "ヾ(*▼・▼)ﾉ⌒☆", false),
                EmoticonEntity(2, "(メ▼ー▼)/●~*", false),
                EmoticonEntity(2, "*~●＼(▼ー▼メ)", false),
                EmoticonEntity(2, "（■Д■*）", false),
                EmoticonEntity(2, "（♯▼皿▼）", false),
                EmoticonEntity(2, "(‡▼益▼)", false),
                EmoticonEntity(2, "( ╬◣ 益◢）y━･~", false),
                EmoticonEntity(2, "(ｷ▼д▼)y─┛~~ﾟﾟﾟ", false),
                EmoticonEntity(2, "(*´∀｀）ヽ＜◆－◆＞→（*◆T◆）", false),
                EmoticonEntity(2, "♪(*・д・)ﾉ●-●", false),
                EmoticonEntity(2, "“o(▼皿▼メ;)o”", false),
                EmoticonEntity(2, "(メノ▼□▼)ノ", false),
                EmoticonEntity(2, "ヾ(●ε●)ノ", false),
                EmoticonEntity(2, "(╭ರ_•́)", false),
                EmoticonEntity(2, "(つ▀¯▀)つ", false),
                //ANGRY
                EmoticonEntity(3, "凸(｀0´)凸", false),
                EmoticonEntity(3, "凸ಠ益ಠ)凸", false),
                EmoticonEntity(3, "凸(⊙▂⊙✖ )", false),
                EmoticonEntity(3, "┌П┐(►˛◄’!)", false),
                EmoticonEntity(3, "凸(-0-メ)", false),
                EmoticonEntity(3, "凸(｀⌒´メ)凸", false),
                EmoticonEntity(3, "凸(｀△´＋）", false),
                EmoticonEntity(3, "( ︶︿︶)_╭∩╮", false),
                EmoticonEntity(3, "凸(｀ι _´メ）", false),
                EmoticonEntity(3, "凸(>皿<)凸", false),
                EmoticonEntity(3, "凸(^▼ｪ▼ﾒ^)", false),
                EmoticonEntity(3, "t(=n=)", false),
                EmoticonEntity(3, "t(- n -)t", false),
                EmoticonEntity(3, "凸(¬‿¬)", false),
                EmoticonEntity(3, "┌∩┐(◣_◢)┌∩┐", false),
                EmoticonEntity(3, "┌∩┐(ಠ_ಠ)┌∩┐", false),
                EmoticonEntity(3, "╭∩╮(︶︿︶)╭∩╮", false),
                EmoticonEntity(3, "╭∩╮(-_-)╭∩╮", false),
                EmoticonEntity(3, "( ≧Д≦)", false),
                EmoticonEntity(3, "(；￣Д￣）", false),
                EmoticonEntity(3, "(;¬_¬)", false),
                EmoticonEntity(3, "（；¬＿¬)", false),
                EmoticonEntity(3, "(｡+･`ω･´)", false),
                EmoticonEntity(3, "｡゜(｀Д´)゜｡", false),
                EmoticonEntity(3, "(　ﾟДﾟ)＜!!", false),
                EmoticonEntity(3, "(‡▼益▼)", false),
                EmoticonEntity(3, "(,,#ﾟДﾟ)", false),
                EmoticonEntity(3, "(҂⌣̀_⌣́)", false),
                EmoticonEntity(3, "(；¬д¬)", false),
                EmoticonEntity(3, "（;≧皿≦）", false),
                EmoticonEntity(3, "(╬ﾟ◥益◤ﾟ)", false),
                EmoticonEntity(3, "(╬⓪益⓪)", false),
                EmoticonEntity(3, "[○･｀Д´･○]", false),
                EmoticonEntity(3, "૮( ᵒ̌▱๋ᵒ̌ )ა", false),
                EmoticonEntity(3, "(⁎˃ᆺ˂)", false),
                EmoticonEntity(3, "(ꐦ°᷄д°᷅)", false),
                EmoticonEntity(3, "((╬●∀●)", false),
                EmoticonEntity(3, "(╬ Ò ‸ Ó)", false),
                EmoticonEntity(3, "( >д<)", false),
                EmoticonEntity(3, "(*｀益´*)", false),
                EmoticonEntity(3, "(☞◣д◢)☞", false),
                EmoticonEntity(3, "<(｀^´)>", false),
                EmoticonEntity(3, "(;｀O´)o", false),
                EmoticonEntity(3, "(ꐦ ಠ皿ಠ )", false),
                EmoticonEntity(3, "（｀Δ´）！", false),
                EmoticonEntity(3, "(*｀Ω´*)", false),
                EmoticonEntity(3, "(╬ಠ益ಠ)", false),
                EmoticonEntity(3, "(╬ﾟ◥益◤ﾟ) ╬ﾟ", false),
                EmoticonEntity(3, "(ு⁎ு)྆྆", false),
                EmoticonEntity(3, "(╬⓪益⓪)", false),
                EmoticonEntity(3, " （╬ಠ益ಠ)", false),
                EmoticonEntity(3, "(●o≧д≦)o", false),
                EmoticonEntity(3, "=͟͟͞͞( •̀д•́)))", false),
                EmoticonEntity(3, "(๑･`▱´･๑)", false),
                EmoticonEntity(3, "༼ つ ͠° ͟ ͟ʖ ͡° ༽つ", false),
                EmoticonEntity(3, "(☄ฺ◣д◢)☄ฺ", false),
                EmoticonEntity(3, "Щ(◣д◢)Щ", false),
                EmoticonEntity(3, "ꀯ(‴ꑒ᷅⺫ꑒ᷄)", false),
                EmoticonEntity(3, "(#｀皿´)", false),
                EmoticonEntity(3, " (｀Д´)", false),
                EmoticonEntity(3, " (ﾒﾟ皿ﾟ)", false),
                EmoticonEntity(3, "(o｀ﾟ皿ﾟ)", false),
                EmoticonEntity(3, "( ╬◣ 益◢)", false),
                EmoticonEntity(3, " （╬ಠ益ಠ)", false),
                EmoticonEntity(3, "（♯▼皿▼）", false),
                EmoticonEntity(3, "( ╬◣ 益◢）y━･~", false),
                EmoticonEntity(3, " （○｀Ｏ´○）", false),
                EmoticonEntity(3, "(; ･`д･´)", false),
                EmoticonEntity(3, " ｜。｀＞Д＜｜", false),
                EmoticonEntity(3, "(; ･`д･´)​", false),
                EmoticonEntity(3, "( •̀ω•́ )σ", false),
                EmoticonEntity(3, "o(-`д´- ｡)", false),
                EmoticonEntity(3, "(´･益･｀*)", false),
                EmoticonEntity(3, "(´Д｀)", false),
                EmoticonEntity(3, "(¬д¬。)", false),
                EmoticonEntity(3, "（≧▼≦；)", false),
                EmoticonEntity(3, "(ᇂ∀ᇂ╬)", false),
                EmoticonEntity(3, "(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)", false),
                EmoticonEntity(3, "(ू˃̣̣̣̣̣̣o˂̣̣̣̣̣̣ ू)⁼³₌₃", false),
                EmoticonEntity(3, "（▼へ▼メ）", false),
                EmoticonEntity(3, "｢(#Φ益 Φo)∩", false),
                EmoticonEntity(3, "s(・｀ヘ´・；)", false),
                EmoticonEntity(3, "s(・｀ヘ´・;)ゞ", false),
                EmoticonEntity(3, "Σ(-`Д´-ﾉ；)ﾉ", false),
                EmoticonEntity(3, "Σ(▼□▼メ)", false),
                EmoticonEntity(3, "๛∙᷅῞ॄ∙᷄", false),
                EmoticonEntity(3, "(°ㅂ° ╬)", false),
                EmoticonEntity(3, "( ｰ̀εｰ́ )", false),
                EmoticonEntity(3, "(눈_눈)", false),
                EmoticonEntity(3, "(´◣д◢`+)", false),
                EmoticonEntity(3, "(ʘ言ʘ╬)", false),
                EmoticonEntity(3, "(Ò 皿 Ó ╬)", false),
                EmoticonEntity(3, "(-̀◞८̯◟-́)", false),
                EmoticonEntity(3, "( ͒˃⌂˂ ͒)", false),
                EmoticonEntity(3, "┌(▀Ĺ̯ ▀-͠ )┐", false),
                EmoticonEntity(3, "[⑇⨀ེ⌓⨀ེ•⑇]", false),
                EmoticonEntity(3, "Σ(ﾟд´;ﾉ)ﾉ", false),
                EmoticonEntity(3, "(-̀◞▥◟-́)", false),
                EmoticonEntity(3, "☜(`o´)", false),
                EmoticonEntity(3, "(◎益◎;)", false),
                EmoticonEntity(3, "(@益@ .:;)", false),
                EmoticonEntity(3, "ꉂ `o´ )", false),
                EmoticonEntity(3, "ಠ_ರೃ", false),
                EmoticonEntity(3, "(*｀へ´*)", false),
                EmoticonEntity(3, "-`д´-", false),
                EmoticonEntity(3, "(*≧m≦*)", false),
                EmoticonEntity(3, "(*￣m￣)", false),
                EmoticonEntity(3, "(>人<)", false),
                EmoticonEntity(3, "(¬_¬)", false),
                EmoticonEntity(3, "(#ಠQಠ#)", false),
                EmoticonEntity(3, "(¬､¬)", false),
                EmoticonEntity(3, "( ಠ ಠ )", false),
                EmoticonEntity(3, "(¬▂¬)", false),
                EmoticonEntity(3, "(⋋▂⋌)", false),
                EmoticonEntity(3, "(>_<)", false),
                EmoticonEntity(3, "（＞д＜）", false),
                EmoticonEntity(3, "(≧σ≦)", false),
                EmoticonEntity(3, "(◣_◢)", false),
                EmoticonEntity(3, "(ಠ⌣ಠ)", false),
                EmoticonEntity(3, "(ಥ⌣ಥ)", false),
                EmoticonEntity(3, "ŎUŎ", false),
                EmoticonEntity(3, "ಠ_ಠ", false),
                EmoticonEntity(3, "ಠ▃ಠ", false),
                EmoticonEntity(3, "ಥ⌣ಥ", false),
                EmoticonEntity(3, "눈_눈", false),
                EmoticonEntity(3, "(ᗒᗣᗕ)՞", false),
                EmoticonEntity(3, "૮(ꂧ᷆⺫ꂧ᷇)ა", false),
                EmoticonEntity(3, "૮(ꂧꁞꂧ)ა", false),
                EmoticonEntity(3, "૮( ᵒ̌ૢཪᵒ̌ૢ )ა", false),
                EmoticonEntity(3, "(,,Ծ‸Ծ,, )", false),
                EmoticonEntity(3, "(๑•ૅㅁ•๑)", false),
                EmoticonEntity(3, "꒰╬•᷅д•᷄╬꒱", false),
                EmoticonEntity(3, "(╬•᷅д•᷄╬)", false),
                EmoticonEntity(3, " (๑‾᷆д‾᷇๑)", false),
                EmoticonEntity(3, "〴⋋_⋌〵", false),
                EmoticonEntity(3, "ఠ ͟ಠ", false),
                EmoticonEntity(3, "(ఠ్ఠ ˓̭ ఠ్ఠ)", false),
                EmoticonEntity(3, " (*´罒`*)", false),
                EmoticonEntity(3, "（｡ò ∀ ó｡）", false),
                EmoticonEntity(3, " (o´罒`o)", false),
                EmoticonEntity(3, "(๑•॒̀ ູ॒•́๑)", false),
                EmoticonEntity(3, "(｡ì _ í｡)", false),
                EmoticonEntity(3, " (๑ò︵ò๑)", false),
                EmoticonEntity(3, " (⑉･̆⌓･̆⑉)", false),
                EmoticonEntity(3, "₍₍ ◝(•̀ㅂ•́)◟ ⁾⁾", false),
                EmoticonEntity(3, " ૮( ᵒ̌皿ᵒ̌ )ა", false),
                EmoticonEntity(3, " (╬ ‾᷅皿‾᷄ ╬)", false),
                EmoticonEntity(3, "(｡☉︵ ಠ╬)", false),
                EmoticonEntity(3, "( ‾᷅⚰‾᷄ )", false),
                EmoticonEntity(3, " (｀◕‸◕´+)", false),
                EmoticonEntity(3, "(∘⁼̴⃙̀˘︷˘⁼̴⃙́∘)", false),
                EmoticonEntity(3, " (*`д´*)", false),
                EmoticonEntity(3, "▻⃘ ௭ ◅⃘", false),
                EmoticonEntity(3, "˃ʍ˂", false),
                EmoticonEntity(3, "ʕ •̀ o •́ ʔ", false),
                EmoticonEntity(3, " ⋋_⋌", false),
                EmoticonEntity(3, "(o･｀Д´･o)", false),
                EmoticonEntity(3, "( ▀ 益 ▀ )", false),
                EmoticonEntity(3, " （▽д▽）", false),
                EmoticonEntity(3, "╭(๑¯д¯๑)╮", false),
                EmoticonEntity(3, "٩(╬ʘ益ʘ╬)۶", false),
                EmoticonEntity(3, "٩(๑`ȏ´๑)۶", false),
                EmoticonEntity(3, "ｏ( ><)o", false),
                EmoticonEntity(3, "o(>< )o", false),
                EmoticonEntity(3, "ᕙ(⇀‸↼‶)ᕗ", false),
                EmoticonEntity(3, "ᕦ(ò_óˇ)ᕤ", false),
                EmoticonEntity(3, "٩(╬ఠ༬ఠ)و", false),
                EmoticonEntity(3, "٩(๑`^´๑)۶", false),
                EmoticonEntity(3, "٩(//̀Д/́/)۶", false),
                EmoticonEntity(3, "٩(╬ʘ益ʘ╬)۶", false),
                EmoticonEntity(3, "p( Ò ‸ Ó)q ", false),
                EmoticonEntity(3, "\\٩(๑`ȏ´๑)۶//", false),
                EmoticonEntity(3, "＼＼\\٩(๑`^´๑)۶//／／", false),
                EmoticonEntity(3, "୧ʕ ⇀ ⌂ ↼ ʔ୨", false),
                EmoticonEntity(3, "୧༼ಠ益ಠ༽୨", false),
                EmoticonEntity(3, "o(｀Д´*)o", false),
                EmoticonEntity(3, "୧▒ •̀ o •́ ▒୨", false),
                EmoticonEntity(3, "!! o(*≧д≦)o))", false),
                EmoticonEntity(3, "o(-`д´- o)", false),
                EmoticonEntity(3, "୧(๑•̀ᗝ•́)૭", false),
                EmoticonEntity(3, "ೕ(Ò⺫ Ó )೨", false),
                EmoticonEntity(3, "o(｀□´)○", false),
                EmoticonEntity(3, "ฅ(๑*д*๑)ฅ!!", false),
                //ARMED
                EmoticonEntity(4, "(」゜ロ゜)」", false),
                EmoticonEntity(4, "(/ﾟДﾟ)/", false),
                EmoticonEntity(4, "＼(｀0´)／", false),
                EmoticonEntity(4, "ヽ(｀⌒´メ)ノ", false),
                EmoticonEntity(4, "ヽ(●-`Д´-)ノ", false),
                EmoticonEntity(4, "ヽ༼ ಠ益ಠ ༽ﾉ", false),
                EmoticonEntity(4, "(((p(>o<)q)))", false),
                EmoticonEntity(4, "(ノ≧┏Д┓≦)ノ", false),
                EmoticonEntity(4, "(ノಠ益ಠ)ノ", false),
                EmoticonEntity(4, "{{|└(>o< )┘|}}", false),
                EmoticonEntity(4, "＼(・｀(ｪ)・)/", false),
                EmoticonEntity(4, "＼(〇O〇)／", false),
                EmoticonEntity(4, "＼(＠O＠)／", false),
                EmoticonEntity(4, "＼(`O´θ／", false),
                EmoticonEntity(4, "＼( ｀.∀´)／", false),
                EmoticonEntity(4, "＼(>o<)ノ", false),
                EmoticonEntity(4, "ヾ( ･`⌓´･)ﾉﾞ", false),
                EmoticonEntity(4, "ヾ(。◣∀◢。)ﾉ", false),
                EmoticonEntity(4, "ヽ(≧Д≦)ノ", false),
                EmoticonEntity(4, "ヽ(#`Д´)ﾉ", false),
                EmoticonEntity(4, "ヽ(ｏ`皿′ｏ)ﾉ", false),
                EmoticonEntity(4, "┗|｀O´|┛", false),
                EmoticonEntity(4, "ヾ(｡｀Д´｡)ﾉ彡☆", false),
                EmoticonEntity(4, "ヽ(｀◇´)/", false),
                EmoticonEntity(4, "ヽ(´益`)ﾉ", false),
                EmoticonEntity(4, "ヽ(￣д￣;)ノ", false),
                EmoticonEntity(4, "┗(｀皿´)┛", false),
                EmoticonEntity(4, "ヽ(｀δ´)ノ", false),
                EmoticonEntity(4, "└(○｀ε´○)┘", false),
                EmoticonEntity(4, "ヾ(｀◇´)ﾉ彡", false),
                EmoticonEntity(4, "ヾ( ˃̶⺫˂̶｡)ノ", false),
                EmoticonEntity(4, " ─(｡ìдí｡)─", false),
                EmoticonEntity(4, " <!–･”(>0<)”･ –>", false),
                EmoticonEntity(4, "<!– {{(>_<)}} –>", false),
                EmoticonEntity(4, "ﾚ(◣益◢#)ﾍ", false),
                EmoticonEntity(4, " ヽ(｀⌒´)ﾉ", false),
                EmoticonEntity(4, "(☝’益’☝)", false),
                EmoticonEntity(4, "((ヾ(≧皿≦；)ノ＿))", false),
                EmoticonEntity(4, " ＼`•̀益•́´／", false),
                EmoticonEntity(4, "ヾ(｀⌒´メ)ノ″", false),
                EmoticonEntity(4, " ヽ(｀○´)/", false),
                EmoticonEntity(4, "б(*｀・´)∂", false),
                EmoticonEntity(4, "╰༼=ಠਊಠ=༽╯", false),
                EmoticonEntity(4, " ｡ﾟﾟ(」｡≧□≦)」", false),
                EmoticonEntity(4, " (ﾉ｀Д´)ﾉ", false),
                EmoticonEntity(4, "ヽ(♯｀Д´)ﾉ", false),
                EmoticonEntity(4, "ヽ(｀Д´#)ﾉ", false),
                EmoticonEntity(4, " ヽ(｀Д´)ノ", false),
                EmoticonEntity(4, "ヾ(*｀ｪ´*)ﾉ", false),
                EmoticonEntity(4, " ヾ(o｀ｪ´)ﾉ", false),
                EmoticonEntity(4, " ヾ(｀ε´)ﾉ", false),
                EmoticonEntity(4, "ヾ(｡｀Д´｡)ﾉ", false),
                EmoticonEntity(4, "ヾ(ﾒ｀･д･´)ﾉﾞ", false),
                EmoticonEntity(4, "ヽ(o｀Д´o)ﾉ", false),
                EmoticonEntity(4, "ヾ(*｀⌒´*)ﾉ", false),
                EmoticonEntity(4, "((ヾ(≧皿≦ﾒ)ﾉ))", false),
                EmoticonEntity(4, "ヾ(｀д´*)ﾉ", false),
                EmoticonEntity(4, "ヾ(o｀ε´o)ﾉ", false),
                EmoticonEntity(4, "∪ヽ(●-｀Д´-)ノ彡☆", false),
                EmoticonEntity(4, " ╚╚|░☀▄☀░|╝╝", false),
                EmoticonEntity(4, "┗曲━（｀益´）━曲┛", false),
                EmoticonEntity(4, "( ꒪Д꒪)ノ", false),
                EmoticonEntity(4, "(＃｀д´)ﾉ", false),
                EmoticonEntity(4, "(･｀ｪ´･)つ", false),
                EmoticonEntity(4, "(； ｀ｪ´ ；)b三b", false),
                EmoticonEntity(4, "θ＼(；￢_￢)", false),
                EmoticonEntity(4, "(ꈨຶꎁꈨຶ)۶”", false),
                EmoticonEntity(4, "┗(•̀へ •́ ╮ )", false),
                EmoticonEntity(4, "(ヾﾉ•᷅ ༬•᷄ )", false),
                EmoticonEntity(4, "( ⓞ⃘ ⺫ ⓞ⃘۶)۶ ੭ྀ", false),
                EmoticonEntity(4, "(ര̀⍨ര́)و ̑̑༉", false),
                EmoticonEntity(4, "(*☆OДo)９　｡+ﾟ", false),
                EmoticonEntity(4, "(☢益☢t)", false),
                EmoticonEntity(4, "v(｀皿´)ﾉ~", false),
                EmoticonEntity(4, "໒( ᓀ ‸ ᓂ )७", false),
                EmoticonEntity(4, "ヽ(*｀Д´*||", false),
                EmoticonEntity(4, "||*｀Д´*)ﾉ", false),
                EmoticonEntity(4, "o(o･`з･´o)ﾉ", false),
                EmoticonEntity(4, "໒( ⇀ ‸ ↼ )७", false),
                EmoticonEntity(4, "(๑•̀ㅁ•́ฅ)", false),
                EmoticonEntity(4, "┗(｀ム´)=З", false),
                EmoticonEntity(4, "ι(｀ロ´)ノ", false),
                EmoticonEntity(4, "(｀∧´メ)ρ))", false),
                EmoticonEntity(4, "໒( : ͡° д °͡ : )७", false)
            )
            return result
        }

    }
}