package com.nitroapps.emoticons.helpers

import com.nitroapps.emoticons.EmoticonEntity

class HelperClass4 {
    companion object {
        fun generateData(): Array<EmoticonEntity> {
            val result = arrayOf(
                //DEAD
                EmoticonEntity(22, "(✖╭╮✖)", false),
                EmoticonEntity(22, "(u_u)", false),
                EmoticonEntity(22, "(ヘ。ヘ)", false),
                EmoticonEntity(22, "ｍ（＿　＿；；ｍ", false),
                EmoticonEntity(22, "(*_*)", false),
                EmoticonEntity(22, "(＊0＊;)", false),
                EmoticonEntity(22, "(#+_+)", false),
                EmoticonEntity(22, "(+_+)", false),
                EmoticonEntity(22, "(×_×;）", false),
                EmoticonEntity(22, "(×_×#", false),
                EmoticonEntity(22, "(=ｘェｘ=)", false),
                EmoticonEntity(22, "(ñ_ñ)", false),
                EmoticonEntity(22, "(o_-)", false),
                EmoticonEntity(22, "(º_º)", false),
                EmoticonEntity(22, "（x_x；）", false),
                EmoticonEntity(22, "（Ω_Ω）", false),
                EmoticonEntity(22, "≖‿≖", false),
                EmoticonEntity(22, "✖‿✖", false),
                EmoticonEntity(22, "꒰✘Д✘◍꒱", false),
                EmoticonEntity(22, "ヾ(×× ) ﾂ", false),
                EmoticonEntity(22, "٩(×̯×)۶", false),
                EmoticonEntity(22, "Σ(๑+⌓ o｡)シ", false),
                EmoticonEntity(22, "へ（>_<へ)", false),
                EmoticonEntity(22, "(｡´✚ฺω✚ฺ｀｡)", false),
                EmoticonEntity(22, "* ूི×̺͡×ू ྀ⁎*☠⁎ꂚ*ᵎᵎᵎ", false),
                EmoticonEntity(22, "╭( ✖_✖ )╮", false),
                EmoticonEntity(22, "(≖͞_≖̥)", false),
                EmoticonEntity(22, "彡(-_-;)彡", false),
                EmoticonEntity(22, "(｡≍ฺ‿ฺ≍ฺ)", false),
                EmoticonEntity(22, "(´×ω×`)", false),
                EmoticonEntity(22, "(´+ω+｀)", false),
                EmoticonEntity(22, "(✖´╹‸╹`✖)", false),
                EmoticonEntity(22, "꒰ლ✘ㅿ✘ლ꒱", false),
                EmoticonEntity(22, "(´×д×`三꒪д꒪ ;)", false),
                EmoticonEntity(22, "(⁎×ㅂ×⁎)༘", false),
                EmoticonEntity(22, "¿ⓧ_ⓧﮌ", false),
                EmoticonEntity(22, "(-Ω-メ)", false),
                EmoticonEntity(22, "( ✖ ਊ ✖)", false),
                EmoticonEntity(22, "⁽͑˙˟́˙̭˟̀˙⁾̉", false),
                EmoticonEntity(22, "c༽✖﹏✖༼ᓄ", false),
                EmoticonEntity(22, "ヽ༼, ͡X ͜ʖ ͡X,༽ﾉ", false),
                EmoticonEntity(22, "ヽ༼xل͜x༽ﾉ", false),
                EmoticonEntity(22, "༼ +ل͟+ ༽", false),
                EmoticonEntity(22, "〓■●＿ ～ □○0", false),
                EmoticonEntity(22, "(X_X) ☜ (◉▂◉ )", false),
                EmoticonEntity(22, "⎧ᴿᴵᴾ⎫◟◟◟◟◟◟◟◟ ❀◟(ó ̯ ò, ", false),
                EmoticonEntity(22, "१|✘`皿′✘|५", false),
                EmoticonEntity(22, "╭✖⊆✖╮", false),
                EmoticonEntity(22, "(((＼（✘෴✘）／)))", false),
                EmoticonEntity(22, "⊆✕ڡ✕⊇", false),
                EmoticonEntity(22, "( ×m×）", false),
                EmoticonEntity(22, "Ｕ×Å×Ｕ", false),
                EmoticonEntity(22, "m(~ー~m)～", false),
                EmoticonEntity(22, "～(m~ー~)m", false),
                EmoticonEntity(22, "m(~ｰ~m)~", false),
                EmoticonEntity(22, "･ﾟﾟ･(×_×)･ﾟﾟ･｡", false),
                EmoticonEntity(22, "┌╏✖_✖╏┘", false),
                EmoticonEntity(22, "(✖﹏✖)", false),
                EmoticonEntity(22, "໒( ” x ͟ʖ x ” )७", false),
                EmoticonEntity(22, "(ꀻꎁꀻ )", false),
                EmoticonEntity(22, "0(:3　)～ =͟͟͞͞(’､3)_ヽ)＿", false),
                EmoticonEntity(22, "ꐑ(*ꐌ◡ꐌꐐ*)࿐࿔࿓", false),
                EmoticonEntity(22, "(+o+)", false),
                EmoticonEntity(22, "୧| ✖ ﹏ ✖ |୨", false),
                EmoticonEntity(22, "〓■●～～=□○0", false),
                EmoticonEntity(22, "m(@益@m)～", false),
                EmoticonEntity(22, "╰▐ ✖ 〜 ✖ ▐╯", false),
                EmoticonEntity(22, "║ : x ل͜ x : ║", false),
                EmoticonEntity(22, "( ✖ ︿ ✖ )", false),
                EmoticonEntity(22, "୧༼ ” ✖ ‸ ✖ ” ༽୨", false),
                EmoticonEntity(22, "( x ~ x )", false),
                EmoticonEntity(22, "Σ(＋Θ＋);", false),
                EmoticonEntity(22, "（*ｘ＿ｘ）", false),
                EmoticonEntity(22, "（×ω×）", false),
                EmoticonEntity(22, "(×□×；)", false),
                EmoticonEntity(22, "꒰⁎×﹏×⁎꒱ ༘ؓ ँั๊ྃ", false),
                EmoticonEntity(22, "∑(✘Д✘๑)", false),
                EmoticonEntity(22, "Σ(×_×;)!", false),
                EmoticonEntity(22, "ゞ(++) シ", false),
                EmoticonEntity(22, "¯\\_| ✖ 〜 ✖ |_/¯", false),
                //CONFUSED
                EmoticonEntity(23, "(・_・ヾ", false),
                EmoticonEntity(23, "｢(ﾟﾍﾟ)", false),
                EmoticonEntity(23, "(・・。)ゞ", false),
                EmoticonEntity(23, "(｀_´)ゞ", false),
                EmoticonEntity(23, "(´−｀) ﾝｰ", false),
                EmoticonEntity(23, "｡(*^▽^*)ゞ", false),
                EmoticonEntity(23, "(^^ゞ", false),
                EmoticonEntity(23, "(^～^;)ゞ", false),
                EmoticonEntity(23, "(￣(エ)￣)ゞ", false),
                EmoticonEntity(23, "(-_-)ゞ゛", false),
                EmoticonEntity(23, "(＃⌒∇⌒＃)ゞ", false),
                EmoticonEntity(23, "(⌒▽⌒)ゞ", false),
                EmoticonEntity(23, "(●´ω｀●)ゞ", false),
                EmoticonEntity(23, "〈(゜。゜)", false),
                EmoticonEntity(23, "「(°ヘ°)", false),
                EmoticonEntity(23, "く（＾_・）ゝ", false),
                EmoticonEntity(23, "σ(´し_｀〃)ゞ", false),
                EmoticonEntity(23, "δ(´д｀; )", false),
                EmoticonEntity(23, "↷( ó╻ò)", false),
                EmoticonEntity(23, "(≖ლ≖๑ )ﾌ", false),
                EmoticonEntity(23, "(;＾◇＾;)ゝ", false),
                EmoticonEntity(23, "(・∧‐)ゞ", false),
                EmoticonEntity(23, "ଽ (৺ੋ ௦ ৺ੋ )৴", false),
                EmoticonEntity(23, "( ;-(ｴ)-)ゞ", false),
                EmoticonEntity(23, "(；´д｀)ゞ", false),
                EmoticonEntity(23, "(≧д≦ヾ)", false),
                EmoticonEntity(23, "｢(ﾟ<ﾟ)ﾞ??", false),
                EmoticonEntity(23, "?(ﾉ)・´ω・(ヾ)", false),
                EmoticonEntity(23, "/(@ﾟﾍﾟ@)", false),
                EmoticonEntity(23, "ಠ_ರೃ", false),
                EmoticonEntity(23, "( •᷄ὤ•᷅)？", false),
                EmoticonEntity(23, "(⊙_◎)", false),
                EmoticonEntity(23, "(⊙_☉)", false),
                EmoticonEntity(23, "(⊙.☉)7", false),
                EmoticonEntity(23, "⁀⊙﹏☉⁀", false),
                EmoticonEntity(23, "●.◉", false),
                EmoticonEntity(23, "(｡☉︵ ಠ╬)", false),
                EmoticonEntity(23, "(๑•̌.•̑๑)ˀ̣ˀ̣", false),
                EmoticonEntity(23, "ʕ•ૅૄ•ʔ", false),
                EmoticonEntity(23, "(๑•ૅૄ•๑)", false),
                EmoticonEntity(23, "| ͠° ▃ °͠ |", false),
                EmoticonEntity(23, "( -_・)?", false),
                EmoticonEntity(23, "▐ ˵ ͠° (oo) °͠ ˵ ▐", false),
                EmoticonEntity(23, "(。ヘ°)", false),
                EmoticonEntity(23, "(´｀;) ？", false),
                EmoticonEntity(23, "( ?´_ゝ｀)", false),
                EmoticonEntity(23, "ヾ(´･ ･｀｡)ノ”", false),
                EmoticonEntity(23, "ヽ(゜Q。)ノ？", false),
                EmoticonEntity(23, "?(*´･д･)ﾉ", false),
                EmoticonEntity(23, "(，，ﾟДﾟ)∩", false),
                EmoticonEntity(23, "（（´‐公‐｀））", false),
                EmoticonEntity(23, "<｜＾□＾#｜/", false),
                EmoticonEntity(23, "(￣■￣;)!?", false),
                EmoticonEntity(23, "(>囗＜?)", false),
                EmoticonEntity(23, "( ⌡ ຶम⌡ ຶ )", false),
                EmoticonEntity(23, "(๑ಕ̴ _̆ ಕ̴) ﾝ？", false),
                EmoticonEntity(23, "(ﾟДﾟ?)", false),
                EmoticonEntity(23, "?(°Д°≡°Д°)?", false),
                EmoticonEntity(23, "(♠_♦)", false),
                EmoticonEntity(23, "(C_C)", false),
                EmoticonEntity(23, "( ⧉ ⦣ ⧉ )", false),
                EmoticonEntity(23, "¿(❦﹏❦)?", false),
                EmoticonEntity(23, "(;´@へ@｀)", false),
                EmoticonEntity(23, "( ؕؔʘ̥̥̥̥ ه ؔؕʘ̥̥̥̥ )?", false),
                EmoticonEntity(23, "﴾͡๏̯͡๏﴿", false),
                EmoticonEntity(23, "`(๑ △ ๑)`*", false),
                EmoticonEntity(23, "٩(̾●̮̮̃̾•̃̾)۶", false),
                EmoticonEntity(23, "꒰๑ऀ •̆ꈊ͒ू•̆๑ऀ꒱⁇", false),
                EmoticonEntity(23, "( ؔ⚈͟ ◡ ؔ⚈͟ ๑)…ﾝ？", false),
                EmoticonEntity(23, "»ू(͒ˑ•᷄͡ꇵ͒•᷅͒)ू?!", false),
                EmoticonEntity(23, "(૦ୂ૦ॢ)ɂ̥Ɂ̥", false),
                EmoticonEntity(23, "(⸝⸝⸝՞̐ˀ̝՞̐ू)˖̛̠͉", false),
                EmoticonEntity(23, "⅀(╹╹͞ू)՞✰⁎", false),
                EmoticonEntity(23, "(•ॢ՞˝̼̮՞)•••Ɂ̥", false),
                EmoticonEntity(23, "(◕ฺ ▿ฺ ◕ฺ)??", false),
                //DANCE
                EmoticonEntity(24, "〜(^∇^〜）", false),
                EmoticonEntity(24, "〜(￣▽￣〜)", false),
                EmoticonEntity(24, "。(⌒∇⌒。)", false),
                EmoticonEntity(24, "（〜^∇^)〜", false),
                EmoticonEntity(24, "(〜￣▽￣)〜", false),
                EmoticonEntity(24, "(。⌒∇⌒)。", false),
                EmoticonEntity(24, "((┌|o^▽^o|┘))♪", false),
                EmoticonEntity(24, "(~‾⌣‾)~", false),
                EmoticonEntity(24, "(~￣▽￣)~", false),
                EmoticonEntity(24, "(~˘▾˘)~", false),
                EmoticonEntity(24, "~(⁰▿⁰)~", false),
                EmoticonEntity(24, "~(‾⌣‾~)", false),
                EmoticonEntity(24, "~(˘▾˘)~", false),
                EmoticonEntity(24, "~(˘▾˘~)", false),
                EmoticonEntity(24, "┌(˘⌣˘)ʃ", false),
                EmoticonEntity(24, "ƪ(˘⌣˘)ʃ", false),
                EmoticonEntity(24, "ƪ(˘⌣˘)┐", false),
                EmoticonEntity(24, "♪((└|o^▽^o|┐))", false),
                EmoticonEntity(24, "(/・・)ノ", false),
                EmoticonEntity(24, "(o´･_･)っ", false),
                EmoticonEntity(24, "(ﾉ･ｪ･)ﾉ", false),
                EmoticonEntity(24, "(ﾉ*ﾟｰﾟ)ﾉ", false),
                EmoticonEntity(24, "(ノ￣ー￣)ノ", false),
                EmoticonEntity(24, "＼(^▽^＠)ノ", false),
                EmoticonEntity(24, "＼(ﾟｰﾟ＼)", false),
                EmoticonEntity(24, "♪(┌・。・)┌", false),
                EmoticonEntity(24, "ヽ(･ω･ゞ)", false),
                EmoticonEntity(24, "ヽ(*ﾟｰﾟ*)ﾉ", false),
                EmoticonEntity(24, "ヽ(^‥^=ゞ)", false),
                EmoticonEntity(24, "〜(^∇^〜）", false),
                EmoticonEntity(24, "〜(￣△￣〜)", false),
                EmoticonEntity(24, "。(⌒∇⌒。)", false),
                EmoticonEntity(24, "( ﾉ^ω^)ﾉﾟ", false),
                EmoticonEntity(24, "（〜^∇^)〜", false),
                EmoticonEntity(24, "(〜￣△￣)〜", false),
                EmoticonEntity(24, "(。⌒∇⌒)。", false),
                EmoticonEntity(24, "₍₍ ◝(・ω・)◟ ⁾⁾", false),
                EmoticonEntity(24, "((┌|o^▽^o|┘))♪", false),
                EmoticonEntity(24, "(*ﾉ´□`)ﾉ", false),
                EmoticonEntity(24, "(~‾⌣‾)~", false),
                EmoticonEntity(24, "(~‾▿‾)~", false),
                EmoticonEntity(24, "(~’.’)~", false),
                EmoticonEntity(24, "(~￣▽￣)~", false),
                EmoticonEntity(24, "(~˘▾˘)~", false),
                EmoticonEntity(24, "(┌ﾟдﾟ)┌", false),
                EmoticonEntity(24, "(o^^)o", false),
                EmoticonEntity(24, "(ﾉ･o･)ﾉ", false),
                EmoticonEntity(24, "(ノ‥)ノ", false),
                EmoticonEntity(24, "(ノ´＿ゝ｀）ノ", false),
                EmoticonEntity(24, "(ノ^_^)ノ", false),
                EmoticonEntity(24, "(ノ^o^)ノ", false),
                EmoticonEntity(24, "(ノ￣ω￣)ノ", false),
                EmoticonEntity(24, "(ノ°ο°)ノ", false),
                EmoticonEntity(24, "(ﾉ≧∀≦)ﾉ", false),
                EmoticonEntity(24, "(ﾉﾟ▽ﾟ)ﾉ", false),
                EmoticonEntity(24, "〈( ^.^)ノ", false),
                EmoticonEntity(24, "", false),
                EmoticonEntity(24, "＼(^ω^＼)", false),
                EmoticonEntity(24, "~(‾⌣‾~)", false),
                EmoticonEntity(24, "~(‾▿‾)~", false),
                EmoticonEntity(24, "~(‾▿‾~)", false),
                EmoticonEntity(24, "~(‘.’~)", false),
                EmoticonEntity(24, "~(˘▾˘)~", false),
                EmoticonEntity(24, "~(˘▾˘~)", false),
                EmoticonEntity(24, "┌(・。・)┘♪", false),
                EmoticonEntity(24, "┌(˘⌣˘)ʃ", false),
                EmoticonEntity(24, "┌（★ｏ☆）┘", false),
                EmoticonEntity(24, "┌(ﾟдﾟ)┘", false),
                EmoticonEntity(24, "┌|゜з゜｜┘", false),
                EmoticonEntity(24, "┌|°з°|┘", false),
                EmoticonEntity(24, "┌U･ｪ･U┘", false),
                EmoticonEntity(24, "┏((＝￣(ｴ)￣=))┛", false),
                EmoticonEntity(24, "┏(｀ー´)┛", false),
                EmoticonEntity(24, "┏(＾0＾)┛", false),
                EmoticonEntity(24, "┐(ﾟдﾟ┐)", false),
                EmoticonEntity(24, "└(^o^)┐", false),
                EmoticonEntity(24, "└(=^‥^=)┐", false),
                EmoticonEntity(24, "└（★ｏ★）┐", false),
                EmoticonEntity(24, "└(ﾟдﾟ)┐", false),
                EmoticonEntity(24, "└@(･ｪ･)@┐", false),
                EmoticonEntity(24, "└｜゜ε゜｜┐", false),
                EmoticonEntity(24, "└|°ε°|┐", false),
                EmoticonEntity(24, "┗(｀ー´)┓", false),
                EmoticonEntity(24, "┗(＾0＾)┓", false),
                EmoticonEntity(24, "♪((└|o^▽^o|┐))", false),
                EmoticonEntity(24, "ヽ( °◇°)ノ", false),
                EmoticonEntity(24, "ヾ(-_- )ゞ", false),
                EmoticonEntity(24, "ヾ(･ω･*)ﾉ", false),
                EmoticonEntity(24, "ヽ(;^o^ヽ)", false),
                EmoticonEntity(24, "ヾ(＠^∇^＠)ノ", false),
                EmoticonEntity(24, "ヾ(*´∇`)ﾉ", false),
                EmoticonEntity(24, "ヽ(*´Д｀*)ﾉ", false),
                EmoticonEntity(24, "ヾ（*⌒ヮ⌒*）ゞ", false),
                EmoticonEntity(24, "ヾ(*д*)ﾉ", false),
                EmoticonEntity(24, "ヾ(´▽｀;)ゝ", false),
                EmoticonEntity(24, "ヽ(´ー`)ﾉ", false),
                EmoticonEntity(24, "ヾ(^ ^ゞ", false),
                EmoticonEntity(24, "ヾ(^^ゞ)", false),
                EmoticonEntity(24, "ヽ(°◇° )ノ", false),
                EmoticonEntity(24, "ヾ(ﾟ∀ﾟゞ)", false),
                EmoticonEntity(24, "ヾ(⌐■_■)ノ♪", false),
                EmoticonEntity(24, "ヽ(⌐■_■)ノ♪♬", false),
                EmoticonEntity(24, "ヽ(ﾟｰﾟ*ヽ)", false),
                EmoticonEntity(24, "o(^^o)", false),
                EmoticonEntity(24, "ƪ(‾.‾“)┐", false),
                EmoticonEntity(24, "ƪ(˘⌣˘)┐", false),
                EmoticonEntity(24, "ƪ(˘⌣˘)ʃ", false),
                EmoticonEntity(24, "ヘ(^_^ヘ)", false),
                EmoticonEntity(24, "ヘ(^o^ヘ)", false),
                EmoticonEntity(24, "ヘ(￣ー￣ヘ)", false),
                EmoticonEntity(24, "ヘ(￣ω￣ヘ)", false),
                EmoticonEntity(24, "⌌⌈╹드╹⌉⌏", false),
                EmoticonEntity(24, "乁( ˙ ω˙乁)", false),
                EmoticonEntity(24, "(｢･ω･)｢", false),
                EmoticonEntity(24, "⁽⁽◝( •௰• )◜⁾⁾", false),
                EmoticonEntity(24, "₍₍◞( •௰• )◟₎₎", false),
                EmoticonEntity(24, "╭(°ㅂ°)╮", false),
                EmoticonEntity(24, "╰(°ㅂ°)╯", false),
                EmoticonEntity(24, "〜(꒪꒳꒪)〜", false),
                EmoticonEntity(24, "ح˚௰˚づ", false),
                EmoticonEntity(24, "(｢`･ω･)｢", false),
                EmoticonEntity(24, "┌|*ﾟｏﾟ|┘", false),
                EmoticonEntity(24, "┌|*ﾟ０ﾟ|┘", false),
                EmoticonEntity(24, "┌|*ﾟ-ﾟ|┘", false),
                EmoticonEntity(24, "┌|*ﾟ｡ﾟ|┘", false),
                EmoticonEntity(24, "✺◟(∗❛ัᴗ❛ั∗)◞✺", false),
                EmoticonEntity(24, "♫͙◟̊₍ꃓ₎◞◟₍ꃔ₎◞̊♫͙", false),
                EmoticonEntity(24, "◟(ꉺᴗꉺ๑◝)", false),
                EmoticonEntity(24, "₍₍(꒪່౪̮꒪່)⁾⁾", false),
                EmoticonEntity(24, "⌌⌈╹므╹⌉⌏", false),
                EmoticonEntity(24, "˺⁽ˆ⁰ˆ˺ ⁾˺", false),
                EmoticonEntity(24, "┌༼▀̿̿Ĺ̯̿̿▀̿༽┘", false),
                EmoticonEntity(24, "ヾ( ͝° ͜ʖ͡°)ノ♪", false),
                EmoticonEntity(24, "˄̙ ̊₍₍◟(⁰^⁰∗)⌟˄̙ ̊", false),
                EmoticonEntity(24, "₍₍◝(°꒳°*)◜₎₎", false),
                EmoticonEntity(24, "↙(ↂ⼼_ↂ)↗", false),
                EmoticonEntity(24, "ﾍ(´∀｀ﾍ)", false),
                EmoticonEntity(24, "(ﾉ´∀｀)ﾉ", false),
                EmoticonEntity(24, "┌(▼▼メ)┘", false),
                EmoticonEntity(24, "└( ▼▼ )┐", false),
                EmoticonEntity(24, "┌(メ▼▼)┘", false),
                EmoticonEntity(24, "┌|ﾟзﾟ|┘", false),
                EmoticonEntity(24, "└|ﾟεﾟ|┐", false),
                EmoticonEntity(24, "┌|ﾟэﾟ|┘", false),
                EmoticonEntity(24, "ヽ(∩。∩゛ヽ)", false),
                EmoticonEntity(24, "(ノ〝∩｡∩)ﾉ", false),
                EmoticonEntity(24, "ゝ(▽｀*ゝ)", false),
                EmoticonEntity(24, "ヾ｜￣ー￣｜ﾉ", false),
                EmoticonEntity(24, "ヾ(´▽｀*;)ゝ”", false),
                EmoticonEntity(24, "へ(ﾟ◇ﾟへ)", false),
                EmoticonEntity(24, "१|˚–˚|५", false),
                EmoticonEntity(24, "ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪", false),
                EmoticonEntity(24, "┛´Д｀┃┛))", false),
                EmoticonEntity(24, "ヘ| ´ω｀ |ﾉ", false),
                EmoticonEntity(24, "♫ ┌༼ຈل͜ຈ༽┘ ♪", false),
                EmoticonEntity(24, "₍₍ ◝( ･’ω’･ )◟ ⁾⁾", false),
                EmoticonEntity(24, "₍₍ ◝(　ﾟ∀ ﾟ )◟ ⁾⁾", false),
                EmoticonEntity(24, "└( ＾ω＾ )」", false),
                EmoticonEntity(24, "o(ﾟｰﾟ*o)", false),
                EmoticonEntity(24, "♪L(´▽｀L )♪", false),
                EmoticonEntity(24, "８（＾－＾゛８）", false),
                EmoticonEntity(24, "（゛８＾－＾）８ﾞ", false),
                EmoticonEntity(24, "┗(｀o´)┓", false),
                EmoticonEntity(24, "┏(｀○´)┛", false),
                EmoticonEntity(24, "┏(｀o´)┓", false),
                EmoticonEntity(24, "┗(｀O´)┛", false),
                EmoticonEntity(24, "└|∵┌|", false),
                EmoticonEntity(24, "└| ∵ |┘", false),
                EmoticonEntity(24, "|┐∵|┘", false),
                EmoticonEntity(24, "|o∵|o", false),
                EmoticonEntity(24, "o|∵o|", false),
                EmoticonEntity(24, "♪└|∵|┐♪", false),
                EmoticonEntity(24, "♪└|∵|┘♪", false),
                EmoticonEntity(24, "♪┌|∵|┘♪", false),
                EmoticonEntity(24, "ヾ(￣ー￣ヾ)", false),
                EmoticonEntity(24, "┌(★o☆)┘", false),
                EmoticonEntity(24, "└(★o★)┐", false),
                EmoticonEntity(24, "┌(☆o★)┘", false),
                EmoticonEntity(24, "ヘ(´m｀ヘ)", false),
                EmoticonEntity(24, "(ノ´m｀)ノ", false),
                EmoticonEntity(24, "“Φ(￣▽￣Φ)", false),
                EmoticonEntity(24, "(Φ￣▽￣)Φ”", false),
                EmoticonEntity(24, "┌|≧∇≦|┘", false),
                EmoticonEntity(24, "(Г・ω・)г", false),
                EmoticonEntity(24, "ヘ(^0^)ヘ", false),
                EmoticonEntity(24, "(´「^o^)「", false),
                EmoticonEntity(24, "7(^-^7)", false),
                EmoticonEntity(24, "♪┏(・o･)┛♪", false),
                EmoticonEntity(24, "〜(꒪꒳꒪;)〜", false),
                //LARGE
                EmoticonEntity(25, "L(‘ω’)┘三└(‘ω’)」", false),
                EmoticonEntity(25, " “:♡.•♬✧⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾*+:•*∴", false),
                EmoticonEntity(25, "(ˇ_ˇ”) ƪ(˘⌣˘)┐ ƪ(˘⌣˘)ʃ ┌(˘⌣˘)ʃ", false),
                EmoticonEntity(25, "(._.) ƪ(‘-‘ ƪ)(ʃ ‘-‘)ʃ(/._.)/ ", false),
                EmoticonEntity(25, " ˓˓(ृ　 ु ॑꒳’)ु(ृ’꒳ ॑ ृ　)ु˒˒˒", false),
                EmoticonEntity(25, "┗( ^o^)┛≡┏( ^o^)┓≡┗( ^o^)┛", false),
                EmoticonEntity(25, "♪(((#^-^)八(^_^*)))♪", false),
                EmoticonEntity(25, "₍₍⁽⁽(ી(^‿ゝ^)ʃ)₎₎⁾⁾", false),
                EmoticonEntity(25, "⁽⁽⁕◟(.öˬö.)◞⁕⁾⁾", false),
                EmoticonEntity(25, "ʅ(◔౪◔ʅ)三(ʃ◔౪◔)ʃ", false),
                EmoticonEntity(25, "♪.*⁽⁽ ◝꒰´꒳`∗꒱◟ ₎₎₊·*", false),
                EmoticonEntity(25, "♪～(◔◡◔ิ)人(╹◡╹๑)～♪", false),
                EmoticonEntity(25, "˄̞⁽⁽୧(꒪ͦᴗ̵̍꒪ͦ=͟͟͞͞ ꒪ͦ ˈ̫̮ ꒪ͦ)୨⁾⁾˄̩̞", false),
                EmoticonEntity(25, "\\(ϋ)/\\(ϋ)/♩", false),
                EmoticonEntity(25, "₍₍⁽⁽(ી(´;ω;` )ʃ)₎₎⁾⁾", false),
                EmoticonEntity(25, "♪ヽ(▽￣ )ﾉ/(＿△＿)ヽ( ￣▽)ﾉ", false),
                EmoticonEntity(25, "♪♪＼(^ω^＼)( /^ω^)/♪♪", false),
                EmoticonEntity(25, "♪└|ﾟ皿ﾟ |┐♪└| ﾟ皿ﾟ |┘♪┌|ﾟ皿ﾟ|┘♪ ", false),
                EmoticonEntity(25, "(（（（o┤｀･ｪ･´├o））））)", false),
                EmoticonEntity(25, "ヽ(○｀･v･)人(･v･´●)ﾉ", false),
                EmoticonEntity(25, " ♪(o=゜▽゜)人(゜▽゜=o)♪", false),
                //LOVE
                EmoticonEntity(26, "(●♡∀♡)", false),
                EmoticonEntity(26, "(｡♥‿♥｡)", false),
                EmoticonEntity(26, "(♥ω♥ ) ~♪", false),
                EmoticonEntity(26, "(♥ω♥*)", false),
                EmoticonEntity(26, "(✿ ♥‿♥)", false),
                EmoticonEntity(26, "✿♥‿♥✿", false),
                EmoticonEntity(26, "乂❤‿❤乂", false),
                EmoticonEntity(26, "٩(♡ε♡ )۶", false),
                EmoticonEntity(26, "ლζ*♡ε♡*ζლ", false),
                EmoticonEntity(26, "⊂（♡⌂♡）⊃", false),
                EmoticonEntity(26, "(๑♡3♡๑)", false),
                EmoticonEntity(26, "(๑♡⌓♡๑)", false),
                EmoticonEntity(26, "♱♡‿♡♰", false),
                EmoticonEntity(26, "⊆♥_㇁♥⊇", false),
                EmoticonEntity(26, "(●♡∀♡))ヾ☆*。", false),
                EmoticonEntity(26, "໒( ♥ ◡ ♥ )७", false),
                EmoticonEntity(26, "༼♥ل͜♥༽", false),
                EmoticonEntity(26, "(灬♥ω♥灬)", false),
                EmoticonEntity(26, "(‘∀’●)♡", false),
                EmoticonEntity(26, "(´∀｀)♡", false),
                EmoticonEntity(26, "（*´▽｀*）", false),
                EmoticonEntity(26, "（´・｀ ）♡", false),
                EmoticonEntity(26, "（´ω｀♡%）", false),
                EmoticonEntity(26, "♥(ˆ⌣ˆԅ)", false),
                EmoticonEntity(26, "꒰˘̩̩̩⌣˘̩̩̩๑꒱♡", false),
                EmoticonEntity(26, "ლ(́◉◞౪◟◉‵ლ)", false),
                EmoticonEntity(26, "⸌̷̻( ᷇ॢ〰ॢ ᷆◍)⸌̷̻♡⃛", false),
                EmoticonEntity(26, "₍՞◌′ᵕ‵ू◌₎♡", false),
                EmoticonEntity(26, "♡ฅ(ᐤˊ꒳ฅˋᐤ♪)", false),
                EmoticonEntity(26, "ʚ♡⃛ɞ(ू•ᴗ•ू❁)", false),
                EmoticonEntity(26, "❣⃛(❛ั◡˜๑)", false),
                EmoticonEntity(26, "( ˭̵̵̵̵͈́◡ु͂˭̵̵̵͈̀ )ˉ̞̭♡", false),
                EmoticonEntity(26, "♡(ŐωŐ人)", false),
                EmoticonEntity(26, "❤⃛ヾ(๑❛ ▿ ◠๑ )", false),
                EmoticonEntity(26, "（*’∀’人）♥", false),
                EmoticonEntity(26, "(°◡°♡).:｡", false),
                EmoticonEntity(26, "ʸ(➜◡ु⚈᷉)♡⃛", false),
                EmoticonEntity(26, "ˉ̞̭(′͈∨‵͈♡)˄̻ ̊", false),
                EmoticonEntity(26, "◟(◔ั₀◔ั )◞ ༘♡", false),
                EmoticonEntity(26, "φ(ﾟ ωﾟ//）♡", false),
                EmoticonEntity(26, "ʸ(ᴖ́◡ु⚈᷉)♡⃛", false),
                EmoticonEntity(26, "ꉂ (′̤ॢ∀ ू‵̤๑))ˉ̞̭♡", false),
                EmoticonEntity(26, "♡♡+.ﾟ(￫ε￩*)ﾟ+.ﾟ", false),
                EmoticonEntity(26, "꒰✪ૢꇵ✪ૢ꒱ෆ⃛", false),
                EmoticonEntity(26, "(●´□`)♡", false),
                EmoticonEntity(26, "(｡･ω･｡)ﾉ♡", false),
                EmoticonEntity(26, "(｡’▽’｡)♡", false),
                EmoticonEntity(26, "（●´∀｀）ノ♡", false),
                EmoticonEntity(26, "₍₍ ( ๑॔˃̶◡ ˂̶๑॓)◞♡", false),
                EmoticonEntity(26, "(๑・ω-)～♥”", false),
                EmoticonEntity(26, "(๑°꒵°๑)･*♡", false),
                EmoticonEntity(26, "～(^з^)-♡", false),
                EmoticonEntity(26, "(๑ˊ͈ ॢꇴ ˋ͈)〜♡॰ॱ", false),
                EmoticonEntity(26, "(ෆ ͒•∘̬• ͒)◞", false),
                EmoticonEntity(26, "♡(㋭ ਊ ㋲)♡", false),
                EmoticonEntity(26, "( •ॢ◡-ॢ)-♡", false),
                EmoticonEntity(26, "(●’ᴗ’σ)σணღ*", false),
                EmoticonEntity(26, "(♡´͈༝`͈)ฅ˒˒", false),
                EmoticonEntity(26, "(•‾⌣‾•)و ̑̑♡", false),
                EmoticonEntity(26, "( ෆຶдෆຶ)", false),
                EmoticonEntity(26, "(⁎⁍̴̛͂▿⁍̴̛͂⁎)*✲ﾟ*｡⋆♡ོ", false),
                EmoticonEntity(26, "(*´o`*)ʖˋʖˋʖˋ～♡", false),
                EmoticonEntity(26, "ღゝ◡╹)ノ♡", false),
                EmoticonEntity(26, "⌓⌓⌕(˃̴◡ुؔ՞ઁ)♡⃛", false),
                EmoticonEntity(26, "♡✧( ु•⌄• )", false),
                EmoticonEntity(26, "(∗ᵒ̶̶̷̀ω˂̶́∗)੭₎₎̊₊♡", false),
                EmoticonEntity(26, "(●මᴗමσ)σணღ*", false),
                EmoticonEntity(26, "(๑╹ڡ╹)╭ ～ ♡", false),
                EmoticonEntity(26, "(๑ Ỡ ◡͐ Ỡ๑)ﾉ♡", false),
                EmoticonEntity(26, "(♡ ὅ ◡ ὅ )ʃ♡", false),
                EmoticonEntity(26, "⁽⁽ପ( •ु﹃ •ु)​.⑅*♡", false),
                EmoticonEntity(26, "꒰ ︠ु௰•꒱ु♡", false),
                EmoticonEntity(26, "(⁎⁍̴̀﹃ ⁍̴́⁎)♡", false),
                EmoticonEntity(26, "(๑ゝᴗම๑) ৷ਕკ~ෆ", false),
                EmoticonEntity(26, "(⋈◍＞◡＜◍)。✧♡", false),
                EmoticonEntity(26, "ε=(｡♡ˇд ˇ♡｡）", false),
                EmoticonEntity(26, "(◍•ᴗ•◍)❤", false),
                EmoticonEntity(26, "(∩˃o˂∩)♡", false),
                EmoticonEntity(26, "♡(.◜ω◝.)♡", false),
                EmoticonEntity(26, "♡〜٩(^▿^)۶〜♡", false),
                EmoticonEntity(26, "♡´･ᴗ･`♡", false),
                EmoticonEntity(26, "♡＾▽＾♡", false),
                EmoticonEntity(26, "♥(✿ฺ´∀`✿ฺ)ﾉ", false),
                EmoticonEntity(26, "♥╣[-_-]╠♥", false),
                EmoticonEntity(26, "♡ლ(-༗‿༗-)ლ♡", false),
                EmoticonEntity(26, "(｡・‧̫・｡).*＊♡", false),
                EmoticonEntity(26, "(◍•ڡ•◍)❤", false),
                EmoticonEntity(26, "-ω(´•ω•｀)♡", false),
                EmoticonEntity(26, "(ෆˊ͈ ु꒳ ूˋ͈ෆ)", false),
                EmoticonEntity(26, "(♡´౪`♡)", false),
                EmoticonEntity(26, "ෆ╹ .̮ ╹ෆ", false),
                EmoticonEntity(26, "( ◜◒◝ )♡", false),
                EmoticonEntity(26, "♡〜ლ(๑癶ᴗ癶๑)ლ〜♡", false),
                EmoticonEntity(26, "(♡´❍`♡)*✧ ✰ ｡*", false),
                EmoticonEntity(26, "(´∩｡• ᵕ •｡∩`) ♡", false),
                EmoticonEntity(26, "( ˊᵕˋ )♡.°⑅", false),
                EmoticonEntity(26, "(♡ >ω< ♡)", false),
                EmoticonEntity(26, "( ๑ ❛ ڡ ❛ ๑ )❤", false),
                EmoticonEntity(26, "（♥￫ｏ￩♥）", false),
                EmoticonEntity(26, "(◍•ᴗ•◍)♡ ✧*。", false),
                EmoticonEntity(26, "（〃・ω・〃）", false),
                EmoticonEntity(26, "(*°∀°)=3", false),
                EmoticonEntity(26, "♥（ﾉ´∀`）", false),
                EmoticonEntity(26, "(♡´艸`)", false),
                EmoticonEntity(26, "(´,,•ω•,,)♡", false),
                EmoticonEntity(26, "❤\\(⸝⸝⸝°⁻̫° ⸝⸝⸝)", false),
                EmoticonEntity(26, "❣╰(⸝⸝⸝´꒳`⸝⸝⸝)╯❣", false),
                EmoticonEntity(26, "(⸝⸝⍢⸝⸝) ෆ", false),
                EmoticonEntity(26, "(⺣◡⺣)♡*", false),
                EmoticonEntity(26, "(๑´ლ`๑)ﾌﾌ♡", false),
                EmoticonEntity(26, "( ̧⸝⸝⍢⸝⸝)ི Շᐱෆ", false),
                EmoticonEntity(26, "( ⌯◞◟⌯)♡", false),
                EmoticonEntity(26, "♡(｡￫ˇ艸￩)", false),
                EmoticonEntity(26, "(灬ºωº灬)♡", false),
                EmoticonEntity(26, "꒰⁎˃ ॢꇴ ॢ˂⁎꒱➴ෆ⃛", false),
                EmoticonEntity(26, "ヽ(o♡o)/", false),
                EmoticonEntity(26, "♡✧。 (⋈◍＞◡＜◍)。✧♡", false),
                EmoticonEntity(26, "٩(ó｡ò۶ ♡)))♬", false),
                EmoticonEntity(26, "٩(*❛⊰❛)ʓਡ～❤", false),
                EmoticonEntity(26, "٩(๑ơలơ)۶♡", false),
                EmoticonEntity(26, "(੭ु ›ω‹ )੭ु⁾⁾♡", false),
                EmoticonEntity(26, "٩(๑∂▿∂๑)۶♡", false),
                EmoticonEntity(26, "\\(-ㅂ-)/ ♥ ♥ ♥", false),
                EmoticonEntity(26, "ヾ(◍’౪`◍)ﾉﾞ♡", false),
                EmoticonEntity(26, "ヽ(愛´∀｀愛)ノ", false),
                EmoticonEntity(26, "♡٩(๑ö⊿ö๑)۶♡", false),
                EmoticonEntity(26, "٩(*ゝڡ◕๑)۶♥", false),
                EmoticonEntity(26, "♡〜٩( ╹▿╹ )۶〜♡", false),
                EmoticonEntity(26, "╰(✿´⌣`✿)╯♡", false),
                EmoticonEntity(26, "(´ ▽｀).。ｏ♡", false),
                EmoticonEntity(26, "( ´͈ ॢꇴ `͈ॢ)･*♡", false),
                EmoticonEntity(26, "(/∇＼*)｡o○♡", false),
                EmoticonEntity(26, "(´▽`ʃƪ)♡", false),
                EmoticonEntity(26, "(◞ꈍ∇ꈍ)◞⋆**✚⃞", false),
                EmoticonEntity(26, "(ღ˘⌣˘ღ)", false),
                EmoticonEntity(26, "（人´∀`*）", false),
                EmoticonEntity(26, "♡o｡.(✿ฺ｡ ✿ฺ)", false),
                EmoticonEntity(26, "♡o｡(๑๏‿ฺ๏๑)｡o♡", false),
                EmoticonEntity(26, "♥～(‘▽^人)", false),
                EmoticonEntity(26, "꒰♡ˊ͈ ु꒳ ूˋ͈꒱.⑅*♡", false),
                EmoticonEntity(26, "*ଯ( ॢᵕ꒶̮ᵕ)ॢഒ*♡", false),
                EmoticonEntity(26, "꒰⑅ᵕ༚ᵕ꒱˖♡", false),
                EmoticonEntity(26, "♡˖꒰ᵕ༚ᵕ⑅꒱", false),
                EmoticonEntity(26, "( ᵒ̴̶̷̤̀ुωᵒ̴̶̷̤́ू )❤”", false),
                EmoticonEntity(26, "(❃•̤ॢᗜ•̤ॢ)✲*｡♡", false),
                EmoticonEntity(26, "(๑॔˃̶ॢ◟◞ ˂̶ॢ๑॓)♡", false),
                EmoticonEntity(26, "(‾̴̴͡͡▿•‾̴̴͡͡ʃƪ)", false),
                EmoticonEntity(26, "( ´͈ ૢᐜ `͈ૢ)･*♡੭ੇ৸♡੭ੇ৸♡", false),
                EmoticonEntity(26, "꒰◍•̤ु௰•̤ु꒱* ∗◌+*♡", false),
                EmoticonEntity(26, "˚‧*♡ॢ˃̶̤̀◡˂̶̤́♡ॢ*‧˚", false),
                EmoticonEntity(26, "´͈ ᵕ `͈ ♡°◌̊", false),
                EmoticonEntity(26, "(*´ ˘ `*).｡oO ( ♡ )", false),
                EmoticonEntity(26, "(人 •͈ᴗ•͈)", false),
                EmoticonEntity(26, "(*˘︶˘*).｡.:*♡", false),
                EmoticonEntity(26, "(*ˊૢᵕˋૢ*)", false),
                EmoticonEntity(26, "❤⃛῍̻̩✧(´͈ ૢᐜ `͈ૢ)", false),
                EmoticonEntity(26, "❤︎⁄⁄꒰* ॢꈍ◡ꈍ ॢ꒱.*˚‧", false),
                EmoticonEntity(26, "♡( ૢ⁼̴̤̆ ꇴ ⁼̴̤̆ ૢ)~ෆ♡", false),
                EmoticonEntity(26, "°₊·ˈ∗♡( ˃̶᷇ ‧̫ ˂̶᷆ )♡∗ˈ‧₊°", false),
                EmoticonEntity(26, "°₊·ˈ∗♡( ˃̶᷇ ‧̫ ˂̶᷆ )♡∗ˈ‧₊°", false),
                EmoticonEntity(26, "ღ˘◡˘ற♡.｡oO", false),
                EmoticonEntity(26, "( ˘͈ ᵕ ˘͈♡)˚๐*˟ ♡", false),
                EmoticonEntity(26, "( ∩ˇωˇ∩)♡", false),
                EmoticonEntity(26, "|๑˃ ॢ‧̫˂ॢ๑ ).*˚‧♡", false),
                EmoticonEntity(26, "♡ฅ(ᐤˊ꒳ฅˋᐤ♪)", false),
                EmoticonEntity(26, "( ื▿ ืʃƪ)", false),
                EmoticonEntity(26, "(o´〰`o)♡*✲ﾟ*｡", false),
                EmoticonEntity(26, "(´⌣`ʃƪ)", false),
                EmoticonEntity(26, "(人*´∀｀)+ﾟ:｡*ﾟ+", false),
                EmoticonEntity(26, "(人´ω｀*)♡", false),
                EmoticonEntity(26, "❣‧✩͓̊(ᵕ̴̤‧̮ ॣᵕ̴̤∗)ɞ₎₎☽˟", false),
                EmoticonEntity(26, "(人´∀`)", false),
                EmoticonEntity(26, "（人*´∀｀）", false),
                EmoticonEntity(26, "ლ(´◉❥◉｀ლ)", false),
                EmoticonEntity(26, "( ˘ ³˘)♥", false),
                EmoticonEntity(26, "( ˘ ³˘)❤", false),
                EmoticonEntity(26, "（。ˇ ⊖ˇ）♡", false),
                EmoticonEntity(26, "（*＾3＾）/～♡", false),
                EmoticonEntity(26, "(｡・//ε//・｡)", false),
                EmoticonEntity(26, "(´ε｀ )♡", false),
                EmoticonEntity(26, "(ʃƪ ˘ ³˘)", false),
                EmoticonEntity(26, "(ʃƪ˘ﻬ˘)", false),
                EmoticonEntity(26, "(づ￣ ³￣)づ", false),
                EmoticonEntity(26, "♡(˃͈ દ ˂͈ ༶ )", false),
                EmoticonEntity(26, "٩꒰ ˘ ³˘꒱۶~♡", false),
                EmoticonEntity(26, "ƪ(♥ﻬ♥)ʃ", false),
                EmoticonEntity(26, "ლ(|||⌒εー|||)ლ", false),
                EmoticonEntity(26, "♡ლζ(♛ε♛*ζლ♡", false),
                EmoticonEntity(26, "†=”Ⴛ̸ ♡(˃͈ દ ˂͈ ༶ )", false),
                EmoticonEntity(26, "(⌯˘̤ ॢᵌ ू˘̤)യෆ̈", false),
                EmoticonEntity(26, "(๑ơ ₃ ơ)♥", false),
                EmoticonEntity(26, "ฅ(♡ơ ₃ơ)ฅ", false),
                EmoticonEntity(26, "(/ ᵒ̴̵̶̷౩ᵒ̴̵̶̷ )/ ᵏᴵˢઽ ❤⃛", false),
                EmoticonEntity(26, "৲( ᵒ ૩ᵕ )৴♡*৹", false),
                EmoticonEntity(26, "(ˊσ̴̶̷̤ ₋̮̑ σ̴̶̷̤ˋ)₊ෆ⃛⁺˚", false),
                EmoticonEntity(26, "ෆ⃛(ˇᵋ ˇෆೄ", false),
                EmoticonEntity(26, "꒰♡⌯́ॢ³⌯̀ॢ꒱", false),
                EmoticonEntity(26, "♪(｡◕ฺˇε ˇ◕ฺ｡）♡", false),
                EmoticonEntity(26, "( *¯ ³¯*)♡", false),
                EmoticonEntity(26, "❣ (●❛3❛●)", false),
                //CLOUDS
                EmoticonEntity(27, "꒰๑ऀ •̆ꈊ͒ू•̆๑ऀ꒱", false),
                EmoticonEntity(27, "♫꒰･‿･๑꒱", false),
                EmoticonEntity(27, "꒰ *๑•ૅʖ̫•́๑꒱", false),
                EmoticonEntity(27, "꒰ ॢö৺ö ૢ๑꒱", false),
                EmoticonEntity(27, "꒰･᷄ु௰･᷅ू꒱", false),
                EmoticonEntity(27, "꒰｡•`ｪ´•｡꒱۶", false),
                EmoticonEntity(27, "꒰｡•ॢ◡-ॢ｡꒱", false),
                EmoticonEntity(27, "꒰·͡ुˑ·ཻू꒱ෆ⃛", false),
                EmoticonEntity(27, "꒰(@｀꒳´)꒱", false),
                EmoticonEntity(27, "꒰•ू꒪͒·̫̮꒪͒•ू꒱", false),
                EmoticonEntity(27, "꒰•ི̫͡ુ•ྀૂ꒱", false),
                EmoticonEntity(27, "꒰˘̩̩̩⌣˘̩̩̩๑꒱♡", false),
                EmoticonEntity(27, "꒰⌯͒•̩̩̩́ ˑ̫ •̩̩̩̀⌯͒꒱", false),
                EmoticonEntity(27, "꒰⌯͒•ɷ•⌯͒꒱", false),
                EmoticonEntity(27, "꒰⑅•ᴗ•⑅꒱", false),
                EmoticonEntity(27, "꒰●꒡ ̫ ꒡●꒱", false),
                EmoticonEntity(27, "꒰♡ˊ͈ ु꒳ ूˋ͈꒱.⑅*♡", false),
                EmoticonEntity(27, "꒰✘Д✘◍꒱", false),
                EmoticonEntity(27, "꒰✩’ω`ૢ✩꒱", false),
                EmoticonEntity(27, "꒰๑ ᷄ω ᷅꒱", false),
                EmoticonEntity(27, "꒰๑•̮̮́౪•̮̮̀๑꒱", false),
                EmoticonEntity(27, "꒰๑͒•̀ुꇵ͒•꒱و ̑̑", false),
                EmoticonEntity(27, "꒰ღ˘‿˘ற꒱❤⃛", false),
                EmoticonEntity(27, "꒰ू ऀ•̥́ꈊ͒ੁ•ૅू॰˳ऀ꒱ ͟͟͞ ̊ ̥ ̥", false),
                EmoticonEntity(27, "꒰ू•௰ू•๑꒱", false),
                EmoticonEntity(27, "꒰ෆ❛ั ु▿❛ั ु꒱", false),
                EmoticonEntity(27, "٩꒰ ̃•ε• ̃๑꒱۶⁼³₌₃", false),
                EmoticonEntity(27, "٩꒰ ´ᆺ`꒱۶", false),
                EmoticonEntity(27, "٩꒰ ˘ ³˘꒱۶~♡", false),
                EmoticonEntity(27, "٩꒰･ัε･ั ꒱۶", false),
                EmoticonEntity(27, "٩꒰｡•‿•｡꒱۶", false),
                EmoticonEntity(27, "٩꒰• ε •꒱۶⁼³", false),
                EmoticonEntity(27, "٩꒰•௰︡๑꒱ु", false),
                EmoticonEntity(27, "٩꒰ಂ❛ ▿❛ಂ꒱۶♡", false),
                EmoticonEntity(27, "٩꒰๑ ´∇`๑꒱۶", false),
                EmoticonEntity(27, "٩꒰๑• ̫•๑꒱۶♡", false),
                EmoticonEntity(27, "٩꒰๑• ³•๑꒱۶", false),
                EmoticonEntity(27, "٩꒰ɵ̥̥▿ɵ̥̥●꒱۶", false),
                EmoticonEntity(27, "٩꒰ʘʚʘ๑꒱۶", false),
                EmoticonEntity(27, "ू꒰ꇐωꇐ ू꒱", false),
                EmoticonEntity(27, "ꉂꉂ꒰•̤▿•̤*ૢ꒱", false),
                EmoticonEntity(27, "ପ꒰⑅°͈꒳°͈꒱੭ु⁾⁾", false),
                EmoticonEntity(27, "꒰⑅ᵕ༚ᵕ꒱˖♡", false),
                EmoticonEntity(27, "♡˖꒰ᵕ༚ᵕ⑅꒱", false),
                EmoticonEntity(27, "꒰⑅ᵕ༚ᵕ꒱˖♡ªʳⁱ૭ªᵗ°♡˖꒰ᵕ༚ᵕ⑅꒱", false),
                EmoticonEntity(27, "꒰⁎❛⃘ͫ ⍘⃘ ❛⃘ͫ⁎꒱", false),
                EmoticonEntity(27, "꒰*⑅˃̶͈ ৺˂̶͈⑅꒱੭ु⁾⁾·°", false),
                EmoticonEntity(27, "꒰•̫͡•ོ꒱", false),
                EmoticonEntity(27, "٩꒰ ˘ ³˘꒱۶ⒽⓤⒼ♥♡̷♡̷", false),
                EmoticonEntity(27, "꒰⌯͒•·̫•⌯͒꒱", false),
                EmoticonEntity(27, "꒰๑ऀ •̆ꈊ͒ू•̆๑ऀ꒱⁇", false),
                EmoticonEntity(27, "꒰๑͒ ु•ꇵ͒•`๑͒꒱", false),
                EmoticonEntity(27, "ᵎᵎᵎ꒰ฅ ͒•ૅꇵ͒•⌯͒꒱ฅ", false),
                EmoticonEntity(27, "٩꒰´·⌢•｀꒱۶⁼³₌₃", false),
                EmoticonEntity(27, "꒰╬•᷅д•᷄╬꒱", false),
                EmoticonEntity(27, "ଽ꒰⌓̈ ॢ꒱ ̉ ̉", false),
                EmoticonEntity(27, "꒰♡˃̶̤́ ॢ꒳ ॢ˂̶̤̀ ꒱·◌*.♡", false),
                EmoticonEntity(27, "꒰⁎ᵉ̷͈ ॣ꒵ ॢᵉ̷͈⁎꒱໊", false),
                EmoticonEntity(27, "⋆⑅˚₊*୧⃛꒰ɞ̴̶̷◟◞ʚ̴̶̷̷꒱୨⃛*₊˚", false),
                EmoticonEntity(27, "✬̴⃛꒰⁍̴ꈊ ॢ⁍̴⌯꒱", false),
                EmoticonEntity(27, "꒰•́ॢ৺•̀ॢ๑͒꒱", false),
                EmoticonEntity(27, "꒰◍•̤ु௰•̤ु꒱* ∗◌+*♡", false),
                EmoticonEntity(27, "ପ꒰*⑅ ॢ˘͈ꀧ˘͈ ॢ⑅꒱✩.*˚", false),
                EmoticonEntity(27, "꒰⌗´͈ ᵕ ॣ`͈⌗꒱৩", false),
                EmoticonEntity(27, "˪৹⌵ೕ꒰๑•‧̮ૣ•ૣ๑꒱", false),
                EmoticonEntity(27, "꒰◍ᐡᐤᐡ◍꒱", false),
                EmoticonEntity(27, "꒰๑•௰•๑꒱", false),
                EmoticonEntity(27, "‘٩꒰｡•◡•｡꒱۶’", false),
                EmoticonEntity(27, "↷꒰ू´•௰ू• `꒱↷", false),
                EmoticonEntity(27, "ᔪ꒰ ꒪ω꒪ |||꒱", false),
                EmoticonEntity(27, "꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥", false),
                EmoticonEntity(27, "꒰´꒳`∗꒱", false),
                EmoticonEntity(27, "꒰´꒳`꒱", false),
                EmoticonEntity(27, "꒰∗´꒳`꒱", false),
                EmoticonEntity(27, ".꒰ϱ﹏-๑꒱‧*Zz｡", false),
                EmoticonEntity(27, "꒰๑⃙⃘ϱ॔꒳˘͈( ˘͈꒳˘͈๑⃙⃘꒱♡", false),
                EmoticonEntity(27, "꒰⌯͒•̩̩̩́ ᴗ •̩̩̩̀⌯͒꒱", false),
                EmoticonEntity(27, "❤︎⁄⁄꒰* ॢꈍ◡ꈍ ॢ꒱.*˚‧", false),
                EmoticonEntity(27, "·˚*୨୧꒰∗ɞ̴̶̷ु ·̮ ूɞ̴̶̷∗꒱୨୧*˚·", false),
                EmoticonEntity(27, "꒰๑•‧̮ૣ•ૣ๑꒱*･.｡", false),
                EmoticonEntity(27, "ू꒰΄ ิ̤۝ ิ ̤꒱ु", false),
                EmoticonEntity(27, "꒰ ்ͦੰ ⍘⃘  ்ͦੰ꒱", false),
                EmoticonEntity(27, "꒰ ॢ꒱˶´ꇵ͒`˶꒰ ॢ꒱", false),
                EmoticonEntity(27, "꒰๑ ̇̅ ॄ ̇̅๑꒱", false),
                EmoticonEntity(27, "꒰⁎ ✪̼ ◡ ✪̼` ⁎꒱﹡Տҽҽ վօմ⁎☪*✩", false),
                EmoticonEntity(27, "꒰✩˙˟˙✩꒱", false),
                EmoticonEntity(27, "꒰♡ᵒ̴̶̷ꇵ͒ᵒ̴̶̷♡꒱*ೄ˚", false),
                EmoticonEntity(27, "*¨*•.¸꒰๑ ᷄ω ᷅꒱", false),
                EmoticonEntity(27, "꒰ꄬຶູྀ ॄ ꄬຶູི ꒱", false),
                EmoticonEntity(27, "꒰ꄬຶູྀ ॄ ꄬຶູི ꒱ ⃛˚", false),
                EmoticonEntity(27, "꒰ ︠ु௰•꒱ु♡", false),
                EmoticonEntity(27, "♪.*⁽⁽ ◝꒰´꒳`∗꒱◟ ₎₎₊·*", false),
                EmoticonEntity(27, "꒰◍ᐡᐤᐡ◍꒱ᐝ.∗̥✩⁺˚⑅", false),
                EmoticonEntity(27, "꒰ ꒪⌑꒪꒱˖ꂚ*ᵎ", false),
                EmoticonEntity(27, "∠꒰’౪’꒱✧", false),
                EmoticonEntity(27, "꒰ •͈́ ̫ •͈̀ ꒱ˉ̞̭", false),
                EmoticonEntity(27, "⁽⁽꒰๑•‧̮ૣ•ૣ๑꒱⁾⁾", false),
                EmoticonEntity(27, "*⋆⑅⃟◌˚꒰ˊૢᵕˋૢෆ꒱", false),
                EmoticonEntity(27, "꒰๑꒪ɷ꒪꒱", false),
                EmoticonEntity(27, "꒰⁎❛⃘ੌ ᵕ ❛⃘ੌ⁎꒱", false),
                EmoticonEntity(27, "꒰⁎′̥̥̥ ⌑ ‵̥̥̥ ꒱", false),
                EmoticonEntity(27, "˖*٩꒰｡‾᷅⌑‾᷅｡;꒱۶ఽ*.·", false),
                EmoticonEntity(27, "꒰๑*´ᗜ`*꒱*›◡‹꒱꒱", false),
                EmoticonEntity(27, "⅀⑈꒰′Ꮌ̮‵꒵꒱՞", false),
                EmoticonEntity(27, "*͛꒰ू ऀ•̥́◟◞•ૅू॰˳ऀ꒱ ͟͟͞ ̊ ̥ ̥", false),
                EmoticonEntity(27, "*+:꒰◍•ᴗ•◍꒱:+*", false),
                EmoticonEntity(27, "꒰｡ › ·̮ ‹ ｡꒱", false),
                EmoticonEntity(27, "◟꒰⌳̈ ꒱", false),
                EmoticonEntity(27, "꒰♡⌯́ॢ³⌯̀ॢ꒱", false),
                EmoticonEntity(27, "꒰ˇ❝͋ꊗ❝͋ˇ꒱ค˒˒", false),
                EmoticonEntity(27, "꒰ີ∗ˊ↥ˋ∗ ꒱ີˉ̶̡̭̭", false),
                EmoticonEntity(27, "◌ต꒰｡•̤༝•̤｡꒱ต◌", false),
                EmoticonEntity(27, "꒰๑͒•௰•๑͒꒱ℒℴѵℯ❤", false),
                EmoticonEntity(27, "꒰(ू•‧̫•ू )꒱", false),
                EmoticonEntity(27, "꒰ ु•̫•̫ ु꒱", false),
                EmoticonEntity(27, "꒰੭ु ऀᵒ̴̶̷̤́ꋢᵒ̴̶̷̤̀ ऀ꒱੭ु⁾⁾", false),
                EmoticonEntity(27, "♡⃛=͟͟͞͞꒰ˇ❝͋ुꈊ❝͋ुˇ꒱⁼³₌₃", false),
                EmoticonEntity(27, "꒰⁎❛⃘ ⍘⃘ ❛⃘⁎꒱", false),
                EmoticonEntity(27, "꒰⌯͒ඹ ·̫ ඹ⌯͒꒱", false),
                EmoticonEntity(27, "*͛꒰ू ऀ•̥́◟◞•ૅू॰˳ऀ꒱ ͟͟͞ ̊ ̥ ̥", false),
                EmoticonEntity(27, "꒰⁎❛⃘ੌ ⍘⃘ ❛⃘ੌ⁎꒱", false),
                EmoticonEntity(27, "꒰·͡ुˑ·ཻू꒱*̫ෆ๋*̫꒰•ི̫͡ુ•ྀૂ꒱", false),
                EmoticonEntity(27, "ｑ꒰*ゝω・꒱ﾉ″", false),
                EmoticonEntity(27, "✧.*꒰⁎❝͋॔༶̶❝͋॓⁎ॢ꒱*·✧", false),
                EmoticonEntity(27, "◟꒰∗⌵̈꒱◞✩◟꒰⌔̈∗꒱◞", false),
                EmoticonEntity(27, "꒰̤◴ㅈ◴̵̤꒱", false),
                EmoticonEntity(27, "꒰⍨꒱", false),
                EmoticonEntity(27, "꒰⑅ˊ͈ ˙̫ ˋ͈⑅꒱", false),
                EmoticonEntity(27, "꒰✪ૢꇵ✪ૢ꒱ෆ⃛", false),
                EmoticonEntity(27, "꒰⁎˃ ॢꇴ ॢ˂⁎꒱➴ෆ⃛", false),
                EmoticonEntity(27, "Σ꒰๑•ॢд •ॢ๑꒱", false),
                EmoticonEntity(27, "꒰ ੭ु・ω ・꒱ ੭ु⁾⁾", false),
                EmoticonEntity(27, "♫꒰･◡･๑꒱", false),
                EmoticonEntity(27, "꒰#’ω`#꒱੭", false)
            )
            return result
        }

    }
}